sublimelsp/LSP

- main.py
I'd suggest some changes to the output panel creation.
1. Use a common function to create both panels to ensure common style.
2. Make sure output panel is marked read-only to prevent accidentally modifications
> Output panel settings

- main.py
> add `initialized` notification

- main.py
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textdocumentitem
> didOpen requires TextDocumentItem.version

- main.py
> some completions do not have details

- LSP.sublime-settings
- docs/index.md
- main.py
I just prefer a highlight box over the underline.
> option to choose a different highlight style

- LSP.sublime-settings
- docs/index.md
> Make ocaml work!

- main.py
Diagnostics removal was not (ever?) working as found in #67
> Only filter on_close handler on syntax to remove diagnostics

- main.py
> Add synchronization and applyEdit capabilities

- main.py
> enable word completions and explicit completions

- LSP.sublime-settings
- docs/index.md
- Add Golang lsp settings
- Change settings / docs for Golang
> Add Golang lsp settings

- main.py
> Only show diagnostics hover for current position, not whole line.

- main.py
> make queue_did_change more synchronous

- Keymaps/Default (Linux).sublime-keymap
- Keymaps/Default (OSX).sublime-keymap
- Keymaps/Default (Windows).sublime-keymap
- main.py
- stubs/mdpopups.pyi
This just adds the browsing functionality, let's leave the parameter highlighting for another PR.
Note the usage of `mdpopups.update_popup`now.
> Browse function overloads with the up/down arrow keys (with no other stuff)

- plugin/formatting.py
Resolve TODO of 604df779ee63daa1c008b9e1b12169a61f4007ea
> Read view tab size

- plugin/completion.py
* Cancel completion popup when backspacing past completion start
Then, when tab-completing (`insert_best_completion`) from a hidden completions list:
* If last completions are still relevant, return them immediately
* If no completions are available, undo tab insertion just before LSP completions are shown.
Credit to Typescript plugin and Jedi plugins for documenting behaviour.
> Fixes for tab completion and backspacing past completion start

- plugin/completion.py
- plugin/core/rpc.py
Fixes #131 and properly exposes errors to code making language server requests.
> Handle completion errors

- plugin/hover.py
these often contain things worth hovering over. see https://github.com/tomv564/LSP/issues/183
> allow hover on constant, keyword, storage

- .gitignore
- plugin/completion.py
> Prevent selection of CompletionItem hint if its label is empty

- plugin/core/rpc.py
My last pull request contained a mistake 🙁 
Sorry for that...
> Fixed incorrect retrieval of 'error' state

- plugin/core/main.py
- plugin/core/rpc.py
For issue #236, where dead language servers continue to spew errors in the logs.
Changes:
* Prevent races terminating the process
* Observe process set to `None`
* Offer restart or ignore dialog:
> cleaner termination + offer restart

- LSP.sublime-settings
https://github.com/REditorSupport/languageserver
> add R languagae server

- plugin/diagnostics.py
Closes #283 
If open, the diagnostic panel will close. Else, it will open. :)
> Feature to toggle diagnostic panel

- Menus/Main.sublime-menu
Closes #302
Add an entry in the main LSP menu for key bindings.
> Add menu option for key bindings 

- plugin/core/rpc.py
> id is an integer

- LSP.sublime-settings
- plugin/core/settings.py
- plugin/diagnostics.py
> add setting to control diagnostics severity level

- plugin/core/test_url.py
This PR fixes the indentation that is causing the build to fail. It replaces the tabs with 4 spaces. There is also missing `import sys`.
> Fix build (indentation + missing import)

- plugin/core/edit.py
This PR addresses issue #325 by sorting the changes.
In my test scenarios, the edits worked as expected.
> Sort changes by start offset

- plugin/completion.py
- plugin/configuration.py
- plugin/core/clients.py
- plugin/core/documents.py
- plugin/core/main.py
- plugin/core/process.py
- plugin/core/rpc.py
- plugin/core/sessions.py
- plugin/core/settings.py
- plugin/core/test_rpc.py
- plugin/core/test_session.py
- plugin/core/transports.py
- plugin/core/types.py
- plugin/diagnostics.py
- plugin/highlights.py
- plugin/hover.py
- plugin/signature_help.py
Promotes ConfigState to a Session object that also handles initialising and shutting down LSP clients.
Introduces the process module for process-related functionality
Removes a chunk of specialised code out of main.py, including shorting the session initializing callback.
> Testable sessions

- plugin/core/popups.py
Popups using `--colorish` should be using `var(--colorish)` instead.
> Fix colorish variable in popups

- docs/index.md
> improve docs for jsts and plain js servers

- LSP.sublime-settings
- tests/test_configs.py
It will be handled directly by https://github.com/REditorSupport/sublime-ide-r
(if it is the practice that you are going the adopt).
> remove R language settings

- Syntaxes/References.sublime-syntax
- plugin/references.py
closes #412
The only thing about this PR that I don't understand is the `References.sublime-syntax` file. 
I just copied the `Diagnostics.sublime-syntax` and made some adjustments, like deleted some things, renamed some.
The syntax looks ok to me, but I would suggest someone else who knows better to have a look at it, just to check if everything is alright.  
If you have any question, concern, let me know.
> Change look of references

- plugin/core/popups.py
- plugin/hover.py
> Render all diagnostics in hovers

- plugin/diagnostics.py
> Filter diagnostics while rendering panel output

- plugin/core/protocol.py
- plugin/core/sessions.py
- plugin/symbols.py
fix https://github.com/tomv564/LSP/issues/504
> add new symbol kinds

- plugin/signature_help.py
Should resolve #517. @jfcherng, @carlevison, could you check out these changes locally for intelephense?
> Account for 'MarkupContent' (intead of just 'str') in signature help

- docs/index.md
Add some problems that I encountered while trying to install and use the `clangd` LSP today.
>  Update docs on how to install clangd

- LSP.sublime-settings
- docs/index.md
- plugin/core/settings.py
- plugin/core/types.py
- plugin/references.py
> Add setting for quick panel monospace font (disabled by default)

- LSP.sublime-settings
There is an official Go language server taking shape: https://github.com/golang/go/wiki/gopls
> Add configuration for gopls

- plugin/completion.py
- plugin/configuration.py
- plugin/core/configurations.py
- plugin/core/documents.py
- plugin/core/registry.py
- plugin/core/settings.py
- plugin/core/test_configurations.py
- plugin/core/test_windows.py
- plugin/diagnostics.py
- plugin/highlights.py
- plugin/hover.py
- plugin/signature_help.py
Unit tests for core/configuration.py
Required removing the settings import and passing in `client_configs.all`
> Core config testing

- plugin/hover.py
Show only the actions that the server can handle during the hover event
> Show symbol actions by client capabilities

- plugin/code_actions.py
- plugin/core/diagnostics.py
- plugin/core/registry.py
- plugin/core/test_diagnostics.py
- plugin/core/test_windows.py
- plugin/core/windows.py
- plugin/diagnostics.py
- plugin/hover.py
Removes "global" diagnostics, lookup via registry instead of accessing data via imported functions
> Testing core/diagnostics

- LSP.sublime-settings
- docs/index.md
Add config for Scala's new LSP server, [Metals](https://scalameta.org/metals/)
> Add configuration for Metals and update Scala doc

- LSP.sublime-settings
- docs/index.md
- plugin/completion.py
- plugin/core/settings.py
- plugin/core/types.py
I wrote it to get snippets out of a specific language server, suspect no one else has used it.
> Remove resolve_completion_for_snippets feature

- README.md
- docs/index.md
> Add lua-ls server

- Keymaps/Default (Linux).sublime-keymap
- Keymaps/Default (OSX).sublime-keymap
- Keymaps/Default (Windows).sublime-keymap
this should prove helpful, as it reduces the need for many shortcuts.
> Show a list of available LSP commands

- plugin/completion.py
> Account for empty dict as completionProvider

- plugin/core/sessions.py
fix for https://github.com/tomv564/LSP/issues/655
> Fix initialize JSON: Remove extra brackets

- plugin/symbols.py
> Gracefully handle cancellation of textDocument/documentSymbol

- Keymaps/Default (Linux).sublime-keymap
- Keymaps/Default (OSX).sublime-keymap
- Keymaps/Default (Windows).sublime-keymap
- Menus/Context.sublime-menu
- boot.py
- docs/features.md
- plugin/core/protocol.py
- plugin/core/test_session.py
- plugin/goto.py
- plugin/hover.py
- tests/setup.py
- tests/test_goto.py
- Add support for textDocument/typeDefinition
- Add support for textDocument/declaration
- Add support for textDocument/implementation
close #636
> Add support for all the modern "goto" requests

- plugin/core/clients.py
- plugin/core/sessions.py
- plugin/core/test_session.py
- plugin/core/test_windows.py
- plugin/core/windows.py
- tests/setup.py
I had to move the MockWindow and MockView to test_sublime.py for this.
close #654
> Handle allowed messages before initialize

- .travis.yml
> Make sure the ubuntu distro is trusty on travis

- plugin/hover.py
> fix(hover): fix typo

- LSP.sublime-settings
Especially for indicating how to add a license key for it.
https://github.com/bmewburn/vscode-intelephense/issues/614#issuecomment-523809437
> Add initializationOptions for intelephense (PHP LSP)

- docs/cplusplus.md
- Put note about EOL cquery
- Inform people about 10.14 macOS system headers bug (or deliberate?)
- Inform people about simpler compile_flags.txt versus more advanced compile_commands.json
> Update c++ documentation

- docs/index.md
> add python virtualenv  config explanation

- README.md
Reason: https://github.com/tomv564/LSP/pull/316
> Update Julia link in readme

- LSP.sublime-settings
- docs/features.md
- plugin/color.py
- plugin/completion.py
- plugin/core/settings.py
- plugin/core/types.py
- plugin/highlights.py
- plugin/hover.py
- plugin/signature_help.py
For #629 and #574
We should probably move the colorProvider toggle into this as well.
> Add disabled_capabilities settings for hover and completion

- plugin/color.py
- plugin/core/windows.py
> Improve color provder

- README.md
- docs/index.md
> Add terraform-lsp server

- docs/features.md
- plugin/core/completion.py
- plugin/core/settings.py
- plugin/core/test_completion.py
- plugin/core/types.py
As discussed in #722 and seen causing confusion with metals in #771.
> Remove "prefer_label_over_filter_text" setting

- plugin/completion.py
> Justify apply_additional_edits properly, and make the flags a bit more readable

- plugin/core/sessions.py
- plugin/goto.py
- tests/test_goto.py
For our fellow ccls users :) Verified with ccls.
close #764
> Make a trivial handler for 'LocationLink'

- plugin/core/test_mocks.py
- tests/.gitignore
- tests/setup.py
- tests/test_pre_save.py
This doesn't actually cover the transport/threads handling as we're dealing with a MockClient. It only verifies the "business logic" :)
> Add a UnitTesting test for the format-on-save feature

- docs/index.md
I wanted to make Python Language Server installation instructions as clear as possible to make life easier for others.
> Update Python Language Server setup instructions

- LSP.sublime-settings
Update syntaxes for javascript-typescript-langserver and typescript-language-server
Add JavaScript language to typescript-language-server
> Update syntax and languages for JavaScript

- .github/workflows/main.yml
- tests/adjust_unittesting_config_for_ci.py
- tests/setup.py
- unittesting.json
We may test on all three platforms
> Move to github actions

- codecov.yml
> Disable patch coverage reporting - we're not at that level yet

- plugin/core/types.py
- plugin/core/windows.py
- tests/test_mocks.py
Documentation from the ST3 API page:
> Returns the current change count. Each time the buffer is modified, the change count is incremented. The change count can be used to determine if the buffer has changed since the last it was inspected.
> Use View.change_count() instead of DocumentState

- Commands/Default.sublime-commands
I know, I am nitpicking,
But I just can't seem to remember the new commands for toggling the panel. :man_facepalming: 
Can we name them with less words and maybe rearrange the words to be more easy to remeber? :D
> Maybe simpler naming of commands for toggeling the panels? :)

- LSP.sublime-settings
- messages/0.9.5.txt
- plugin/core/sessions.py
- plugin/core/settings.py
- plugin/core/types.py
- tests/test_session.py
> Turn initialize timeout number into a setting

- LSP.sublime-settings
[Changelog](https://rust-analyzer.github.io/thisweek/2020/02/24/changelog-13.html)
Relevant PR: rust-analyzer/rust-analyzer#3216
> Update rust-analyzer binary name

- plugin/diagnostics.py
> Remember to set lsp_diagnostic_phantom to false when cleared

- plugin/core/sessions.py
- tests/test_session.py
> Differentiate between `null` init options and empty dict

- LSP.sublime-settings
- docs/index.md
The recommended way is to use LSP-eslint.
That said, the default config was *very*
specific, so I doubt it worked for many people ;)
> remove outdated eslint config

- boot.py
This should be everything. Please check if I forgot something!
> Narrow down imports

- plugin/completion.py
It is unclear to me whether sublime.CompletionList is thread-safe. It doesn't seem to be thread-safe when looking at the details in sublime_plugin.py and sublime.py. So just to be on the safe side, let us resolve the promise from the main thread.
By the way, I noticed ST freezing when using clangd, I don't experience freezes anymore with this change. I'm not 100% sure if it's related, but since there's no threading locks being used in sublime_plugin.py I'm pretty sure it's not thread safe.
> Resolve the promise on the main thread

- LSP.sublime-settings
- docs/index.md
Also remove metals from the default servers list as LSP-metals provides more features and better experience
> Add LSP-metals to the dedicated packages list

- plugin/completion.py
The auto-complete triggers do not de-register themselves when restarting ST:
>>> view.settings().get("auto_complete_triggers")
[{'characters': '<', 'selector': 'text.html, text.xml'},
{'selector': 'punctuation.accessor'},
{'characters': '.', 'selector': '- comment - punctuation.definition.string.end'},
{'characters': '.', 'selector': '- comment - punctuation.definition.string.end'},
{'characters': '.', 'selector': '- comment - punctuation.definition.string.end'},
{'characters': '.', 'selector': '- comment - punctuation.definition.string.end'},
{'characters': '.', 'selector': '- comment - punctuation.definition.string.end'}]
This commit adds a token to the registration dict that we re-use in a new
`__del__` method to remove our registration. The token is the name of the
language server. …
> Fix: too many auto-complete registrations

- docs/index.md
- plugin/core/configurations.py
- plugin/core/sessions.py
- plugin/core/settings.py
- plugin/core/types.py
- tests/test_configs.py
- tests/test_session.py
This would allow language handlers to define client experimental capabilities
A fallow up on https://github.com/sublimelsp/LSP/issues/927#issuecomment-612252151
> Add experimental_capabilities setting

- plugin/core/rpc.py
- plugin/core/windows.py
This is a first step towards different kinds of loggers, for usage in https://github.com/rchl/lsp-log-parser
> Extract an abstract base class from the logger

- plugin/core/protocol.py
- plugin/core/rpc.py
- plugin/core/transports.py
- plugin/formatting.py
- tests/setup.py
- tests/test_rpc.py
- tests/test_single_document.py
- unittesting.json
Try re-applying the sync fixes.
> Handle incoming notifications/responses during a sync request (#787)

- tests/test_completion.py
- tests/test_single_document.py
Seems like those work fine after latest changes.
> Re-enable formatting tests that seems to work fine

- plugin/core/handlers.py
Needed to address cases when there is more than one level of
sub-classing. Required for https://github.com/sublimelsp/lsp_utils/pull/5
> Initialize final subclass for each LanguageHandler

- plugin/core/documents.py
- plugin/core/typing.py
- plugin/core/views.py
- plugin/core/windows.py
- tests/test_incremental_sync.py
- tests/test_single_document.py
Subsequent simple insertions are stitched together.
Let's try handling simple erasures at a later date.
> Optimize incremental text sync

- plugin/core/windows.py
> Account for floating point numbers as percentages

- plugin/core/configurations.py
- plugin/core/workspace.py
This makes the code a little bit easier to follow.
> Encapsulate some functions to make them more understandable

- plugin/completion.py
- plugin/core/views.py
- tests/test_views.py
> Improve whitespace and link parsing in documentation popup

- plugin/core/signature_help.py
- plugin/core/views.py
- plugin/signature_help.py
- tests/test_documents.py
- tests/test_signature_help.py
This makes all tests pass.
There were some errors in test_signature_help.py, and test_documents.py caused an extra session to exist, making the completion tests fail.
> Unit test fixes

- docs/index.md
- plugin/core/collections.py
- plugin/core/configurations.py
- plugin/core/sessions.py
- plugin/core/settings.py
- plugin/core/types.py
- plugin/core/views.py
- tests/test_collections.py
- tests/test_configurations.py
- tests/test_views.py
Both styles work: you can put a dict in the "settings" of a server,
or you can put "paths" in the "settings" of a server.
> Dotted server settings

- plugin/code_actions.py
I'd like this part to be synced with ST4 so that it's easier for me to work on CAOS (I'm working on ST4 but want to merge to master in the end).
> Sync code_actions.py with ST4 branch

- plugin/core/settings.py
- tests/setup.py
- tests/test_configurations.py
- tests/test_session.py
Must reset cached object on removing/adding configs.
> Fix timeouts in tests

- plugin/completion.py
Showing and updating popups from ST's main thread seems to fix the issue.
> Hopefully fix AC disappearing

- plugin/completion.py
I haven't tested this, but it seems straightforward. If anything comes up from a user we can improve upon it.
> Optionally run a server command after inserting a completion

- plugin/core/main.py
- plugin/core/sessions.py
- plugin/core/windows.py
- plugin/core/workspace.py
- tests/test_workspace.py
We can now rely on ST for this.
> Use the new project callbacks from EventListener

- plugin/code_actions.py
- plugin/color.py
- plugin/completion.py
- plugin/core/registry.py
- plugin/formatting.py
- plugin/highlights.py
- plugin/signature_help.py
The extra indirection is no longer needed.
> Remove client_from_session

- plugin/code_actions.py
- plugin/core/registry.py
- plugin/execute_command.py
- plugin/formatting.py
- plugin/goto.py
- plugin/hover.py
- plugin/references.py
- plugin/rename.py
- plugin/symbols.py
Replace it with `self.session("capability.path")`.
> Replace 'client_with_capability' and 'has_client_with_capability'

- plugin/code_actions.py
- plugin/core/documents.py
- plugin/core/registry.py
- plugin/execute_command.py
- plugin/formatting.py
- plugin/goto.py
- plugin/hover.py
- plugin/references.py
- plugin/rename.py
- plugin/symbols.py
- tests/test_completion.py
It looks like we more or less have one LspTextCommand per server capability.
> Standardize on having a "capability" in your LspTextCommand

- plugin/core/rpc.py
Error responses were not marked as errors in the logs.
> Mark error responses properly in server logs

- plugin/core/documents.py
- plugin/core/windows.py
I'm hitting this bug dozens of times a day so I had enough.
Once the ST bug is fixed this should become a no-op and shouldn't cause any issues since the trigger is very specific (a=0, b=0 and text='') and I can't see how it would trigger in normal cases.
I've split `notify_did_change` into two methods so that I can `notify_sessions` directly with `None` `changes` as that triggers full document sync in `did_change_text_document_params`.
> Workaround on_text_changed bug messing up view content synchronization

- plugin/code_actions.py
- plugin/color.py
- plugin/core/registry.py
- plugin/core/windows.py
- plugin/highlights.py
There's a bunch of places where we run a function at a later point
in time, but only when a certain stability condition holds.
> Refactor "debouncing" into a function

- plugin/core/views.py
- plugin/formatting.py
> Use the range formatter if there's no full range formatter

- plugin/core/sessions.py
- plugin/core/views.py
- tests/test_server_requests.py
- tests/test_views.py
I need this for my pyls helper package which I am working on.
> Expand variables in didChangeConfiguration notification

- Commands/Default.sublime-commands
- Menus/Main.sublime-menu
Also remove reference to LSP as it's a global keybindings file, not
specific to LSP.
> Fix user keybindings template to use array rather than object

- boot.py
- plugin/documents.py
- plugin/goto.py
- plugin/references.py
- plugin/rename.py
- plugin/session_view.py
I will need this for my one-view-event-listener mega plan.
> Move documents.py and session_view.py up one level

- Keymaps/Default (Linux).sublime-keymap
- Keymaps/Default (OSX).sublime-keymap
- Keymaps/Default (Windows).sublime-keymap
- boot.py
- plugin/code_actions.py
- plugin/core/protocol.py
- plugin/core/rpc.py
- plugin/core/windows.py
- plugin/documents.py
- plugin/formatting.py
- plugin/save_command.py
- tests/setup.py
- tests/test_single_document.py
- There are now three separate tasks, one for code actions on save,
one for formatting request, and one for WillSaveWait request.
- Those tasks are registered onto LspSaveCommand and run sequentially on saving.
- Tasks by default have the timeout set to 1s (matching former sync request) and code actions to 2s and controlled by a setting.
~~I still need to clean this up and figure out the timeout stuff (timeout separate for each task or for whole save action?).~~
> Make formatting tasks run asynchronously

- plugin/core/configurations.py
- plugin/core/registry.py
- plugin/core/types.py
- plugin/core/windows.py
- plugin/core/workspace.py
- plugin/session_view.py
They are not necessary anymore.
> Remove WindowLike, ViewLike and SublimeLike protocol classes

- plugin/hover.py
- We used show_popup two times, but it's a smoother experience to use
show_popup and then update_popup.
- There's a bug in ST where it thinks the view is modified when doing
a show_popup or an add_regions call with an edit token. Workaround
this by running sublime.set_timeout.
See: https://github.com/sublimehq/sublime_text/issues/3424
> Fixup hover popup behavior

- boot.py
- plugin/documents.py
- plugin/hover.py
The disabled_capabilities check is now also not cached. So if you update disabled_capabilities in your settings, you will see the effect immediately.
> Merge DocumentSyncListener and HoverHandler

- Commands/Default.sublime-commands
- boot.py
- plugin/tooling.py
for setting up language server helpers.
> Add a dev command to parse VSCode package.json files

- Keymaps/Default (Linux).sublime-keymap
- Keymaps/Default (OSX).sublime-keymap
- Keymaps/Default (Windows).sublime-keymap
> Do not override the built-in "Next Modification" keybinding

- docs/features.md
Follow up on https://github.com/sublimelsp/LSP/pull/1191
> Update Code Actions Doc

- plugin/symbols.py
- Put the name (without spaces) in the first row
- Put the parent hierarchy in the second row
- Put the kind and detail in the third row
~~This only works when the server returns DocumentSymbol[] as response,
not when it returns SymbolInformation[].~~ Works for both DocumentSymbol[] and SymbolInformation[] return types.
close #1172
> Document symbol improvements

- plugin/core/windows.py
- plugin/documents.py
- plugin/session_buffer.py
- plugin/session_view.py
> Diagnostics summary count in status bar should be global

- plugin/core/views.py
The scopes are taken from http://www.sublimetext.com/docs/3/scope_naming.html
It wasn't clear to me which scopes belong to these symbol kinds:
- Array
- Object
- Key
- Enum Member (what is this?)
- Event
> Put a little more effort in the symbol scope names

- plugin/core/types.py
- plugin/session_buffer.py
> Fix diagnostics getting out of sync when having diagnostics_delay_ms set

- plugin/completion.py
- plugin/core/views.py
- plugin/documents.py
- plugin/hover.py
- popups.css
Make links look like links. They look like text and it's not obvious
that they can be clicked.
> Make popup links more recognizable

- plugin/completion.py
- plugin/core/registry.py
- plugin/execute_command.py
- plugin/formatting.py
- plugin/goto.py
- plugin/hover.py
- plugin/references.py
- plugin/rename.py
- plugin/selection_range.py
- plugin/symbols.py
Done with pyls' now correctly working textDocument/rename, pretty nice.
All tests pass and tox doesn't complain, so I'm assuming everything went well.
> Rename LspTextCommand.session -> LspTextCommand.best_session

- plugin/core/registry.py
Will be useful for e.g. LSP-metals and LSP-julia so that their commands are hidden in the command palette when there's no session with that name attached to the view.
> API: Get session by name

- popups.css
According to https://www.sublimetext.com/docs/3/minihtml.html there is no
variable called "whitish".
> Rename: var(--whitish) -> var(--foreground)

- LSP.sublime-settings
- docs/index.md
And point people to LSP-intelephense instead.
I also removed this "Felix Becker language server" because it's dead.
> Remove intelephense from the default configs

- LSP.sublime-settings
- docs/index.md
And point people to LSP-typescript and LSP-eslint instead.
> Remove all the ts/js stuff from the default configs

- plugin/core/types.py
> Fix: show_view_status wasn't working properly

- plugin/core/transports.py
> Don't close the transport and server on it writing empty line to stderr

- plugin/core/transports.py
> Revert "Don't close the transport and server on it writing empty line to stderr"

- plugin/core/transports.py
> Fix server being shut down on it writing an empty line to stderr

- plugin/core/transports.py
> Fix freeze when force-closing a running server

- plugin/tooling.py
- Sort keys by name
- Try to not mess up original description line-wrapping too much
- Pretty-print default dictionary values
- Don't convert default values to ascii
> Improve script for parsing VSCode's configuration

- docs/index.md
add few comments on java jdtls setting sample. Clarify the fields that need to be changed based on the user env. Try to make it beginner-friendly
> add few comments on java jstls setting sample

- plugin/code_actions.py
- plugin/core/promise.py
Make use of Promises so that task only progresses once server commands
have completed. This doesn't guarantee that server has applied all the changes
since the server command can make server trigger workspace edits but extra
set_timeout_async after promises resolve helps with that.
> Fix save task leaving document in dirty state sometimes

- plugin/core/views.py
- plugin/symbols.py
- stubs/sublime.pyi
A server returning DocumentSymbol[]:
A server returning SymbolInformation[]:
> Use sublime.QuickPanelItem for textDocument/documentSymbol

- plugin/core/sessions.py
Enables LSP-json to provide documentation in markdown format
> Announce support for markdown in completion documentation

- LSP.sublime-settings
- Use "languages" for all default clients
- Format the whole file with vscode-json
- Merge "ocaml" and "reason" configs into one
(Don't forget to mention this in the release notes)
- Remove "golsp" configuration, everyone uses "gopls"
(Don't forget to mention this in the release notes)
> Clean up LSP.sublime-settings

- docs/index.md
- sublime-package.json
Also updated project-specific settings documentation.
> Extend sublime-project schema

- dependencies.json
- plugin/core/types.py
- stubs/wcmatch/glob.pyi
- tests/test_server_requests.py
- tests/test_types.py
This finally makes OmniSharp work 100% correctly.
Fixes #1216
> Implement pattern matching for DocumentFilter

- plugin/core/views.py
- plugin/core/windows.py
- plugin/hover.py
Also fix http:// and https:// links not working for some reason
> Fix related diagnostic links not working

- plugin/core/sessions.py
- plugin/core/windows.py
> Notify user about failed initialize

- plugin/completion.py
> Fix completion info not shown when session doesn't support resolveProvider

- plugin/core/sessions.py
- plugin/core/windows.py
- plugin/core/workspace.py
> Attach sessions to views outside the workspaces

- plugin/core/sessions.py
- plugin/core/views.py
settings.get() returns None in some cases.
Also a minor style change in unrelated code. Sorry about that :)
> Fix some formatting tests

- plugin/core/windows.py
- plugin/documents.py
- plugin/session_view.py
> Update code actions on diagnostics change

- language-ids.sublime-settings
> Account for source.*.react base scopes

- plugin/core/sessions.py
This seems safe to do. There's no need to put more code under the mutex.
> Tighter locking

- plugin/core/edit.py
- plugin/core/main.py
- plugin/core/promise.py
- plugin/core/sessions.py
- plugin/core/windows.py
- tests/test_server_requests.py
The plan is to refactor some code in code_actions.py to also make use of this
technique.
> Make the workspace/applyEdit handler truly async

- plugin/code_actions.py
- plugin/core/sessions.py
- plugin/hover.py
- tests/setup.py
- tests/test_code_actions.py
This method returns a promise that will be resolved once the code action
is done executing.
> Add a "run_code_action" method to Session

- boot.py
- plugin/edit.py
- plugin/rename.py
Last piece of the puzzle. Also remove unused code.
> Apply apply_workspace_edit in textDocument/rename

- plugin/core/types.py
- tests/test_session.py
See https://github.com/microsoft/language-server-protocol/issues/288
> Fix some issues with textDocument/didSave and old-style text sync

- sheets.css
I want to use this in LSP-SonarLint.
> Use the system font for sheet css

- plugin/__init__.py
- plugin/core/promise.py
- plugin/core/sessions.py
See https://github.com/sublimelsp/LSP-elixir/pull/9#discussion_r499389741
> Expose more stuff in api

- plugin/documents.py
- plugin/session_buffer.py
- plugin/session_view.py
Resolves #1365 
I cannot repro the bug with these changes.
> Record the change_count from the UI thread, and then dispatch to the worker thread

- plugin/session_view.py
> Show diagnostics with same begin and end range in the view

- plugin/code_actions.py
- plugin/core/sessions.py
- plugin/documents.py
- plugin/formatting.py
- plugin/hover.py
- plugin/rename.py
- plugin/selection_range.py
- stubs/sublime.pyi
- tests/setup.py
- tests/test_code_actions.py
- tests/test_single_document.py
- code actions
- formatting
- rename
- expand selection
I had to change quite a bit in the tests to make this work.
> Ensure more requests are ran from the async thread

- boot.py
- plugin/core/registry.py
- plugin/core/views.py
- plugin/documents.py
- plugin/formatting.py
- plugin/goto.py
- plugin/hover.py
- plugin/references.py
- plugin/rename.py
- plugin/selection_range.py
For now this seems problematic because it doesn't work for the first view that
you open when starting Sublime Text.
> Call the action commands directly, instead of going through LspRunCommandFromPoint

- plugin/rename.py
> Make the right placeholder even for servers with prepare rename support

- README.md
- plugin/core/sessions.py
> Advertise window.showMessage.messageActionItem.additionalPropertiesSupport

- README.md
- plugin/__init__.py
- plugin/core/handlers.py
- plugin/core/message_request_handler.py
- plugin/core/sessions.py
- plugin/core/views.py
I want to use those in lsp_utils
> Backport some stuff to LSP3

- plugin/core/sessions.py
> Add ability to set status for all views attached to the session

- Main.sublime-menu
This helps discovery of capabilities for inexperienced users. Let the discussions begin :)
> Put the menu items from the Context menu in the top Menu bar as well

- plugin/hover.py
clangd has for instance interesting things to say about your custom `operator+` binary operators.
> Let the server decide what is a valid token for hover

- boot.py
- plugin/core/edit.py
- plugin/core/open.py
- plugin/core/promise.py
- plugin/core/sessions.py
Implements https://github.com/microsoft/language-server-protocol/commit/ec377055d48d1bc79bbee6ad89c23ec428059f8f
> Implement window/showDocument server request

- plugin/documents.py
- stubs/sublime.pyi
Idea from @Ultra-Instinct-05
See: https://github.com/sublimehq/sublime_text/issues/3748
> Use the Sheet to check if a view is transient

- plugin/core/types.py
- plugin/core/url.py
- tests/test_url.py
Looks like this creates an import loop for lsp_utils somehow.
Reverts #1478
> Revert "Add an optional ClientConfig argument to filename_to_uri and uri_to_filename"

- plugin/core/registry.py
> Don't ignore session_name in LspTextCommand if capability is defined

- plugin/core/sessions.py
- tests/test_code_actions.py
not codeAction.resolveSupport.
> Fix: server capability is codeAction.resolveProvider

- docs/src/features.md
- plugin/execute_command.py
> Add support for $document_id in settings

- plugin/documents.py
This may or may not fix #1470. At least partially.
> on_{reload,revert}_async is also invoked for the ViewEventListener

- plugin/completion.py
- plugin/documents.py
I feel this is cleaner and isolated better.
Done this as part of looking into #1421 but that one might be too tricky to do with the current API limitations so not sure if it will come.
> Minor refactor of completions resolving

- plugin/core/views.py
> Fix related diagnostics being smushed together

- LSP.sublime-settings
- plugin/core/types.py
- plugin/session_buffer.py
- sublime-package.json
> Rename auto_show_diagnostics_panel_level to show_diagnostics_panel_on_save

- docs/src/language_servers.md
- OmniSharp clarifications
- rust analyzer clarifications
- wording
> Miscellaneous doc improvements

- LSP.sublime-settings
- docs/src/features.md
- plugin/code_actions.py
- sublime-package.json
> Extend disabled_capabilities with more options

- plugin/documents.py
looking up via the buffer capabilities falls back to the "global"
session capabilities if there's no such buffer capability.
This fixes an issue where a server can register a signatureHelpProvider
via client/registerCapability. Then those triggers live in the buffer.
> Look up the sig help triggers via the buffer capabilities

- docs/index.md
Ghcide is no longer maintained and the repo is archived.
For a beginner in haskell like me, it was a real struggle to have a clean haskell environment to work with due to old and misleading documentation on all the web.
I don't want the next guy to try haskell to suffer (or at least less than I did).
Also, thanks a lot for this magical plugin for sublime text !
Really good job, keep going this way !
> updated haskell doc

- popups.css
> Use --mdpopups-font-mono in popups.css

- plugin/core/registry.py
- plugin/symbols.py
> Fix: some menu items are broken

- plugin/code_actions.py
> Display an error message when a code action returns an error

- plugin/core/sessions.py
I've also added some comments and links.
> Advertise our markdown parser

- README.md
Also remove links to specific languages as that list can easily get out
of sync with documentation.
> Link to the new documentation in the readme

- plugin/core/open.py
- plugin/core/sessions.py
Needed for opening arbitrary URIs
> Minor improvements to opening files

- README.md
- docs/mkdocs.yml
- docs/src/guides/customisation_of_the_popups.md
> Move customization of popups to docs

- plugin/core/sessions.py
Was going to add it to the previous PR after rebase but didn't make it. :)
> Call on_session_end_async on crash also

- plugin/tooling.py
- allow to use it for disabled/crashed servers also since it's most
common to troubleshoot right after a crash
- make "shell command" show the server command with variables resolved
so that it can actually be used to test directly in the terminal
- in case of troubleshooting plugin-based servers, call their
"needs_update_or_installation" implementation as it's often necessary
to resolve the real command before being able to run it
> Make server troubleshooting more useful

- plugin/core/configurations.py
- plugin/core/windows.py
- plugin/core/workspace.py
- tests/test_configurations.py
- tests/test_server_panel_circular.py
- tests/test_views.py
> Disable crashed servers in-memory instead of in project data

- plugin/completion.py
- plugin/core/edit.py
- plugin/core/protocol.py
- plugin/edit.py
- plugin/formatting.py
- plugin/rename.py
This PR tries to improve the completion item type.
> improve completion item typings

- docs/src/language_servers.md
- Remove ST3 example configs.
- Redirect to install instructions of various new ST4 packages.
> Update for ST4

- LSP.sublime-settings
- plugin/documents.py
- sublime-package.json
> Allow no automatic code actions

- plugin/code_actions.py
- plugin/documents.py
This reverts commit c7ffb666afc1970ec12703485bcfb4c6e255a9dd.
The title may be very long. Let's revert this for now and think of a possible solution for this. @husanjun, I would like to make a new release but this feature isn't 100% done yet. Please don't be discouraged and make a new pull request.
> Revert "Improve code action annotation UX (#1677)"

- docs/src/customization.md
> Mention font face in customization docs

- LSP.sublime-settings
- pyls
- dart
- elixir-ls
- flow
- jdtls
- sourcekit-lsp
> Remove some default configs

- plugin/core/views.py
- plugin/session_view.py
Lots of users were confused about the vertical lines.
> Draw empty regions as a small horizontal line

- plugin/core/sessions.py
> Clear all status messages when session ends

- plugin/code_actions.py
- plugin/core/registry.py
> Remove sessions_for_view

- LSP.sublime-settings
> Remove some defaults

- plugin/core/sessions.py
> Fixup window/showDocument request handler

- LSP.sublime-settings
- sublime-package.json
Also updated LSP.sublime-settings
> Update sublime-package.json for 'schemes'

- plugin/core/sessions.py
- plugin/core/url.py
- tests/test_session.py
~~Fixes #1770~~
Fixes diagnostics on Windows.
> Account for FS case-insensitivity

- .github/workflows/main.yml
- tests/test_configs.py
Three time's the charm :) or is this the fourth attempt now?
> Try my luck with a Windows CI

- plugin/core/url.py
- tests/test_url.py
> Fix res URIs for Windows

- plugin/core/url.py
- tests/test_url.py
> Fix UNC paths on Windows

- docs/src/language_servers.md
This PR will add documentation for Phpactor language server
> Add documentation for Phpactor

- plugin/completion.py
- plugin/core/protocol.py
- stubs/sublime.pyi
- tests/test_completion.py
See: https://github.com/Azure/bicep/issues/4055
> Strip carriage returns in completion insertions as well

- plugin/core/protocol.py
- plugin/core/sessions.py
- plugin/core/views.py
- stubs/sublime.pyi
- tests/test_completion.py
There isn't actually any language server that I know of that implements labelDetails. So I've written extensive tests. The most likely candidates that will are jdtls and omnisharp.
close #1570
> Implement labelDetailsSupport

- docs/src/guides/client_configuration.md
- Instead of a typescript example I used phpactor as example. This should minimize confusion as to whether you're supposed to write this yourself or whether a helper package "provides"/"registers" a config.
- Update client config keys
- Explain transport modes better
> Update client configuration docs

- plugin/core/sessions.py
- plugin/core/views.py
- plugin/formatting.py
- tests/test_views.py
Not entirely convinced on naming of things, of course.
> Add AbstractPlugin.on_before_formatting API for tweaking formatting options

- plugin/core/panels.py
> Revert "Always clear undo stack after a mutation on any panel"

- docs/src/language_servers.md
Wait till this [this PR](https://github.com/sublimelsp/repository/pull/53 ) is merged.
> Document LSP-volar

- docs/src/language_servers.md
These plugins are available on PC but were not documented.
> Docs add plugins

- docs/src/language_servers.md
> Document LSP-rust-analyzer

- Default.sublime-keymap
I got confused because i didn't know about the context part
I think this comment could be helpful to guide new users
> Add a comment to guide new users how to change the keybind of a command

- plugin/core/windows.py
When more than one server send diagnostics for the same file, that file appears once for every server in the diagnostics panel. This fixes it.
> Merge diagnostics from multiple sessions for same file in panel.

- .github/workflows/main.yml
- plugin/tooling.py
- tox.ini
Follow to real flow more closely for better error reporting.
> Call can_start() and on_pre_start() in the troubleshooting flow

- plugin/__init__.py
- plugin/completion.py
- plugin/core/sessions.py
- plugin/core/signature_help.py
- plugin/core/views.py
- plugin/documents.py
- plugin/hover.py
- tests/test_signature_help.py
Real implementation for the POC in #1908
> Allow plugins to specify a custom syntax for code blocks in markdown

- plugin/semantic_highlighting.py
- stubs/sublime.pyi
> Fix LspShowScopeNameCommand for the new ContextStackFrame type

- language-ids.sublime-settings
See https://github.com/LDAP/LSP-ltex-ls/issues/10
> Fix language id for mangecoeur/AcademicMarkdown

- plugin/hover.py
> Fix bug for symbol action links in hover popup

- plugin/locationpicker.py
> Restore selections after location picker panel

- plugin/core/protocol.py
- plugin/core/views.py
Add new type from https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#semanticTokenTypes
> Update semantic token types

- docs/src/language_servers.md
Fixes https://github.com/sublimelsp/LSP/pull/2001#issuecomment-1193394900
> Add GDScript syntax highlighting instructions

- docs/src/language_servers.md
the project works with native rbs syntax https://github.com/soutaro/steep
> Add docs for ruby steep language server

- boot.py
- plugin/core/windows.py
> Fix types in LspOpenLocationCommand

- Context LSP Log Panel.sublime-menu
- Context.sublime-menu
- LSP.sublime-settings
- boot.py
- plugin/core/panels.py
- plugin/core/windows.py
- plugin/panels.py
- sublime-package.json
- tests/test_server_panel_circular.py
A small PR that adds the ability to clear the output panel.
> Custom context menu in log panel and "Clear log panel" item

- sublime-package.json
I never know what to put in the `disabled_capabilities`,
always have to look up the spec.
With this PR we will get JSON schema validation for `disabled_capabilities`.
> Add json suggestions for disabled capabilities

- language-ids.sublime-settings
relates to https://github.com/sublimelsp/LSP-tailwindcss/issues/47
> Add jinja to language ids

- plugin/session_view.py
- tests/test_server_notifications.py
> Fix diagnostics underline color priority

- plugin/core/views.py
- plugin/goto.py
- plugin/locationpicker.py
- plugin/references.py
Don't get confused from the title ;-)
This is just a pull request with small improvements to the branch of the other pull request.
> Placeholder text

- plugin/core/views.py
- plugin/goto.py
- plugin/locationpicker.py
- plugin/references.py
> Nicer presentation for "find references/definition" quick panel

- plugin/code_lens.py
- plugin/core/views.py
- plugin/documents.py
- plugin/hover.py
- tests/test_completion.py
Fixes https://github.com/sublimelsp/LSP-rust-analyzer/issues/86
> Ensure commands triggered from minihtml run on correct view

- plugin/core/open.py
Workaround for core issue https://github.com/sublimehq/sublime_text/issues/2411
Fixes https://github.com/sublimelsp/LSP/issues/1979
> workaround for View Listeners not being attached for new transient view

- plugin/code_actions.py
This happend when the main menu is opened and no view or input field has currently focus (for example when you focused the side bar or an output panel). Because there exists no instance of a corresponding active TextCommand in that case, and therefore also no `is_visible` method to check for the visibility state - see https://github.com/sublimehq/sublime_text/issues/5857.
The solution is to use a WindowCommand instead, because there is always an instance of that for the active window.
> Fix hidden code action menu entries sometimes being visible

- plugin/core/protocol.py
This PR should address this https://github.com/sublimelsp/LSP/pull/2194#discussion_r1103680104
> Update generated protocol types

- language-ids.sublime-settings
fixes https://github.com/sublimelsp/LSP-tailwindcss/issues/51
> Add language ID mapping for TailwindCSS syntax

- plugin/session_buffer.py
> Don't run non-essential requests during save

- LSP.sublime-settings
- plugin/core/types.py
- sublime-package.json
> adding outline as an option to drawing document_highlight

- docs/src/language_servers.md
And re-organize a bit TS/JS section
> docs: add LSP-rome and LSP-ruff

- dependencies.json
> remove unused dependencies

- plugin/core/open.py
> Fix find_open_file incompatibility with older ST versions

- plugin/core/input_handlers.py
- plugin/core/sessions.py
I'd like to document the considerations from https://github.com/sublimelsp/LSP/pull/2410#issuecomment-2010976733 to make users of this API method aware of potential side effects.
> Small docstring supplement

- plugin/core/sessions.py
> Fix StrEnum values in initialize request

- plugin/__init__.py
want to use it for vue package
> feat: make DebouncerNonThreadSafe public

- plugin/core/windows.py
> Fix possible exception on settings change

- docs/src/features.md
- docs/src/index.md
Added some more paragraphs with explanations in the landing page, which might be useful to new users.
> Add some more paragraphs in docs

- docs/src/language_servers.md
Add Herb Language Server docs.
https://github.com/marcoroth/herb
> docs: add Herb to language_servers.md
