sublimelsp/LSP

LSP.sublime-settings

I've commented out the mscpp server because its path is hardcoded. I'm also unsure how the plugin responds to multiple servers being able to handle the same language. How would that work?

Add clangd to default settings

---

Syntaxes/Diagnostics.sublime-syntax

Somewhat more structured syntax for diagnostics:
You could consider highlighting the Exxx and Dxxx numbers at this point, but that seems to be too python-specific. I'm wondering if a per-server syntax would be beneficial.

Improve highlighting for diagnostics

---

LSP.sublime-settings
main.py

We should consistently use `markup.error.lsp` to scope errors and `markup.warning.lsp` later for warnings as they are considered (new) RFC. `sublimelinter.mark.error` is kept for backward compatibility with older color schemes.
Region names should always contain or better start with the package name as they must be unique.

Scope naming

---

main.py

Nice package! :)
I tried to integrate flow (see [this](https://github.com/flowtype/flow-language-server) LSP library) with this ST package and found some issues with the hover support.
One issue was that the code didn't comply with the specification for the hover payload. The contents attribute can look like this `contents: MarkedString | MarkedString[];` (see [here](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_hover)), however it was implemented to only accept `contents: string | MarkedString[];`.
Another issue was that flow sometimes returns null instead of a MarkedString (array). This is flow's fault, but checking for that doesn't do any harm, I think.
The actual flow integration can be done by installing …

Improve compatibility with flow

---

Syntaxes/Diagnostics.sublime-syntax
main.py

I found some further settings to improve the look and feel of the output panel yesterday, which I forgot to push to the recently merged branch. So here it is as another PR
- formatting `line:column` to ensure the colons being aligned
- (hopefully) provide enough space for each column so the tab_size can be reduced to 4 which makes the output look more compact
- added a bunch of settings to ensure to make the output panel look nicer for everyone removing unnecessary stuff
- removed the `base_dir` setting as it not used anywhere and would possibly not make sense to as it is created once but might change during lifetime of the panel, if the open project is changed on the fly.

Improve visual settings of output panels

---

Syntaxes/References.sublime-syntax
main.py

The references output is quite static so multiple pushes may make things too complicated here.
The scope names are applied the same way we did for diagnostics.
The tab between file path and location is changed into a normal whitespace as tab does not align correctly if the file paths' length in the list differs too much. It looks better with fixed distance.
We may or may not scope the preamble more detailed, but I find a more minimalistic scoping better at the moment.

Apply scopes from diagnostics t references output panel highlighting

---

LSP.sublime-settings
main.py

Adds flags as requested in issue #15:
log_debug: (off) logs outgoing requests, responses, etc.
log_server: (on) log entries received from the server through `window/logMessage`
log_stderr: (off) some servers write logging output here.
Removes UTF-8 decoding from stderr stream as client is likely not obliged to send utf-8 and can cause errors like issue #12

Turn most default logging off, add settings to re-enable

---

main.py

This commit basically contains some results of my investigation on python-language-server issues, yesterday. I've created a module uri.py, which handles the job. The client should use the same standard functions to translate between url and filename to avoid OS specific code.
As the main.py is quite large, I would suggest to just import the urllib and use the functions with full path. This is a bit more expressive and it is easier to see where the functions come from.
I use the opportunity to group and sort the imports as suggested by several official sources
First sorting level (groups):
1. standard library imports
2. sublime text default imports
3. dependencies packages imports
4. private imports (not yet used)
Second sorting level:
1. import
2. from ... import
Third sorting level:
Sort …

Use urllib to translate between url and filename

---

main.py

Especially while developing, an enormous amount of settings reloading can be witnessed after saving a settings file.
This change should prevent registering the same settings update handler multiple time.

Only update settings when changed, don't re-initialize settings handling

---

LSP.sublime-settings
main.py

As requested in issue #19, adds a third option for displaying diagnostics besides hovers and phantoms.

Show diagnostics in status bar

---

main.py

For #18, where already-open views do not trigger the language server to startup (only toggling events or opening other views works).
In limited testing on OS-X, the non-active window had an activated event fired on its view once I changed to it, so only the active_window's active_view needed a manual startup.

Initialize the active window's active view at startup

---

main.py

I noticed the print functions were somewhat convoluted so I simplified them.
Also, there was a lonely built-in print used for printing an exception on line 1347.

Simplify print functions

---

LSP.sublime-settings
Syntaxes/Diagnostics.sublime-syntax
main.py

Had a look into the regions and phantoms stuff a little bit with more attention to the regions right now. 
1. I'd suggest to disable phantoms by default at the moment as they make files with many issues unreadable at the moment.
2. Errors/Warnings/Infos are added with different scopes so they can have different colors. Scopes are synced with diagnostics syntax. Decided to use sublimelinter scopes in diagnostics panel for now. But we may discuss which solution is better. I am not sure.
For details, please see commit messages.

Add error/warning/info regions and disable phantoms by default.

---

main.py

This PR addresses issue #36 and intends to display tooltip even if language-server doesn't offer a description. A basic filter is used to statically exclude some scopes which a language server will most likely not have something to offer for.

Always show symbol information popup

---

LSP.sublime-settings
main.py

For issue #25, where all completion requests (even manual) were ignored unless the cursor followed a trigger character.
The following improvements were made:
* No more filtering on trigger chars (ctrl+space no longer ignored)
* Switch to ViewEventListener (easier to disable, less risk with shared state)
* Track completion states so we can discard and request new completions as the user keeps typing
To do:

Enable full completions

---

main.py

When `insertText` is not empty, it should be used irregardless of wether `insertTextFormat` is `PlainText` or `Snippet`. In fact since Sublime handles snippets transparently, we don't even have to care about `insertTextFormat`.

Fix bug in format_completion function

---

docs/index.md
main.py

Should provide functionality for:
* Passing `initializationOptions` to language servers
* Disable language servers / enable per-project (#69)
* Per-project configuration of `initializationOptions`
* Initial sending of per-project `settings` via `workspace/didChangeConfiguration`
To do:
Tested this using a stdio-supporting fork of vscode-eslint (https://github.com/tomv564/vscode-eslint/tree/add-stdio-support), which refused to start up without initializationOptions (needed `nodePath`) or an initial didChangeConfiguration (with empty settings)
The python language server will get configuration support in PR https://github.com/palantir/python-language-server/pull/118

Per-window/project configuration

---

LSP.sublime-settings
README.md
docs/index.md

I'm not sure why this doesn't activate for ocaml files (ocaml-language-server works for reason and both, so it shouldn't be that side's error), but for reason files this works.
Test:
```
git clone https://github.com/freebroccolo/ocaml-language-server.git
cd ocaml-language-server
npm install
npm install -g .
```
Then use this diff and open up a foo.re file and write
```reason
let a: int="hi";
```
And see the correct error at the bottom

Add Reason/OCaml lsp settings

---

main.py

Fixes #79.
This changes from using the common prefix (which could be a partial directory name) to using only the first folder in a project. Additionally, it fixes the `is_in_workspace` check to avoid the same problem.
This removes support for multiple folders (in a way; it will now only index one folder instead of the common parent of all folders), so probably warrants a major version bump.

Use one project path instead of common prefix

---

main.py

Apply sublime's variables and ~ on config.binary_args
To close #55

Expand variables and ~ in language server path configuration

---

main.py

Fixes #84.
Rather than appending to the panel once per line, this instead builds the entire string once, then replaces all the content at once. It also avoids calling `erase` at all. With this, there's now no flickering at all during redraws:
This also adds a `lsp_update_panel` text command; as far as I can see, there's no built-in command to do this, but happy to be wrong on that!

Update diagnostic panel atomically

---

LSP.sublime-settings
docs/index.md
main.py

Some language servers can provide rich completion items (including documentation and snippet formatting) but at a great cost. To defer this cost, we can resolve extra details for completion items only when necessary through `completionItem/resolve`.
This strategy can be seen in action in VS Code, where only the selected completion item displays documentation etc.
Sublime Text provides no API to detect which completion item is currently selected in the list.
To still enjoy snippet support, we need to detect the inserted completion item label, resolve the completion, and insert the snippet in its place.
This PR demonstrates it can be done in a performant manner.
>  An alternative solution is to resolve all received completions (only functions/methods?) if less than MAX_RESOLVE_COUNT async …

Resolve completions for snippets

---

main.py

If a server cannot start, there is no space between the message and the name of the server, resulting in, e.g., `Could not startjsts` instead of `Could not start jsts`

need a space before concatting "Could not start " + config.name

---

docs/index.md

- Retested it with the [github:DisposaBoy/GoSublime](https://github.com/DisposaBoy/GoSublime) package installed and it works.

Remove redundant text from doc.

---

main.py

Fix for issue #101, where completions updates were never applied the first time.

Hide completion list before updating

---

main.py

This is just a very simple copy-paste from Default's exec.py to sync the styling of LSP phantoms with build errors.
before 
after
The docs suggest giving the phantoms a package specific `id` to help targeting style customisation. However, I think the idea here is to match the built-in phantoms so it's good as is at least for now. It's a shame these styles aren't easily shared. It's also not guaranteed to get out of sync.. ¯\_(ツ)_/¯

Gives phantoms the same nubbin as build errors

---

main.py

Word completion and snippets cannot be shown if it is true.
Also, `auto_complete_commit_on_tab` should be set by the view settings.

show non api completions when only_show_lsp_completions is False

---

main.py

mdpopups' markdown engine squashes down all multiple spaces to one.
This PR prepares the content to preserve them all and make popup content look a bit better.

Enhancement: Keep whitespace displayed in popups

---

main.py

Some python docstrings contain multiple newlines at the end, which results in an empty line being displayed in the tooltip for such docstrings. To avoid this issue, `preserve_whitespace` now strips whitespace from the beginning and the end of the content to display in a popup.
For consistency the replacement of multiple spaces was modified, too. Without functional effect.

Strip leading and tailing whitespace from function documentations.

---

docs/index.md

Fixed autocomplete_triggers -> auto_complete_triggers and added the explanation about 'User or Syntax-specific settings' to each site, because the users are likely to skip directly to the language-specific explanation. (`auto_complete_triggers` won't work in the LSP settings, but if you skip the explanation, you are likely to think that's where you're supposed to copy it.)

Doc changes about autocomplete triggers.

---

main.py

You were right that it doesn't print the last error message. Basically calling `subprocess.poll()` to check if the process has terminated, and if it isn't, read from stdout/stderr is a race condition. It's better to terminate the loop after `EOF` has reached directly from the pipes.
Additionally, made it so that it prints the error message even when debug logging isn't on, which is consistent with other fatal error conditions.
This fixes https://github.com/tomv564/LSP/issues/116

Fixed a bug where the last message from the server doesn't get read when the server terminates.

---

main.py

If there is no project folder, it considers the directory containing the file as a fallback case. Whether this is a grokkable by the language servers is their business, but at least it allows them to be able to handle the case, if they so wish.
I tested that by default, RLS can do code completion even if the project folder isn't set right.

Added a fallback in the case where there is no project folder.

---

main.py

Actually, I don't understand why we should inhibit word completions and `.sublime-completion` completions when CompletionState is idle. Firstly, some servers (e.g. julia server) are really slow to respond, if we inhibit word completions and the server doesn't respond fast enough or encounters an error while handling a completion request, it will essentially stop the entire auto-completion functionality. Secondly, if the reason was to prevent flickers, then I argue that `.sublime-snippet` should be also inhibited. Otherwise, there would still be flickers. (AFAIK, there is no way to stop snippet completions).

show other completions even when CompletionState is idle

---

main.py

Fixes Issue #132
With commit 8beb41e the `self.process.poll()` function was removed, which checks, whether the subprocess (language-server) was terminated.
Therefore the `read_stdout()` and `read_stderr()` methonds of Client never exit and run without any sleep time after the process exits.
This commit reintroduces `self.process.poll()` but makes sure the already sent stdout/stderr content is still read and processed by LSP.
Furthermore the output checks of `stderr.readline()` / `stdout.readline()` are simplified as using `len()` is not the best solution here. It will fail if the passed string is None.

Fix endless loop after language-server termination.

---

main.py

Prior to this commit an exception is raised if the function signature returned by a language server does neither contain a `parameters` nor `params` field.
The error message was:
```
LSP: active signature {'label': 'active_window()', 'documentation': ''}
LSP: params None
LSP: error handling response 10
LSP: Error handling server content: 'NoneType' object is not iterable
```
This commit fixes this issue by a fallback to an empty dictionary.

Fix exception when handling empty signature parameters.

---

LSP.sublime-settings
main.py

With this PR a user can add a dictionary to each client-configuration.
"environment": {
"PATH": "$PATH;${project_path};/opt/libs"
"PYTHONPATH": [
"${sublime_libs}",   feature removed by request
"${packages}",
"${project_path}"
]
}
This dictionary lists environment variables to add or set to the global
environment variables `os.environ` provided by Sublime Text.
The language server will see the merged set of environment variables.
Notes about the dictionary:
1. Each variable can be either a simple string or a list of strings.
2. If a variable is a list, it is merged to a string separated by ;
This enables easier setup of larger sets of values such as paths.
3. Each variable replaces the global environment variable.
4. Shell variables such as $PATH are expanded.
5. Point 3. and 4. allow …

Add support for per language-server environment variables

---

main.py

Fixes following traceback:
File "C:\Apps\Sublime\Data\Packages\LSP\main.py", line 1965, in <lambda>
on_navigate=lambda href: self.on_diagnostics_navigate(self, href, point, diagnostics))
TypeError: on_diagnostics_navigate() takes 4 positional arguments but 5 were given

Fix crash when clicking diagnostics hover "Code Action" link

---

LSP.sublime-settings

PackageDev uses the comments above each setting to display a tooltip, if the cursor is hovered over an existing setting.
This commit adds required comments to the LSP.sublime-settings file.
An empty "clients" object was added to prevent PackageDev's linter from highlighting the key as unknown.
The template for user defined clients is moved to the "clients" setting and a warning was added to the comment of "default_clients" to prevent a user from accidentally manipulating the wrong setting to do overrides.
The template was formatted to hopefully display well in the tooltip for most users.

Add support for PackageDev settings tooltips

---

main.py

fixes #158
The format of the "trigger" of the completions returned by a plugin seems to influence the way Sublime Text merges them with word completions.
The extra spaces added to the "trigger" value, which make sure the hints are displayed with enough distance to the label, cause Sublime Text not to correctly merge in word completions.
To solve the issue, the `\t` is moved to the very left to prevent a space to be appended to the label in the returned value.

Fix word completions not displayed in completions panel

---

Commands/Default.sublime-commands
Menus/Context.sublime-menu
docs/index.md
main.py

There might be race bugs when using this with multiple selections.
When this is invoked with multiple selections, I try to send requests from "highest range" to "lowest range", so that local edits don't affect other local edits.
I'm not too worried about this at the moment.

Implement textDocument/rangeFormatting

---

plugin/signature_help.py

This commit fixes an issue with LSP throwing an exception after opening another project within the self window using project switcher or ProjectManager plugin.
The traceback:
```
LSP: pyls not available for view None in window 3
File "C:\Apps\Sublime\sublime_plugin.py", line 417, in run_async_view_listener_callback
vel.__class__.__dict__[name](vel)
File "C:\Apps\Sublime\Data\Packages\LSP\plugin\signature_help.py", line 60, in on_modified_async
if self.signature_help_triggers:
AttributeError: 'SignatureHelpListener' object has no attribute 'signature_help_triggers'
```

Fix exception with signature help after project change

---

plugin/configuration.py
plugin/core/popups.py
plugin/hover.py
plugin/signature_help.py

Replaces #168 after the codebase was split. Please refer to that PR for the epic ride towards the new good looking popups with code highlighting. It was pretty much impossible to rebase or merge this so I decided to re-implement.
Fixes #105 and fixes #82, pretty sure it also fixes #159
Please also note we should [update our dependencies](https://github.com/tomv564/LSP/pull/168#issuecomment-336130644)
Before: 
After:

New whitespace / layout / styling PR

---

plugin/core/main.py

According to the API reference
https://www.sublimetext.com/docs/3/api_reference.html
the `message_dialog()` function is directly on the `sublime` module, not on the `Window` class.

Fix wrong usage of message_dialog().

---

plugin/core/documents.py

was trying to lookup a file in the window ids map. pretty certain should be using this function instead
map is keyed on int as per https://github.com/dten/LSP/blob/0f8b8b0feb40878330953ea66a3b579caa7b1bcd/plugin/core/documents.py#L53

fix looking up document state in notify_did_save

---

LSP.sublime-settings

I thought we fixed this... Anyway, this should be set to `objc++` to get mdpopups highlighting.

Set languageId to objc++ for the clangd server

---

plugin/completion.py

This sorts the completions as defined by the language server (if there's a sortText property).
At least python-language-server and clangd provide this key.

Use sortText if it's present in completion items

---

plugin/core/edit.py
plugin/rename.py

For #190, should display how many documents (for workspace edits) or how many regions (for document edits) in the status bar were edited.

Show result (once) in status bar when workpace or document edits are applied

---

plugin/completion.py

inserted spaces get undone as mentioned at https://github.com/tomv564/LSP/pull/180#issuecomment-338468746
this PR checks actively if the last text command is
insert_best_completion

fix: inserted space get undone

---

LSP.sublime-settings

only works on unix/mac though.
PC users may use (untested)
```
"command": ["julia", "--startup-file=no", "--history-file=no", "-e", "using LanguageServer; server = LanguageServer.LanguageServerInstance(STDIN, STDOUT, false); run(server);"]
```

add julia language server

---

plugin/core/popups.py
plugin/hover.py
stubs/mdpopups.pyi

Currently the diagnostic hover hides the hover information from the language server.
This is unhelpful when you are trying to hover the signature of a type, but instead are shown the exact error you are trying to fix.
This PR combines the diagnostic and hover content:

Combined hover content

---

plugin/core/rpc.py

A few methods in the Language Server Protocol can return `null`.
The Python library maps the JSON value `null` to `None`. So far,
rpc.py was unable to distinguish between `{result: null}` and a missing
result field. It reported both of them as protocol violation.
Due to this, it was not possible to restart the python-language-server
cleanly. Trying to execute `Restart Servers` always resulted in an
`incomplete response payload` error since the `shutdown` request always
returns `null`.
This commit adapts rpc.py so that it accepts `{result: null}`. In case
both `result` and a non-empty `error` are received, we treat that as an
error response.
Also, a response of the form of `{result: null, error: {code: 123,
message: "error"}}` is treated as invalid. According to the JSON-RPC spec,
it is …

Handle 'null' result in JSON RPC

---

plugin/core/rpc.py

So far, the presence of a capability's key in ServerCapabilities was treated as if the server supported that capability.
E.g., `{"codeActionProvider": false}` was interpreted as if the server supported code actions.
While not clearly stated in the LSP spec, the intent of such a `false` capability is rather to explicitly state that the server does *not* support the capability.
I was running into this while experimenting with my own dummy language server implementation

Treat a capability announced as `False` as unsupported

---

LSP.sublime-settings
boot.py
plugin/core/protocol.py
plugin/core/settings.py
plugin/highlights.py

- Using a queue/purge model like in notifying document changes.
- Using "text" scope for unknown and text kinds, "markup" for read/write.
- Add the kind of document highlights to protocol.py
- Allow users to change the presentation style:
* Users can choose underline, stippled or squiggly.
* Users can change the scope per kind.
- Timeout of 500ms after no selection changes before sending out a document
highlight request.
clangd recently added textdocument/documentHighlight 🎉

Implement textdocument/documentHighlight

---

LSP.sublime-settings
docs/index.md

I tested it locally, the enable server command that then sets up configuration for the user is quite nice.
`npm i -g polymer-editor-service` is the prerequisite command if you'd like to test it out.
This HTML should produce an error diagnostic on the url:
```html
<link rel="import" href="./does-not-exist.html">
```

Add polymer-ide to the default_clients list in settings.

---

plugin/completion.py

Pre https://github.com/tomv564/LSP/issues/211#issuecomment-345973254
> We could also check if the last character is whitespace and set the completion state to CANCELLING in on_modified?
Cancel current completion If you receive a space while waiting for the completion reply.
fix #211

cancel current completion if the previous input is an space

---

LSP.sublime-settings
docs/index.md
plugin/core/settings.py
plugin/signature_help.py

- Can switch between "sublime" style and "vscode" style in the LSP preferences.
- Tried to keep both style as similar as possible. I think only the top label is now different.
Related: https://github.com/tomv564/LSP/issues/231

Add "vscode" style signature help popup

---

LSP.sublime-settings

Rename R settings key to prevent it overwriting Rust settings

---

plugin/core/clients.py
plugin/core/configurations.py
plugin/core/documents.py
plugin/core/main.py
plugin/core/rpc.py
plugin/core/settings.py

For PHP on Windows (#151 and #240) and easier debugging of language servers. 
To do:
Because TCP ports cannot be shared, some work was done tightening state and removing overlap during client restarts:
- `starting_configs_by_window` replaced by a lookup storing ClientState.STARTING/READY/STOPPING per configuration
- Clients remain in STOPPING state until exit is posted, at which point `restarting_window_ids` is checked to see if new clients should be started for the window.
Things this won't solve:
- Port selection (you'll need to solve this with per-project configuration)

TCP support

---

plugin/core/main.py

According to the LSP specifications, the processId field in the initialization params needs to be the parent process id.  This is so the language server can shut itself down when the parent process terminates.  This will fix bugs where when you close Sublime Text, the language server would be kept running.

Send parent process id in initialization params.

---

LSP.sublime-settings
docs/index.md
plugin/highlights.py

- Add "" option for document_highlight_style
- Add document_highlight_* settings to index.md docs
closes https://github.com/tomv564/LSP/issues/286

Allow "" for document_highlight_style in order to disable it entirely

---

LSP.sublime-settings
plugin/configuration.py
plugin/core/configurations.py
plugin/core/handlers.py
plugin/core/main.py
plugin/core/settings.py

Aims to provide a richer API allowing packages external to LSP to:
Motivation is that we are starting to have conflicts in the default configs (so I'd like to remove them entirely). Also, other maintainers can do a much better job ensuring language servers are installed / up to date.
Classes that extend the abstract interface will automatically be instantiated by LSP:
```python
from LSP.plugin.core.handlers import LanguageHandler
from LSP.plugin.core.settings import ClientConfig
class LspYourServerPlugin(LanguageHandler):
@property
def name(self) -> str:
return YOUR_CONFIG_NAME
@property
def config(self) -> ClientConfig:
return YOUR_CLIENT_CONFIG
def on_start(self, window) -> bool:
def on_initialized(self, client) -> None:
```
Example plugin implementations at …

Language handler support

---

plugin/completion.py

Fix: lang servers may return mixed sortText and non-sortText completion items (e.g. intelephense for PHP)

---

plugin/hover.py

To fix an obvious bug of `local variable referenced before assignment`
```
File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1066, in run_
return self.run(edit, **args)
File "/Users/Randy/Dropbox/Sublime Text 3/Packages/LSP/plugin/hover.py", line 47, in run
self.show_hover(point, self.diagnostics_content(point_diagnostics))
File "/Users/Randy/Dropbox/Sublime Text 3/Packages/LSP/plugin/hover.py", line 102, in diagnostics_content
return "".join(formatted)
UnboundLocalError: local variable 'formatted' referenced before assignment
```

fix: local variable referenced before assignment

---

docs/index.md

[vue-syntax-highlight](https://github.com/vuejs/vue-syntax-highlight) has changed their syntax file to take advantage of the latest ST3 builds. This specifies which file to use against different build versions.

Improve Vue syntax file reference in docs

---

plugin/core/edit.py

The last PR introduced an invalid type annotation. Didn't notice it. This should finally fix the build. Sorry!

Remove invalid type annotation

---

LSP.sublime-settings
docs/index.md
plugin/core/settings.py
plugin/diagnostics.py

closes #186 
- changed the default value for `auto_show_diagnostics_panel` to false,
- before `auto_show_diagnostics_panel` was responsible for automatically opening and closing the diagnostics panel,
now it is responsible only for opening, as the panel will automatically close when there are no errors(no need to show an empty panel),
- updated the docs for the settings I changed and added.
- new setting for configuring the visibility of the count in the status bar `show_diagnostics_count_in_view_status`, defaults to true,
- added diagnostics count to the status bar.
Waiting for feedback, if you have something you would change, or reject, please say so.. :)

Add diagnostics count to statusbar

---

plugin/completion.py

Sublime Text does not support explicit replacement with completion at given range, instead it replaces current completion prefix with the completion text. Knowing the completion prefix boundaries at plugin
side, we can trim `textEdit` range and text given by language server to the boundaries of the prefix.
Fixes #294
E.g. for PowerShell grammar and PowerShellEditorServices LS:
$tru<Ctrl+Space> (prefix "tru") -> now "true" instead of "$true"
$env:U<Ctrl+Space> (prefix "U") -> now "USER" instead of "$env:USER"

Try to utilize LS completion textEdit if possible

---

plugin/core/configurations.py

This pull request makes it so `get_scope_client_config()` returns the most specific configuration that matches the currently selected scope.

Give priority to more specific scopes. Fixes #338

---

plugin/core/configurations.py

This is compatible with the current configurations, but also supports using partial words for syntaxes. 
Ex., to match any syntax with "JSON" in it:
```json
"syntaxes": ["json"]
```

Allow using partial words to match syntaxes. Fixes #340

---

plugin/completion.py
plugin/core/protocol.py

- Update completion item kinds
- More safely fetch the kind (if it doesn't exist, it reverts to None)
I haven't tested this, but this should fix #348. Ping @gobijan and @LaurentTreguier, could you give this a spin with the Ruby server?

Bugfix: format completion

---

plugin/diagnostics.py

Otherwise os.path.relpath may emit for example:
`ValueError: path is on mount 'D:', start on mount 'C:'`
This is just a tiny fix for Windows users. Problem occurs when you have your project on one drive, but you add a folder from different drive.

Prevent os.path.relpath exception for project and file on 2 drives

---

LSP.sublime-settings
plugin/core/clients.py
plugin/core/configurations.py
plugin/core/diagnostics.py
plugin/core/documents.py
plugin/core/edit.py
plugin/core/main.py
plugin/core/rpc.py
plugin/core/sessions.py
plugin/core/settings.py
plugin/core/test_session.py
plugin/core/test_windows.py
plugin/core/types.py
plugin/core/windows.py
plugin/core/workspace.py

This makes some of the core behaviour around startup, failure, restarting and language handler hooks tested.
Some ugly stuff introduced:
* Some hastily done typing (at times poorly named) resolves to using `Any` where eg. `ViewLike` meets `sublime.View`
* This is hopefully temporary
* modules like clients and configuration expose a shim over their global state
* The hope is to remove remaining global-dict-by-window-id state gradually.

Move session lifecycle into window, inject dependencies

---

plugin/hover.py

When using plugins for language servers, or language servers that natively return the source of a diagnostic, the source should be shown as part of the hover popup.
For example, Python's pycodestyle, flake8 and mypy all return the source for each diagnostic; without adding the source, it's difficult to guess where the errors are coming from, this is a suggestion for. This pull request adds the source, as in: "[mypy] some message" or "[pyflakes] E501: line too long".

Show diagnostic source as part of the message

---

plugin/core/rpc.py
plugin/core/test_rpc.py
plugin/core/transports.py

As suggested by @Kronuz in his fork, instead of any sublime thread blocking on writing stdio/socket, now a dedicated thread takes messages from a queue.
No longer seeing sublime hangs while triggering various messages during lsp-tsserver startup.
This should fix #287.

Dedicated server writing thread

---

docs/index.md

Some whitespace in `docs/index.md` was causing the docs to render like so:

Fix docs rendering issue

---

plugin/core/process.py

For most nodejs-based language servers, this will allow globally installed servers like "lsp-tsserver" to be found without having to add ".cmd" in the client config for Windows.

Append '.cmd' when needed for an executable on the path

---

docs/index.md

It took me a minute to realize I needed to add `"enabled": true` for the go language server to startup.

Add enabled flag to the go client configuration example

---

plugin/core/panels.py

Dont scroll to end when the diagnostics panel is open, but keep the clear selection, so that panel text is not selected when opened.
Closes  #446

Dont scroll to end when the diagnostics panel is open  

---

plugin/core/test_windows.py
plugin/core/windows.py

We never updated the current project path after a quick switch was detected, causing #448.
Updates the unit test to catch this scenario.

Fix switched project path

---

.gitignore
plugin/core/rpc.py
plugin/core/test_rpc.py
plugin/core/test_windows.py
setup.cfg
tox.ini

- The _response_handlers dictionary was never cleared.
- Add tests checking that it is cleared now after handling a response
from the server.
- Re-organize tox.ini so that contributors can just run "tox" on the
command-line and do the basic checks.

Fix RPC memory leak, update tests, and dust off tox.ini

---

plugin/core/test_documents.py
plugin/core/test_rpc.py
plugin/core/test_session.py
plugin/core/test_windows.py
tests/test_hover.py

There were a bunch of warnings all of the form
> PytestWarning: cannot collect test class 'TestFoo' because it has a `__init__` constructor
Simple fix is to rename them to MockFoo etc.

Fix all pytest warnings

---

plugin/core/rpc.py
plugin/core/test_rpc.py

If there's an error response, handle that.
Otherwise, handle the result.

Fix: we should be able to handle a "null" result from a server

---

plugin/core/protocol.py
plugin/core/windows.py

complement to https://github.com/tomv564/LSP/pull/470
See https://github.com/tomv564/LSP/pull/470#issuecomment-445992403

send null for result fiend when no-op for "window/showMessageRequest"

---

LSP.sublime-settings

If you install [Djaneiro](https://github.com/squ1b3r/Djaneiro), Python language server does not activate automatically because Djaneiro defines its own scope (`source.python.django`) and syntax (`Python (Django)`).

Add support for Djaneiro Python syntax

---

plugin/completion.py

Previously adding a space while requesting completion would
cause completion to stay in CANCELLING indefinitely.
Fixes https://github.com/tomv564/LSP/issues/510

Always reset completion state to IDLE when in CANCELLING

---

LSP.sublime-settings
docs/index.md
plugin/core/settings.py
plugin/core/types.py
plugin/references.py

Usually the quick panel is better suited for showing symbol references
because you can cycle through the references using the keyboard.
It is also closer to the original Sublime Text behavior.
I chose to make this opt-in to avoid confusing existing users.

Implement quick panel for symbol references

---

plugin/highlights.py

At least when using this package in conjunction with https://github.com/guillermooo/dart-sublime-bundle, there are cases where kind is None, resulting in an exception. This resolves that issue.

Fix exception when kind is None

---

LSP.sublime-settings

This PR adds a settings entry for pyls
I was trying to disable pyflakes warnings as they were annoying, I searched in the web, changed the settings such as:
```json
{
...
"settings": {
"pyflakes": {
"enabled": false
}
}
}
```
and
```json
{
...
"settings": {
"plugins": {
"pyflakes": {
"enabled": false
}
}
}
}
```
in various ways and gave up many times before stumbling upon the solution in a thread (I forget where)
and the trick was adding `"pyls"` entry like this:
```json
{
...
"settings": {
"pyls": {
"plugins": {
"pyflakes": {
"enabled": false
}
}
}
}
}
```
I think adding this entry commented will save many people a lot of time.

Add a settings entry in pyls configurations

---

LSP.sublime-settings

https://github.com/tomv564/LSP/pull/522 introduced a trailing comma that shouldn't be there.

Remove trailing commas in pyls configuration

---

LSP.sublime-settings
docs/index.md
plugin/completion.py
plugin/core/settings.py
plugin/core/types.py
tests/test_completion.py

An option is added to always prefer "label" over the "filterText" if the user so desires. However, certain language servers might use the "label" to denote extra data, e.g. a circular dot in front of the word-to-complete in case it returns a completion with an "additionalTextEdits" key. In this case, using the "label" for the ST trigger characters can give wrong behavior. An example of this wrong behavior is: https://github.com/tomv564/LSP/issues/368
One can take a look at the completion_test.py file to get a feel for what this change entails.
ping @ayoub-benali @frou

Fix: Use "filterText" (fallback to "label") for the trigger of the completion item

---

tox.ini

Pyls language server is not capable of parsing previous formatting of
flake8 configuration. It does its own parsing that expects rule codes
to be separated by comma.

Change flake8 rules formatting to make compatible with pyls

---

boot.py
plugin/core/edit.py
plugin/core/protocol.py
plugin/core/test_edit.py
plugin/core/windows.py
plugin/edit.py
plugin/formatting.py
plugin/rename.py
tests/test_edit.py

Separate sublime-tied logic to plugin/edit.py.
Add tests for remaining logic (response parsing, sorting)
Remove debugging status/logging when applying doc edits.
Part of an effort to improve unit test coverage.

Text editing cleanup/testability

---

plugin/core/completion.py
plugin/core/test_completion.py

The dart language server sends filterText in its completions, but the value is null.
fixes https://github.com/tomv564/LSP/issues/582.

Account for a present filterText key but its value is null

---

plugin/core/signature_help.py
plugin/core/test_signature_help.py
plugin/signature_help.py

Move parsing and formatting of signature help to core with tests

---

plugin/core/sessions.py
plugin/core/test_session.py
tests/setup.py
tests/test_completion.py
tests/test_configs.py
tests/test_hover.py

For the code that cannot be unit tested, we want it to be quick and reliable to add an in-sublime test.
This PR restored some disabled tests, extracted some shared setup / teardown logic so tests are less likely to affect each other.
MockClient (rename?) was also changed to support async responses

Improve in-sublime testing

---

LSP.sublime-settings
plugin/core/sessions.py
plugin/core/settings.py
plugin/core/signature_help.py
plugin/core/test_signature_help.py
plugin/core/types.py
plugin/signature_help.py
stubs/mdpopups.pyi

A single signature help implementation that does both (simple) syntax highlighting and active parameter highlighting.
Add support for language servers to send a [int, int] range instead of a string as parameter label (for  reliable highlighting): https://github.com/microsoft/language-server-protocol/commit/3854f1c503b3e1f1cab9b4f81e62fc47bc7d174a
Parses the signature label to classify three types of content:
* function
* parameter
* punctuation
Then uses mdpopups to get styles for relevant scopes, applied in `<span>` tags.
Although parentheses and parameters are detected, commas and text outside parameter labels are not detected - they inherit the "function" style.
So far tested with python-language-server and lsp-tsserver, would like more examples of servers that support signatureHelp!

WIP: Unify signature helps

---

plugin/core/transports.py

Give the stdio transport a bit of love, fix a fairly subtle bug that might have mistaken an empty string as EOF, make the processing loop state-driven like the TCP transport.
The LSP protocol does insert a blank line between the headers to signal where the content starts. There was a subtle bug in the stdio processing loop that could have mistaken a blank line as EOF, which is what `readline()` returns when it reads EOF.
I came across this while debugging an issue in `haskell-ide-engine`.

stdio transport fix

---

docs/index.md

This closes #565 , and additionally improves the overall functionality of the language server.
Without the initializationOptions, the language-server often crashes or errors-out on trying to provide completions*. With this new config, things run quite well.
\* vue-language-server does a very poor job of checking for attributes on the `vetur` object, it just assumes it's being run from VSCode and those options are set

Improve vue-language-server docs

---

plugin/signature_help.py

Hello,
I just noticed that we now have syntax highlighting and active parameter in signature help, which is great! :)  (although I don't use a very colorful colorscheme)
But I had some problems with determining visually what the active parameter is. 
Here are a few screenshots... By first glance it is hard to tell what is the active parameter, right?
With this PR, I just add a underline. The result is that you can immediately see what the active parameter is.

Add underline in active parameter

---

plugin/core/completion.py
plugin/core/test_completion.py
tests/test_completion.py

Using `label` for `trigger` works with many language servers.
Clangd and languages with `$` variable prefixes (Powershell and PHP) are notable exceptions where label and insertText/textEdit don't match. Here LSP will try to take off or re-add mismatching leading characters.
Hope is that this will improve completions for the next release without introducing new settings.

Test and fix completion label/replacement mismatches

---

plugin/completion.py
plugin/core/completion.py
plugin/core/test_completion.py
tests/test_completion.py

Sets up a post-completion hook so we can:
* Fix the completion using the item's textEdit (issue #536)
* Apply additionalTextEdits (issue #529)
`completionItem/resolve` is used to get the additionalTextEdits if the server indicates support.
Code is tested using examples given in issues, but more live testing with specific servers is needed!
Assumptions:
* If a command like `'commit_completion', 'insert_best_completion', 'auto_complete'` runs, the next `on_modified` is the insertion of the completion.
* It is always safe to trim the difference between the start of the current word and the textEdit's start.
* All additionalTextEdits should be immediately applied after the completion is inserted.
To do:

Completion with text edits

---

plugin/core/signature_help.py
plugin/core/test_signature_help.py

We are escaping the parameter of the signature help too many times

---

plugin/code_actions.py
plugin/core/sessions.py
plugin/execute_command.py

Fixes two issues:
- The Command's arguments passed to workspace/executeCommand should be
passed through 'arguments' property rather than 'args'.
- Fix handling of code action in case textDocument/codeAction [1] returns
list of CodeAction's rather than Command's [2].
Instead of having LspCodeActionsCommand duplicate logic of
LspExecuteCommand, pass data from former to the latter to
execute code action. Had to modify latter to not trigger a
dialog box on success as it's not the best user experience in case
when executing action from a popup menu.
- Advertise support for workspace/executeCommand as we clearly support
that. That wasn't necessary to fix anything but it felt right to do.
[1] https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction
[2] …

Correctly handle code action of CodeAction type (fixes #566)

---

plugin/core/completion.py

Addresses #623. In Ruby, symbols are denoted with a leading colon (like `:my_symbol`). This fixes the colon being dropped from the auto complete as described in the mentioned issue.
I noticed that there were similar fixes in the 0.8.4 release:
> Fix double '$' or removal of leading characters in some completions (clangd/PHP/Powershell)
I saw that those fixes were implemented pretty simply so I tried to follow the same format. Let me know if you think there might be any other issues with this, I'm happy to try to fix them if they are within my limited realm of Python knowledge.

Fix dropping a leading colon when accepting a completion

---

plugin/completion.py
plugin/core/completion.py
plugin/core/test_completion.py

The implementation for #299 and possibly a fix for #523 ?
If a language server responds with `isIncomplete: true`, then the completion handler will request fresh completions in `on_modified` as long as the completion list stays open. 
Tested somewhat with lsp-tsserver but I'd really like to hear how this works with real-life projects with intelephense and other servers!

Handle incomplete completion lists

---

plugin/core/sessions.py

RLS now requires a `codeActionKind` entry. An empty `valueSet` will
satisfy the requirement for now, allowing RLS to start normally. Fixes #630

Add empty codeActionKind entry

---

README.md
docs/index.md

I have tested the language server under Windows.

Add LaTeX language server (TexLab) to README and docs

---

plugin/completion.py
tests/test_completion.py

For issue #645 
TextEdits from completion items are being skipped because LSP incorrectly calculates the "current" completing word.
In this case it works: `List.a|` -> word_start is char 6
In this case it fails: `List.|` -> word_start is char 5
The fix is to check if the cursor position _is_ at a word to begin with.

Add failing test for textedit on non-word completion

---

plugin/hover.py

In C#, you can get hover text that contains angle brackets.  Angle brackets don't need to be escaped in markdown.  The problem is that mdpopups.md2html doesn't escape our angle brackets and causes invalid HTML to be generated, so let's escape our hover text before we toss it into md2html.

Escape the hover text.

---

plugin/hover.py

Close #657.
~Otherwise mdpopups will complain.~
~Also add two hover tests to cement this behavior.~
cc @LoneBoco

Do not escape hover content

---

Menus/Main.sublime-menu

So other LSP Handler Plugins settings can be added to the same sublime menu.

Add settings id

---

README.md
docs/index.md

Add elm to docs

---

.gitattributes

The current master of `LSP.sublime-package` has a size of ~725KB. Almost all size comes from images in the `docs/` directory, which is not useful at local imho.
After excluding it, the packed size is ~120KB.

Exclude docs/ folder while packaging

---

plugin/hover.py

Fixes #607 and #625.
LSP will always request hover info from the server, and stop showing the `No description available` popup if the server has no info in the response.

Remove filter on comment and string for requesting hover

---

LSP.sublime-settings

Must be enabled manually, documented:
https://github.com/castwide/solargraph/issues/37#issuecomment-380520595

Add ruby RuboCop linting to initialization options

---

LSP.sublime-settings
boot.py
docs/features.md
plugin/color.py
plugin/core/main.py
plugin/core/protocol.py
plugin/core/registry.py
plugin/core/sessions.py
plugin/core/settings.py
plugin/core/types.py
plugin/highlights.py

This PR brings support for `textDocument/documentColor` request.
It will display a box next to the color. 
By default I have set  `show_color_box` to `false`.
Also, one thing I did with this PR is a little bit of cleanup in the unload_plugin logic.
Before:
We iterated multiple times though the windows to do the cleanup.
Now:
We will iterate only once thought the windows and views. and in that one iteration do the cleanup.
Although in reality, the user would have max 3 sublime windows open. :) 
But still. I think it is a small nice clean up.

Add color provider support

---

plugin/color.py

The phantom created by LSP is make the height of the line larger a little bit.
- Similar issue that I reported to ColorHelp weeks ago: https://github.com/facelessuser/ColorHelper/pull/122

Fix inline color phantom makes line height larger a little bit

---

plugin/hover.py

I tried the elm language server, and noticed one thing.
The diagnostics for errors were really hard tor read. They were all concatenated into one big hard to read string. 
So this PR fixes that.
Before
After
I know  mdpopups has a `nl2br` option, but setting it won't cause the new lines to translate to breaks.
https://github.com/tomv564/LSP/blob/67a55b7978651f29d8c7d1e0873c8f20deff8ce1/plugin/hover.py#L169-L179
So if you know a better way how to fix this, please close this PR :)

Fix new line to break

---

plugin/configuration.py
plugin/core/configurations.py
plugin/core/registry.py
plugin/core/settings.py

This PR contains only direct fixes where change global client configs would not propagate to windows. #708 will look into more cleanups and improvements
The issues below were caused by all windows sharing values from `client_configs.all` so all windows would pick up changes instantly for free. But when project overrides were in place we would copy the global config, orphaning the copy from global changes.

ConfigManager listens for  and propagates global client config changes to windows

---

plugin/code_actions.py
plugin/color.py
plugin/completion.py
plugin/configuration.py
plugin/core/configurations.py
plugin/core/registry.py
plugin/core/test_configurations.py
plugin/core/test_windows.py
plugin/core/windows.py
plugin/execute_command.py
plugin/formatting.py
plugin/goto.py
plugin/highlights.py
plugin/hover.py
plugin/references.py
plugin/rename.py
plugin/signature_help.py
plugin/symbols.py
plugin/workspace_symbol.py
tests/test_completion.py

Fixes #562 where view and command-based LSP code only looks at scope to find the most suitable session. 
In a case where two servers run for the same scope (eg. typescript and eslint server on `source.js`), LSP would pick the first session, instead of checking which server provides the relevant capability.
Implementation details:
* Forced all lookups to consider multiple servers by changing `scope_config` -> `scope_configs`
* `session_for_view` and `LspTextCommand.client_with_capability` take capability parameter.
* Use iterators to save some effort of calculating 2nd, 3rd matching session if only the first session is needed.
* Attempt to fix some timings on completion tests on travis.

Lookup session by capability

---

plugin/core/windows.py
plugin/core/workspace.py
plugin/diagnostics.py
plugin/references.py

As logs in #668 show, when running sublime without a project, sessions get restarted every time you open a file from a different folder. 
The "switch project" detection logic was firing accidentally when switching files. The solution effectively disables this logic by not setting `_project_path` - instead a separate `_projectless_root_path` member is used.
`_projectless_root_path` will only be set once per window.

Simplify projectless sessions

---

plugin/core/logging.py
plugin/core/main.py

The use of the `log_server` setting seems to have been removed at some point. This reintroduces it it again.
Just out of curiosity, would it not be possible to import `settings.settings` in logging.py and read the various log settings directly instead of setting it from main?

Use log_server setting

---

plugin/core/edit.py
plugin/core/test_edit.py
plugin/edit.py
tests/test_edit.py

Fixes #690 where gopls is returning edits for a line that doesn't exist - this happens to work with VS Code because implementation details.
To do:

Create a new line for edits after the document

---

plugin/completion.py
tests/setup.py

Sublime has a pretty good scope-based filter for determining if we need completions. 
Switching to this setting:
* Allows the user to change the completion scopes without editing the package source
* Disables completion in comments (no more completion on '.' in comments)
* Allows completion in string literals (at least, works in typescript for me)

Use sublime's auto_complete_selector setting for filtering completions

---

plugin/references.py

Things that should be constant for an invocation of "find references" are now set as members when the command is invoked (word, word_region and base_dir).
The references are always stored grouped by _full path_. Relative paths are not made until display text is being built.
Also replaces the complex "find nearest reference" to picking the first occurrence from the current file, hope it is good enough.
Fixes #727

Unentangle references logic for panel/quick panel and base_dir handling

---

.style.yapf
docs/features.md
plugin/core/protocol.py
plugin/core/rpc.py
plugin/core/sessions.py
plugin/formatting.py

For issue #8 
Adds support for sync request (blocking the editor for up to 1 second)
Default off, enable by setting `lsp_format_on_save` to true in preferences.

Format on save

---

plugin/code_actions.py
plugin/core/popups.py
plugin/core/protocol.py
plugin/diagnostics.py
plugin/hover.py
tests/test_hover.py

The Hover popup currently always shows a Code Actions link, even if no code actions are available. This PR aims to query the server, then show information about available code actions in the popup.
This shows an initial implementation, running with a typescript and eslint server.
[
](url)
**Two functional issues need to be resolved:**
- (I'm hesitant to get into this, but of all places to combine LSP results, this use case probably makes the most sense)
**UI opinions wanted**
The hover UI is getting messy. Code actions feel like they "belong" to the diagnostics, but there can be many blocks of diagnostics (errors and warnings, per server) so it's unclear where to place the links.
**Technical fixes**

Pre-request code actions

---

LSP.sublime-settings
docs/index.md
plugin/core/sessions.py
plugin/core/settings.py
plugin/core/transports.py
plugin/core/types.py

If `tcp_mode` is "host", LSP opens specified `tcp_port` (or selects a free port)
The resulting port is replaced into a `{port}` placeholder in the server's command line
The language server is expected to connect, after which LSP starts initializing.
This is suggested to be the default behaviour by Microsoft, although many servers have implemented a server-owned port.
Solves issue #513

Client-hosted tcp connection

---

LSP.sublime-settings

It is very common to use GoSublime when working on a go project in
sublimetext which comes with it's own syntax for Go files.
This adds the default recommended GoSublime syntax to the gopls client
config

Add GoSublime-Recommended syntax to gopls config

---

Menus/Context.sublime-menu

The number of LSP capabilities grows larger and larger :) I think it makes sense to put the items of the context menu into a child menu.

Put the context menu into a separate child menu

---

plugin/core/sessions.py
plugin/core/test_session.py

There's no need to keep this information around. The authority on that
information is the WindowManager class.
One of the building blocks for #697.

Remove the project_path property of the Session object

---

LSP.sublime-settings
docs/features.md
plugin/code_actions.py
plugin/core/diagnostics.py
plugin/core/main.py
plugin/core/protocol.py
plugin/core/settings.py
plugin/core/test_diagnostics.py
plugin/core/test_windows.py
plugin/core/types.py
plugin/core/windows.py
plugin/diagnostics.py
plugin/hover.py

The "Show diagnostics panel after saving" investigation (#748) showed the functionality could be "tacked" on, but would work better if components were set up in proper relations instead of querying global state.
In this PR, a DiagnosticsPresenter is introduced which gets access to DocumentHandler's events.
Clean ups:
Desired fixes:

Diagnostics rework

---

plugin/core/completion.py
tests/test_completion.py

@ckipp01 I haven't actually tested this with a snapshot build of MetaLS. Could you try this branch?
close #771

Extend completion heuristics for metals' 'implement all members'

---

plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/test_diagnostics.py
plugin/hover.py
popups.css

Closes #492 
It's pretty ugly, though RLS's duplicate content in the diagnostics doesn't help:
Discussion of how VS Code implemented the UI: https://github.com/microsoft/vscode/issues/10271

Parse and show related information in diagnostics hover content

---

plugin/core/signature_help.py
plugin/core/test_signature_help.py
plugin/hover.py

Closes #486
Specific fixes for the related issues #604 and #646 
Long hover before:
after:
Long signature before:
after:
Worth noting:
* Line breaks added at 80 characters, I'm aware there's logic in SublimeLinter that sets a viewport-relative limit but perhaps this is enough?
* Splitting does not work in signature labels that don't use commas.  
To do:

Break long spans in popups

---

Commands/Default.sublime-commands
phantoms.css
plugin/core/diagnostics.py
plugin/core/protocol.py
plugin/core/test_diagnostics.py
plugin/diagnostics.py

Press  <kbd>F8</kbd> to open/next, <kbd>shift+F8</kbd> for previous, <kbd>esc</kbd> to close. (see suggested keybindings)
Essentially like VS Code's "Next Problem" feature. 
Suggested keybindings
```json
{ "keys": ["f8"], "command": "lsp_next_diagnostic"},
{ "keys": ["shift+f8"], "command": "lsp_previous_diagnostic"},
{ "keys": ["escape"], "command": "lsp_hide_diagnostic", "context":
[
{ "key": "setting.lsp_diagnostic_phantom"}
]
}
```
Closes #746:
* Allows navigation for those who don't like to use the panel for it (SublimeLinter style)
* Allows a faster and more readable way to see a diagnostic + related info than hovering.
Implementation details:
* The DiagnosticsPresenter passes user actions (forward/back) and server diagnostic updates into the DiagnosticsCursor
* The cursor selects a …

Show previous/next diagnostic with phantom

---

plugin/code_actions.py
plugin/diagnostics.py
stubs/sublime.pyi

Send Code Action request only if the Region didn't changed for 800ms.
Previously we only checked if the .begin() of the region didn't changed for 800ms.
But in that case we might end up in situation when making a selection,
where we had code actions but didn't show a bulb, because the begin in selections didn't change.
https://github.com/tomv564/LSP/blob/f9c68aa98266e23f61b1254c3f41ee0af8c00f64/plugin/code_actions.py#L136
The bug:
After this PR gets merged:

Fix bulb not showing up in selections even if code action exist

---

plugin/configuration.py
plugin/core/configurations.py
plugin/core/test_configurations.py
plugin/core/test_mocks.py
plugin/core/types.py
plugin/core/windows.py
tests/setup.py

This PR tries to improve the logic and implementation details around config management:
Not investigated:
* ClientConfig.enabled can be in (absent, True, False) for global and project settings: This means 9 combinations. Which ones make sense and which ones do we want to avoid?

Client config handling improvements / cleanup

---

LSP.sublime-settings
README.md
docs/index.md

Add configuration and instructions to make [elixir-ls](https://github.com/elixir-lsp/elixir-ls) work
Sadly still needs a bit of manual configuration since this probably won't ever be in the path

Add elixir-ls support

---

Commands/Default.sublime-commands

In the style of GitSavvy, Terminus, etcetera.
It chooses the correct keybinding file based on the ${platform}.

Advertise keybindings in the command palette

---

LSP.sublime-settings
plugin/core/diagnostics.py
plugin/core/settings.py
plugin/core/types.py
plugin/diagnostics.py

Closes #795
Next/previous diagnostic was hardwired to Errors and Warnings, but as we have a setting controlling what the user thinks is relevant (`show_diagnostics_severity_level`), we should read that instead.
Also drops the severity filter for in-view diagnostic regions. This is because as a developer I want quick access to errors and warnings, but still want to see server suggestions somewhere.
- <strike>For those offended by `info` and `hint` squigglies in their code, should we expose `diagnostic_severity_scopes` as a setting? (We could drop some of the fallback scopes and give the user the chance to not set any scopes at all for some diagnostics)</strike> Can do this later.

Apply severity filter to diagnostics panel and navigation, not underline/hover

---

docs/features.md
plugin/core/main.py
plugin/core/types.py

While debugging, I found a reference to a removed setting.
I think it's nice to have this setting, so instead of removing it, I used the show_view_status setting. Let me know if I should just remove it altogether.

fix: remove reference to obsolete setting

---

LSP.sublime-settings
docs/index.md

Following on from issue #812 have added R to the default list of clients in `LSP.sublime-settings` and added a note to the docs to install `languageserver` from CRAN first.

Closes #812 added R to default config and to documentation

---

.travis.yml
plugin/completion.py
plugin/core/configurations.py
plugin/core/protocol.py
plugin/core/rpc.py
plugin/core/test_diagnostics.py
plugin/core/test_mocks.py
plugin/core/test_session.py
plugin/core/transports.py
plugin/core/types.py
plugin/core/windows.py
plugin/references.py
tox.ini

Unsure if we really want to do this for ST3, but this PR will track the impact:

Upgrade python and tools to recent version

---

mypy.ini
plugin/core/process.py
plugin/core/test_process.py

There's nothing in the LSP spec about the encoding of the stderr stream (or in the case of the TCP transport the stdout stream). We're assuming UTF-8, which is a good choice I think, but if the encoding fails we can try UTF-16 as a last resort.
Related: #249

Replace undecodeable UTF-8 sequences by '?'

---

plugin/completion.py
plugin/core/documents.py
tests/test_completion.py

Testing with python language server, starting with 
```
view|
``` 
and typing `.settings()` quickly, resulted in _several_ completion requests, and the results shown when irrelevant:
This sequence should result in only 1 completion request of which the results are never shown.
This PR
* prevents showing completion results after crossing a word boundary (https://github.com/tomv564/LSP/commit/54c93d2067e02db7b6706c701c278e8a4660f545),
* prevents discarding requests (going to CANCELLING) when `is_same_completion` (https://github.com/tomv564/LSP/commit/173ea358dc8403a6345963d7831d0d3177699b0c)
* makes `is_same_completion` return True when going from `.` to `.s`  by undoing the fix for #745 (https://github.com/tomv564/LSP/commit/861b7e5dc3e838409430818b13323f6485e8c008)
Also fixes a related …

Completion filtering fixes

---

plugin/configuration.py
plugin/core/clients.py
plugin/core/documents.py
plugin/core/process.py
plugin/core/protocol.py
plugin/core/registry.py
plugin/core/sessions.py
plugin/core/test_documents.py
plugin/core/test_mocks.py
plugin/core/test_session.py
plugin/core/test_windows.py
plugin/core/test_workspace.py
plugin/core/types.py
plugin/core/windows.py
plugin/core/workspace.py
plugin/diagnostics.py
plugin/hover.py
plugin/references.py
tests/setup.py

Closes #443 - if people are satisfied they can setup multiple project folders into their monorepo-style workspace
Closes #785 - if someone can confirm this makes the "module in wrong path" error from Go go away.
**Implementation details**
* A window now stores a list of sessions per configuration, instead of just one session per config.
* Each session has a list of paths it handles, which can be queried with `session.handles_path(file_path)`
* Servers are sent all folders at startup, the first folder being the one a file was originally opened in.
* If the server confirms support for multiple folders, the session keeps all folders. 
* If not, only the folder with the opened file is kept. 
* We can send `didChangeWorkspaceFolders` when opening a file in a newly added folder. Added in …

Multiple-folder project support

---

LSP.sublime-settings

Allow LSP to process TypeScript using the lighter-weight "TypeScript Syntax" package rather than the full "TypeScript" package that includes a full language server protocol implementation

Add more TypeScript Syntax support

---

plugin/core/sessions.py
plugin/core/windows.py
plugin/core/workspace.py
tests/setup.py
tests/test_documents.py
tests/test_mocks.py
tests/test_single_document.py
tests/test_windows.py
tests/test_workspace.py
unittesting.json

- Take the first available language server if it's workspace-unaware
- Take the one and only language server if it's workspace-aware
- Ensure things work when ST is started with a foreign file
- Ensure sessions know what type of language server they are dealing with
(i.e. workspace-aware or workspace-unaware) with a mutex lock.
Actually, you can use that same mutex lock to check wether a
session is ready (thus simplifying some test code)
The DocumentHandler needs to know wether a file is inside or outside the workspace for its _get_applicable_sessions method.

Fix "goto def" for a foreign file (outside the workspace)

---

LSP.sublime-settings

This lets tsserver interpret the source properly.
(Sorry these fixes are coming one at a time, I'm fixing them as I find them and you're merging too fast :-)

Set "...react" languageId for .jsx and .tsx files

---

README.md
docs/index.md
mkdocs.yml

Closes #805
This PR reworks the main site of the documentation, which has become pretty unorganized and inconsistent over the time:
* Move general "Server Configuration" and "Per-project overrides" sections to top of the site
* Add a new introductory section with explanations for beginners and links to language-specific LSP-xxx packages on Package Control
* Group servers by language (IntelliJ -> Java) and reorder all languages alphabetically
* Use consistent formatting and indentations for the code blocks
* Improve some descriptions where appropriate
* Fix typos and several broken links
* I saw that @AmjadHD took some effort before in #642, but that PR was closed. I adopted his idea to use a table for the settings' parameter descriptions
* Add description for Fortran language server
For …

Rework documentation

---

plugin/goto.py

When navigating to a symbol's implementation, the existing behaviour was to go to the first implementation it receives from LSP.
This pull request will pop up a dialog and let the user pick from multiple implementations.
Gif preview: https://github.com/mrbrian/LSP/blob/big_gifs/docs/images/goto_implementation.gif
I've only tested my changes with C++ & CCLS so far.  I'm not sure how to setup a test with Javascript.

Allowing user to pick from multiple implementations when using 'Go to symbol implementation'

---

plugin/core/windows.py

Noticed `didSave` was not being sent even though rust-analyzer requested `save: {}`.
```
>>> bool({})
False
```
Tested with rust-analyzer.

An empty dict should enable a textDocumentSync notification

---

.github/workflows/main.yml
plugin/completion.py
plugin/core/protocol.py
plugin/core/registry.py
plugin/core/sessions.py
plugin/core/transports.py
plugin/core/types.py
plugin/core/windows.py
tests/probe.txt
tests/server.py
tests/setup.py
tests/test_completion.py
tests/test_configs.py
tests/test_diagnostics.py
tests/test_edit.py
tests/test_process.py
tests/test_protocol.py
tests/test_session.py
tests/test_single_document.py

A session is ready _or_ initializing if and only if
1) it is present in wm._sessions
A session is ready if and only if
1) it is present in wm._sessions
2) a call to session.handles_path(...) or session.supports_workspace_folders() returns
A session that is exiting is immediately popped from wm._sessions, so we cannot obtain a session that is exiting.
Since wm.get_session(...) always calls session.handles_path, we are guaranteed a ready session.
We have to await the initialize request because we need to determine wether the session is workspace-aware or workspace-unaware before calling session.handles_path.
Language servers that don't respond to the initialize request are disabled temporarily for the window.
- ~Let's try adding a Windows CI~
- ~Find and make sure that language servers that …

Session state

---

tests/server.py

When running: `UnitTesting: Test current file` in test_completion.py
sublime would not run the tests 
and it would show a popup saying that the server didn't initialize in 3sec, 
because 'asyncio' has no attribute 'get_running_loop'.
All credit goes to @rwols.

FIX AttributeError: module 'asyncio' has no attribute 'get_running_loop'

---

plugin/core/clients.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/windows.py
plugin/core/workspace.py
tests/test_documents.py
tests/test_mocks.py
tests/test_session.py
tests/test_sublime.py
tests/test_windows.py
tests/test_workspace.py

Moreover, account for nested workspace folders.
Added a test for this.
Also, disable a language server if it responds with an error for the initialize request.
Flow returns an error when its version doesn't match with what is stated in .flowconfig.
Tested with Flow language server and a sublime project with the structure /foo, /foo/bar.
This results in the following behavior:
1. Language server is started for some folder /foo
2. It fails somehow. "blacklist" the server name + folder pair
3. A file is opened in another workspace.
4. Language is not blacklisted for this server name + folder pair, so we attempt to start a process
5. It succeeds.
6. User can move on with his/her work.
Thus there are two ways to disable a lang server:
1. Disable locally per workspace folder. We do this if it …

Disable a server only for a specific folder of the project, if it fails to init

---

messages/0.9.4.txt
plugin/completion.py
plugin/core/documents.py
plugin/core/protocol.py
plugin/core/rpc.py
plugin/core/sessions.py
plugin/core/views.py
plugin/core/windows.py
plugin/formatting.py
plugin/goto.py
plugin/highlights.py
plugin/hover.py
plugin/references.py
plugin/rename.py
plugin/signature_help.py
tests/test_documents.py
tests/test_mocks.py
tests/test_session.py
tests/test_views.py

Also:
- Move some of the boring boilerplate param construction to views.py
- Session gained some knowledge about whether we should send various
text doc sync notifications
- Add tests for various server text sync capabilities
- Add tests for the various conversion functions in views.py (perhaps we should rename that to conversions.py)

Notify textDocument/willSave, and include text (if needed) in textDocument/didSave

---

plugin/references.py

When the `show_references_in_quick_panel` setting is true, references are shown in the quick panel. In `LspSymbolReferencesCommand`, references are stored in the `reflist` variable, which are then passed to `window.show_quick_panel` to display the results. However, at no point is `reflist` emptied. So, as more references are displayed, previous results accumulate in the panel, which gets very noisy.
This PR simply clears `reflist` before it is repopulated.

Fix accumulation in reference quick panel.

---

Syntaxes/ServerLog.sublime-syntax
plugin/core/protocol.py
plugin/core/rpc.py
plugin/core/sessions.py
plugin/core/windows.py
tests/test_rpc.py

Request IDs can be strings or integers.
We, the text editor, always use integers for request IDs.
But some servers may send out e.g. GUIDs as request IDs.
I decided to type-erase the request ID in various places,
because all we're doing in most functions is passing through
the received request ID from the server all the way to our
Response object, finally serializing it back to JSON again.
close #905 
@jwortmann, mind giving this branch a try?

Account for server request ID strings

---

docs/index.md

`pip install python-language-server` installs only the python language server while `pip install 'python-language-server[all]'` additionally installs optional providers such as pycodestyle and yapf, users would generally want/expect these providers.

improve pyls installation command

---

plugin/core/views.py
tests/test_views.py

<details><summary>YAML codes for reproduction</summary>
```yaml
parameters:
locale: 'en'
j: ""x
services:
_defaults:
autowire: true      # Automatically injects dependencies in your services.
autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
public: false       # Allows optimizing the container by removing unused services; this also means
```
</details>
<details><summary>LSP diagnostic panel</summary>
```text
◌ C:\Users\Clover\Desktop\test.yaml:
4:115 	None        	error     	can not read a block mapping entry; a multiline key may not be an implicit key
```
</details>
<details><summary>LSP payload log</summary>
```text
:: <-- yaml-lsp textDocument/publishDiagnostics: {'diagnostics': [{'message': 'can not read a block mapping entry; a …
```

Fix point_to_offset() when Position.character > line length

---

docs/index.md
plugin/core/sessions.py

The workspace/configuration request seems to be implemented differently in various servers:
* The Julia server sends multiple configuration keys as `section`
* The ESLint server sends a blank section instead, but expects a single dict of configuration settings.
* According to https://github.com/sublimelsp/LSP/pull/737#issuecomment-536482338 the Kotlin server sends a single "kotlin" as `section`.
This PR makes LSP to read each `section` from the server's settings in LSP.sublime-settings, so for the Julia server they could for example be
```json
"settings": {
"julia.format.calls": false,
"julia.format.comments": false,
"julia.format.curly": false,
"julia.format.docs": false,
"julia.format.indent": 4,
"julia.format.indents": false,
"julia.format.iterOps": false,
"julia.format.kw": false, …
```

Read values for workspace/configuration request from settings

---

plugin/core/protocol.py

You can put folders in your .sublime-project that don't exist.
For now we can pass-thru those folders.
close #893

Be more lenient about non-existing folders

---

Syntaxes/ServerLog.sublime-syntax
messages.json
messages/0.9.7.txt
plugin/core/protocol.py
plugin/core/rpc.py
tests/test_rpc.py

- When there's no request handler, reply with an error with code MethodNotFound
- When there's an exception thrown in the request handler, translate that exception to an error response.
- When there's an exception of type Error thrown in the request handler, send that error as-is.
Quoting the JSON-RPC 2.0 spec, which LSP is based on:
When a rpc call is made, the Server MUST reply with a Response,
except for in the case of Notifications.
Admittedly this is talking about "the server", but the LSP spec page says every request must be paired with a response, omitting the word "server": https://microsoft.github.io/language-server-protocol/specification#requestMessage
And the wikipedia page also talks about "the receiver" of a request: https://en.wikipedia.org/wiki/JSON-RPC#Usage
In any case, …

Reply to all requests

---

LSP.sublime-settings
README.md
docs/index.md

Add Erlang to Sublme LSP Client documentation (... and also removes some trailing whitespaces).
Fixes erlang-ls/erlang_ls#401.

[erlang-ls/erlang_ls#401] Add Erlang to Sublme LSP Client documentation

---

LSP.sublime-settings
plugin/core/clients.py
plugin/core/protocol.py
plugin/core/registry.py
plugin/core/sessions.py
plugin/core/settings.py
plugin/core/types.py
plugin/core/windows.py
plugin/core/workspace.py
tests/setup.py
tests/test_documents.py
tests/test_mocks.py
tests/test_session.py
tests/test_sublime.py
tests/test_windows.py
tests/test_workspace.py

This PR proposes to replace the initialisation lock with necessary checks and state management.
As far as I know there is no requirement for servers to respond to initialise in a certain time, so we should stop punishing our users for using servers like Metals.
Will not attempt to fix other edge cases related to server initialization as they can be solved in future work.
*Bugs to fix*
- Make sure sessions with same but different case paths match files being opened 
- Stop opening files outside workspace if workspace folders are defined
- Make sure to not open more files for sessions that are initializing
-  REVERTING Disable a server only for a specific folder of the project, if it fails to init    
- We don't need complexity to support working with broken setups/servers
- Do prefer …

Remove initialisation lock

---

plugin/core/sessions.py

The LSP doesn't seem to be defining any guidelines on what goes into each field, but it seems that most clients just put the editor's name and editor's version.
I can imagine some useful additional information such as OS/arch and version of the plugin here, but I'm being intentionally conservative for now and I feel this could this deliver some value to Language Servers that wish to collect some usage data and understand their user base.

core: Send clientInfo in initialize request

---

LSP.sublime-settings
docs/index.md

Hi,
The scope of this PR is to add default config for Sorbet, static type checker for Ruby (https://github.com/sorbet/sorbet).

add sorbet type checker to lsp

---

plugin/core/transports.py

Sometimes the server can crash and exit with a non-zero exit code. This allows the server to be restarted if necessary.

Restart the server when it fails on exit

---

plugin/hover.py

The popups.css selector uses ".lsp_popups .actions a" which does not
match the generated html. Without this, the links are solid blue without
framing.

Add 'actions' class to hover popup action links.

---

LSP.sublime-settings
README.md
docs/index.md

Just a little thing I whipped up using the SourceKit LSP server that ships with Xcode 11.4. This seems to work, but is this the right way to add support for a new server?

Add support for Swift's sourcekit-lsp

---

plugin/hover.py
stubs/mdpopups.pyi

It seems to only break lines if it finds opportunity to
do so (whitespace). That means that in some cases lines won't
be wrapped where old code would aggressively wrap.
Resolves #859

Use line-wrapping algorithm provided by mdpopups

---

docs/index.md

It was pointed out [here](https://github.com/sublimelsp/LSP/pull/916#issuecomment-602043968) that after having deleted trailing whitespaces which signaled newlines, the format of the Julia and Fortran sections was broken. Also the numbering in the Erlang section was off.
This PR removes the reliance on trailing whitespaces and fixes the numbering.

Fix formatting and numbering for items

---

plugin/completion.py
tests/setup.py

This makes the AC show up for labels that have an odd prefix like a space character (e.g. clangd).
close #935

Set auto_complete_preserve_order to none

---

plugin/diagnostics.py

In commit https://github.com/sublimelsp/LSP/commit/3c267eab898cf43778a1d05e6b582045b8812b4b a change was made to underline all regions for all severities of diagnostics. However `range` isn't inclusive at the upper limit and thus, hints are currently excluded.

Fix off-by-one error

---

plugin/completion.py

I guess when we convert the tuple into a list we're forgetting what kind of tuple it was. So it's a List[Any] at that point. Converting back to tuple makes mypy think that we're assigning a Tuple[object, object, ...] to a Tuple[int, str, str]. Anyway, this avoids the problem by constructing a new tuple right away.

Fix mypy error

---

plugin/core/sessions.py
tests/test_session.py

The textDocument/willSave was sent too eagerly.
We should notify only when "willSave" is set to True in the server's
capabilities. So willSave will never be sent for old-style text doc
sync capabilities.
The textDocument/didSave was also sent too eagerly.
It should only be sent when:
- "save" is a dict, whether empty or not, or
- "save" is a boolean with value True.
So didSave will also never be sent for old-style text doc sync
capabilities.

Be a little less eager to notify willSave and didSave

---

plugin/code_actions.py
plugin/hover.py

It looks the intention of `request` function was to set the value
of passed-in `diagnostics_by_config` but that of course doesn't work as
arguments are not passed by reference in python.
The one place that actually needs diagnostics (modified in this PR)
gets them itself before calling `request` anyway.

Remove unused argument to CodeActionsManager.request

---

plugin/diagnostics.py

Say a diagnostic with the following message has been published for a source line
```python
'This expression has type bool\nThis is not a function; it cannot be applied.'
```
When the caret is on the line, the diagnostic message is shown in the Status Bar:
...but the Sublime API function `View#set_status` simply eats the newline that's part of the string, meaning those two words become conjoined.
This PR inserts a space into the string passed to `set_status` where a line in a diagnostic message ends without trailing whitespace and the next line starts without leading whitespace.

Compensate for View#set_status eating newlines of diagnostic messages

---

plugin/completion.py

closes #933 
For now this will only be added for the `"` char, with the selector punctuation.definition.string.begin.
If we notice more of this cases where the AC is triggering forever,
we could either assign a special selector like we did here,
or fill an issue to the language server that it shouldn't return completions in that case.
That is also an option worth considering.
The server could specify not to return completions when inside comments. (just giving elm language server as an example :) ) https://github.com/elm-tooling/elm-language-server/issues/238

Add more specific selector for some trigger characters.

---

plugin/completion.py
tests/test_completion.py

The buffer can be modified by the user, e.g. by typing more characters
while the AC widget is visible. This invalidates all text edits returned
by the language server. We now account for this by keeping an eye on the
buffer modifications via on_text_changed and adjusting the text edits
accordingly.
Another problem was that we called view.change_id() too early. It should be
called just before running the completion command. This accounts for the
prefix removal that ST does.
close #956

Fix buffer modifications while completing

---

plugin/core/views.py

The `rangeLength` is marked deprecated in the specs.
see: https://microsoft.github.io/language-server-protocol/specification.html#textDocument_didChange
Nevertheless it is still required by some language servers such as
RedHat's LemMinX and needs to be passed to make them happy.

Fix incremental didChange notification

---

notification.css
plugin/core/message_request_handler.py
plugin/core/windows.py
tests/test_message_request_handler.py
tests/test_mocks.py

[Previously](https://github.com/sublimelsp/LSP/pull/470) it was handled with show_quick_panel but we couldn't show
the request message to the user. Until ST4 would allow such a feature
we resort to mdpopups.show_popup

migrate window/showMessageRequest handling to mdpopups.show_popup

---

README.md
docs/index.md

Close #980 
Also fix some whitespace and add back a few fenced code blocks after the last item in a list, because the version of Mkdocs that we use with readthedocs otherwise doesn't recognize comments in indented code blocks (in contrary to the latest Mkdocs release when tested locally).
And add some more LSP-xxx packages that are on Package Control now.

Add Dockerfile language server to docs

---

.github/workflows/main.yml
plugin/completion.py
plugin/core/rpc.py
tests/setup.py
tests/test_single_document.py

At least locally the window was closed when running `close_all` command
and that made the tests fail due to missing window.

Various fixes / improvements

---

plugin/core/panels.py

Some servers return OS specific newlines, which need to be normalized to `\n` for proper display. Otherwise ST prints `<0x0d>` at each eol.

Normalize server panel message newlines

---

plugin/completion.py
stubs/sublime.pyi
tests/test_completion.py

The LSP-filterText is truly the suitable thing for the ST-trigger.
If an LSP-filterText is present, we have a bit of a problem on where
to stuff all of the interesting things.
I decided to put the LSP-label into the ST-annotation field.
That leaves us with only the ST-details to fill in. If there's an LSP-detail,
use that. Otherwise, use the LSP-documentation for the ST-details.
In case there's no LSP-filterText, we are supposed to use the LSP-label
for the ST-trigger. In that case there are enough fields: the LSP-detail
can go into the ST-annotation, and the LSP-documentation and go into the
ST-details.

Use filterText as trigger, if it's present

---

plugin/diagnostics.py

Status wasn't cleared when cursor was moved away from region with
diagnostic region so it appeared stuck.
There are still cases where it might not be removed like removing line
with diagnostic region without changing cursor position. It's can be
fixed easily by moving cursor though.
We could also handle on_text_changed_async (ST4) or on_modified_async (ST3)
to make this more reliable but I'm not sure it's worth the gain.

Remove diagnostic from status when moving away from region

---

plugin/completion.py

This gives us order of items as defined by the server (alphabetical
or otherwise relevant) instead of seemingly random order from
ST's algorithm.

Use `INHIBIT_REORDER` flag when only showing lsp completions

---

boot.py
plugin/completion.py
stubs/sublime.pyi
tests/test_completion.py

This allows us to handle any text edit.
Also I split up the command completions:
- LspCompleteTextEdit for text edits (complex),
- LspCompleteInsertText for insert text that has additional edits,
- snippet completion for insert text that doesn't have additional edits.
There is also a separate command to handle resolving documentation,
but it's a work in progress. There is only some skeleton code.

Use sublime.COMPLETION_FLAG_KEEP_PREFIX for text edits

---

plugin/core/protocol.py
tests/test_protocol.py

With content like:
```
const x = 1
```
and error diagnostic at the end of the first line (missing semicolon),
it was impossible to trigger hover popup with code actions when hovering
end of the line due to `Range.contains`' broken logic.
The `Range.contains` logic was broken when range spanned more than one
line and point's column was larger than range's `end` column.

Fix hover popup not triggering in some cases when hovering diagnostics

---

.gitattributes

So they won't be shipped in the .sublime-package

Mark CI/CD files as export-ignore 

---

plugin/core/sessions.py

We can always expand/change this in the future.
For now, we understand dynamic registrations of the following methods:
- ~~textDocument/didOpen~~
We notify the server if the server registers this method.
- ~~textDocument/willSave~~
We notify the server if the server registers this method.
- ~~textDocument/willSaveWaitUntil~~
We do the request if the server registers this method.
- ~~textDocument/didSave~~
We notify the server if the server registers this method.
- ~~textDocument/didClose~~
We notify the server if the server registers this method.
- ~~workspace/didChangeConfiguration~~
Registering this capability does nothing interesting: we only notify
a change in configuration when we initialize the session.
(this is a problem of ST3, but we can improve this in ST4)
- …

Start with basic dynamic capabilities

---

plugin/core/protocol.py

Avoid `TypeError: 'NoneType' object is not iterable` in case of `'relatedInformation': None` (Julia server).

Fix error on diagnostics 'relatedInformation': null

---

Syntaxes/ServerLog.sublime-syntax
plugin/core/rpc.py

The payload wasn't logged at all (it was always "None") as result was
not returned from handle_response() (because frankly it's not needed
apart from logging).
Also marking sync responses with a symbol that matches sync requests
to be able to spot them better.

Fix logging of sync payload

---

plugin/core/sessions.py
tests/test_session.py

It might need more exceptions, but it should be possible to add those in the "exceptions" dict and that's really all there should be to it.
Note that once a user has typed a char, and then the server registers textDocument/completion, then we still won't do completion because of the `self.initialize()` strategy.

Handle all dynamic capabilities

---

plugin/core/sessions.py

The code has triggered exception with LSP-lemminx as "registerOptions"
is optional.

Handle case when registerOptions doesn't exist

---

README.md
plugin/completion.py
plugin/core/edit.py
plugin/core/sessions.py
plugin/edit.py
tests/test_edit.py

If version is provided use that to verify that edit can be applied to
current version of the document.

Ignore edit if textDocument.version doesn't match current view

---

tests/server.py
tests/setup.py

Part of my work on code actions on save where I will need that functionality to popular document diagnostics. Also might be useful for testing $/progress notifications, I imagine.
Allows to trigger any notification from tests.
For example if we want the server to send a 'textDocument/publishDiagnostics'
notification to populate view's diagnostics we'd do:
yield from self.await_client_notification('textDocument/publishDiagnostics', {'params': {}})
On the server side this is a request handler and not a notification handler
as I wanted to be able to await the result so that I would have guarantee
that the notification has been handled when "await_client_notification" call
returned.

Extend test server with $test/sendNotification request handler

---

README.md
docs/index.md
plugin/core/sessions.py
plugin/core/windows.py

This is an enhanced version of PR #902 with support for `window/workDoneProgress/create` from protocol version 3.15.0: [Work Done Progress](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgress).
* `$/progress` notifications are displayed for a short period with Sublime's `status_message(string)` method. Alternatively we could use `set_status(key, value)` for permanent status messages and `erase_status(key)` on notifications with `"kind": "end"`, but i think the former option might be better for very long background processes from the server to avoid unnecessary distraction.
* `cancellable?: boolean;` in `$/progress` notification is ignored because Sublime's UI has no simple cancel button. `window/workDoneProgress/cancel` would be used …

Support window/workDoneProgress and $/progress notifications

---

plugin/core/windows.py

Previous code logged to the active window, but lang server progress should be logged to the window that the lang server belongs to.

Log progress to the window belonging to the Session, not the active window

---

plugin/edit.py
tests/test_code_actions.py

With multiple changes to apply, first change would change view version
and later changes would not longer apply.
I've played myself here before. This really made code-actions-on-save unusable. :)

Check changes to apply against initial view version (change count)

---

plugin/code_actions.py
plugin/color.py
plugin/core/registry.py
plugin/core/sessions.py
plugin/core/windows.py
plugin/formatting.py
tests/test_session.py

- Allow passed capability to be in 'dotted' format like 'textDocumentSync.change'
- Replace some checks to use get_dotted_value to make code more compact
The logic of changed code is not necessarily 100% identical to the old
one (empty dicts will return True now) but I think it shouldn't make
a difference in practice.
This change merges cleanly with st4000-exploration branch also.

Support capability argument for sessions_for_view

---

plugin/core/windows.py
tests/test_windows.py

This allows us to forget about the on_closed callback.
The self._workspace (ProjectFolders class) had a strong reference
to its containing WindowManager.
To check what the referrers are of a Python object, you can do:
import gc
import pprint
pprint.pprint(gc.get_referrers(some_object))

Use a WeakValueDictionary for storing the window managers

---

plugin/completion.py

The anakin-language-server returns `null` for `"details"`. This is not allowed per spec, but we can be a bit more friendly in this case.

Be a little more friendly to non-conforming langservers

---

plugin/completion.py
plugin/core/signature_help.py
plugin/core/views.py
plugin/hover.py
plugin/signature_help.py
tests/test_views.py

Those two, together with documentation for completion items covers all
places where MarkupContent is currently supported.
Resolves #991

Support MarkupContent in function signatures and hover content

---

docs/index.md

Hi, I've added configuration for the Microsoft Python Language Server.
The documentation on the Microsoft website contains partial information, without explanation on how to define the settings object.
Such explanation has been defined here:
https://github.com/sublimelsp/LSP/issues/918#issuecomment-600569260
Cheers,
V.

Add configuration about the Microsoft Python Language Server

---

plugin/color.py
plugin/completion.py
plugin/core/documents.py
plugin/formatting.py
plugin/highlights.py
plugin/hover.py
plugin/signature_help.py

Instead of using the free-standing "is_supported_syntax" function.
(This doesn't fix the performance issue - just cleans up the code to make the fix easier.)

Use LSPViewEventListener.has_supported_syntax consistently

---

plugin/core/configurations.py
plugin/core/registry.py
plugin/core/settings.py
tests/test_configurations.py

is_supported_syntax was called from all view listeners when checking
if listener is applicable. Added caching so that lookup for config
supporting given syntax is only done once per syntax.
Resolves #1057

Fix performance issue related to calling is_supported_syntax a lot

---

docs/features.md
plugin/execute_command.py

As it is now, the `lsp_execute` command is not really usefull if the request arguments require a file URI or other things dependent on current state. This PR expands (actually replaces) the following string arguments:
* `"${file_uri}"` for the file URI of the active view
* `"${offset}"` for the character offset of the (topmost) cursor position
* `"${selection_begin}"` for the character offset of the begin of the (topmost) selection
* `"${selection_end}"` for the character offset of the end of the (topmost) selection
* `"${selection}"` for the the content of the (topmost) selection
* `"${position}"` for Position object (from LSP specs) of the (topmost) cursor position
* `"${range}"` for Range object (from LSP specs) of the (topmost) selection 
In general the `arguments` parameter for the …

Expand variables for workspace/executeCommand request arguments

---

plugin/edit.py
tests/test_code_actions.py

I've noticed that eslint goes crazy and breaks the code on CAOS when there are emojis. This fixes it.

Fix applying code action when content preceded by utf16 char (emoji)

---

plugin/completion.py
stubs/sublime.pyi

There are already tests that check that a dollar-sign is inserted, so no extra test is needed.

Use sublime.COMPLETION_FORMAT_TEXT instead of escaping dollar-signs

---

plugin/completion.py
plugin/core/protocol.py
plugin/core/sessions.py
tests/test_completion.py

```
/**
* Client supports the tag property on a completion item. Clients supporting
* tags have to handle unknown tags gracefully. Clients especially need to
* preserve unknown tags when sending a completion item back to the server in
* a resolve call.
*
* @since 3.15.0
*/
```
The `deprecated` flag on a `CompletionItem` was deprecated in favor of `CompletionItem.tags`. This PR add support for tags.

Support completion item tags

---

README.md

Maybe add some nice badges with links to the license and docs?
And use rounded corners for the Discord badge, so it looks like the other badges too.

Add badges for license and docs to README

---

boot.py
plugin/core/main.py

Since users upgrading to ST4 won't get automatically updated (apparently) to ST4-compatible LSP, we should do something about it or it can become a major hassle.
This is a proof of concept how we could handle it.
It doesn't work as-is, because both ST3 and ST4 versions of LSP use the same `__version__`. We should IMO actually bump `__version__` of ST4 branch a bunch of notches so that we can differentiate them. Then we can implement this solution properly.

Trigger warning for ST4 users that are still using ST3-version of LSP

---

plugin/core/views.py
plugin/hover.py

ST is behaving weird and non-HTML-like when there are spaces within
an anchor. Those should still be part of the link and clickable but
in ST they are not. Work around by replacing spaces with non-breakable
ones.

Fix white space within links not being clickable

---

plugin/code_actions.py
plugin/core/registry.py
plugin/execute_command.py
plugin/formatting.py
plugin/hover.py

Every LSP text command must have an optional `event` parameter in its `run` method.

The context commands are broken due to want_event

---

plugin/core/rpc.py
plugin/core/sessions.py
plugin/core/windows.py
tests/test_session.py

It's more neat to have it like this. The Logger is created in the WindowManager and then passed to the Client, which then doesn't know with what type of Logger it's dealing with.

Dependency inject the logger

---

plugin/core/windows.py

When restoring from session, and making some changes in the document
quickly after plugin initialized but before LSP initialized the server,
we would end up with some accumulated pending buffer changes from
"on_text_changed" listener that we would send after sending "didOpen"
notification. That broke view synchronization as it applied old changes
to the current state of the document send in "didOpen".
Resolves #1096

Fix document synchronization issue when restoring from session

---

Keymaps/Default (Linux).sublime-keymap
Keymaps/Default (OSX).sublime-keymap
Keymaps/Default (Windows).sublime-keymap
LSP.sublime-settings
boot.py
docs/features.md
plugin/code_actions.py
plugin/core/sessions.py
plugin/core/settings.py
plugin/core/types.py
plugin/core/views.py
plugin/formatting.py
plugin/hover.py
tests/server.py
tests/setup.py
tests/test_code_actions.py

A: We are applying all right now. I think it's just fine but haven't seen any servers using `commands` for this functionality.
A: At current state, we're re-applying code actions as long as they make changes in the document, limited by time (2s).
[Code Action Request Spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction)

Implement Code Actions On Save

---

Keymaps/Default (Linux).sublime-keymap
Keymaps/Default (OSX).sublime-keymap
Keymaps/Default (Windows).sublime-keymap
Menus/Context.sublime-menu
README.md
boot.py
plugin/core/sessions.py
plugin/core/views.py
plugin/selection_range.py
plugin/symbols.py
tests/test_mocks.py
tests/test_single_document.py
tests/test_views.py

An LSP alternative to Sublime's own "Expand Selection".

Implement textDocument/selectionRange

---

plugin/core/main.py
plugin/core/sessions.py
plugin/core/settings.py

Then, users have to override settings with "settings".
I tested this with LSP-eslint. I modified Packages/LSP-eslint/LSP-eslint.sublime-settings as follows:
```js
{
"languages": [
{"languageId": "javascriptreact", "document_selector": "source.js.react | source.jsx"},		
{"languageId": "javascript",      "document_selector": "source.js"},
{"languageId": "vue",             "document_selector": "text.html.vue"}
],
"initializationOptions": {},
"default_settings": {
"validate": true,
"packageManager": "npm",
"autoFix": true,
"autoFixOnSave": true,
"options": {},
"run": "onType",
"nodePath": null,
"quiet": false,
"workspaceFolder": null,
"codeAction.disableRuleComment.enable": true,
"codeAction.disableRuleComment.location": "separateLine",
"codeAction.showDocumentation.enable": true
},
}
```
I …

Load "settings" from base file for plugin authors

---

plugin/highlights.py

close #1108 
A mouse-button-release event also triggers on_query_completions(_async).
Whether that should actually happen even if the selection doesn't change is
debatable.

Fix textDocument/documentHighlight getting called twice when using the mouse

---

plugin/color.py
plugin/core/main.py
plugin/core/views.py
tests/test_views.py

By storing the phantomset in the listener instead.
Also separate the parsing and construction of params and the actual
logic in the listener.
The place for parsing payloads is in views.py

Replace a global map of view IDs to phantomset

---

plugin/diagnostics.py

Encountered this issue when using haskell-ide-engine. When there is any error in a file, it sends two diagnostics, one with the actual error and one at the top of the file with a blank message. This caused `splitlines()` to return an empty list so that the `lines[0]` on the next line threw an `IndexError`, preventing any diagnostics from being displayed. I'm not sure why HIE does this, but this commit at least allows SublimeLSP to show the actual errors.

Fix IndexError when diagnostic message string is empty

---

plugin/color.py
plugin/highlights.py

On extending selection "sel().begin()" point does change as it denotes
beginning of selection, not end. So the check that compares current point
with stored point would always be True.
That resulted in trigger many many requests on making a selection as
all debounced request would go through.

Fix debouncing equality check on making selection

---

LSP.sublime-settings
docs/features.md
docs/index.md
docs/troubleshooting.md
plugin/core/rpc.py
plugin/core/settings.py
plugin/core/types.py
plugin/core/windows.py
tests/test_mocks.py
tests/test_session.py

This setting was not used anywhere, instead log_debug controlled logging
in the panel.
Change default to False and make it control the log panel logging.

Make log_server setting work again and remove log_payloads

---

plugin/core/sessions.py
plugin/core/windows.py

closes #1122 
I remember there being an issue with this. Perhaps @predragnikolic or @rchl can comment. If not, we can merge this.

Fix: send initialized notification first

---

messages/4070-unreleased.txt
plugin/code_actions.py
plugin/core/protocol.py
plugin/diagnostics.py
plugin/hover.py
tests/test_code_actions.py
tests/test_protocol.py

Change filter_by_point and filter_by_range to also return an extended
range that includes filtered diagnostics.
This range is then used to request code actions with all filtered
diagnostics included within the range.
Previously the code only included range of the first diagnostics which
wasn't entirely correct and for "range" requests the range was not
extended at all, making those two types of calls inconsistent in number
of code actions returned.
Resolves #1128

Request code actions using range extended to include diagnostics

---

plugin/diagnostics.py

It might happen that the server sends diagnostics with a lowercase drive letter (on Windows OS) for the filename in the `uri` field (e.g. the Julia server does that). Sublimes `view.file_name()` function on the other side returns a uppercase drive letter. Therefore the filenames don't match and diagnostics will only be shown in the panel, but not as regions in the editor or on hover.

Fix diagnostics for lowercase drive letter in DocumentUri

---

plugin/execute_command.py

It's annoying to have a dialog pop up each time `lsp_execute` is run.

Don't show dialog for successful workspace/executeCommand

---

LSP.sublime-settings

This is a common fix type in use so worth having it there to simplify things.

Add "source.organizeImports" example to lsp_code_actions_on_save setting

---

Keymaps/Default (Linux).sublime-keymap
Keymaps/Default (OSX).sublime-keymap
Keymaps/Default (Windows).sublime-keymap
plugin/core/documents.py

The capability check can be done with key "lsp_session_with_capability",
operator "equal", and operand one of the LSP provider names.
You'll have to consult the LSP spec to find the provider names.
I have also formatted our keybinding files with the formatter of vscode-json-language-server. This way I can actually read the text when I have two views side-by-side.
closes #765

Update keybindings with more precise capability checks

---

plugin/core/rpc.py

Deferred notifications were never logged through the loggers. Those were
logged in the log panel through a different code path:
m_window_logMessage -> WindowManager.handle_log_message
but since those didn't pass through the loggers, the remote logger didn't
see those.
I've noticed this while looking at #1145.

Pass the window/logMessage notifications through the loggers

---

plugin/core/rpc.py

Reset error property on SyncRequestStatus on resetting state. Otherwise
the asserts in prepare() would fail on next sync request.
Resolves #1145

Fix sync requests failing after one has errored out

---

plugin/core/sessions.py
plugin/core/windows.py
plugin/documents.py
plugin/session_buffer.py
plugin/session_view.py

SessionView Part II: Attack of the Clones
This solves the clones problem by storing state per session *per buffer* instead of per session *per view*. Multiple views may refer to the same underlying buffer.
After this we can store diagnostics in the SessionBuffer class.

Introduce the SessionBuffer class

---

scripts/release.py

More info: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
Have not tested but hopefully didn't mess up such simple change.

Switch away from deprecated Github API

---

plugin/documents.py
plugin/session_buffer.py
plugin/session_view.py

There's still a small bug left where ST fires a text change event
with all zeroes.
See: https://github.com/sublimelsp/LSP/issues/1015
See: https://github.com/sublimehq/sublime_text/issues/3323

Listen for on_revert and on_reload events

---

plugin/core/main.py

Instead of using sync variant ('on_new_window') where window.folders()
are not yet available, use async one where they seem to be.
Additional use set_timeout to jump on the main thread.
Fixes regression from SessionView task.

Create WindowManager instance from 'on_new_window_async'

---

plugin/edit.py
tests/test_edit.py
tests/test_single_document.py

I couldn't find a way to make view.insert or view.replace to respect tabs. We have to temporarily change view setting.

Fix: respect tabs when applying TextEdits

---

plugin/completion.py
tests/test_completion.py

When "on_query_completions" has been triggered before session has
been initialized (for example on start of ST), then the initialize()
has not seen the session yet and has disabled the completions
for the rest of the session for that file.
Fix by not storing "initialized" or "ready" state and instead handle
"initialize" (renamed to "apply_view_settings") on every request to
"on_query_completions".
To make that work nicely, also fixed issue with "auto_complete_triggers"
values being duplicated. Those values are stored in STs session so after
restarting ST, we would add duplicate entries to that list.
With "apply_view_settings" running on each completion request now that
would become even worse.

Fix completions not being requested from server in some cases

---

LSP.sublime-settings
plugin/core/main.py
plugin/core/panels.py
plugin/core/settings.py
plugin/core/types.py
plugin/core/windows.py
plugin/panels.py
tests/test_server_panel_circular.py

- Don't print param payload if it exceeds 8k chars (can be modified).
- Do debounced logging to improve performance.
- Do not convert to JSON, send it to the plugin host, and then convert
it back into a dict, only to then convert it to a JSON string again.
Instead maintain a queue of log messages to be handled.
This also unclutters the console when investigating commands with
sublime.log_commands(True).
resolves https://github.com/sublimelsp/LSP/issues/1029

Log panel improvements

---

plugin/core/typing.py

We know exactly from which python version "typing" import is available
so no need to try and catch.
This also makes pyright type checker work well with the code base.

Import typing based on version rather than try/except

---

plugin/completion.py
plugin/core/signature_help.py

- The "tags" in a CompletionItem response are null (invalid per spec)
- The "signatures" in a textDocument/signatureHelp response is null (invalid per spec)

Work around broken language servers part II: PowerShellEditorServices

---

docs/index.md

New package does not have all that old had, but syntax highlighting works

Update docs to replace abandoned Dart Package

---

plugin/core/windows.py

This won't help with showing error output when starting the servers
as we can't redirect the stderr output in those cases but it will help
with providing more information when installation of LSP package fails
when executing subprocesses.

Show stderr when server installation fails with CalledProcessError

---

LSP.sublime-settings
plugin/core/settings.py
plugin/core/types.py
plugin/session_buffer.py

This adds the `diagnostics_panel_include_severity_level` setting, which allows the diagnostics shown in the panel to be controlled independently from the ones shown in the code itself, which uses the `show_diagnostics_severity_level` setting.
This seems to be the least complex way to accomplish what I mentioned [on Discord](https://discord.com/channels/280102180189634562/645268178397560865/725710727712604171). While I may want to show hints and info level diagnostics in the code, which can be extremely helpful, I only want the diagnostic panel to be shown when I save a file and there are warning or error level diagnostics that would cause the code to not run. The `auto_show_diagnostics_panel_level` setting helps control when the panel is shown, but since the panel currently shows _all_ …

Add diagnostic panel severity level setting

---

docs/features.md

- Update outdated keybindings explanation
- Update paragraph about "completion resolve docs" by adding a context to check if the AC widget is not visible
- Add missing settings (I'm not sure we even need this overview?)

Update features docs

---

plugin/core/views.py

This does nothing at the moment, but should render `\<` and `\>` correctly once https://github.com/facelessuser/pymdown-extensions/commit/5fca01fa343b67c211ba5a1b51d4b0a40e939ccc is in https://github.com/facelessuser/sublime-pymdownx/tree/master/st3/pymdownx

Use the escapeall markdown extension to handle \< and \> in markdown

---

LSP.sublime-settings
plugin/session_view.py

Also, allow 0 to get the effect of showing no linter results in the view.
Note that the language server will keep publishing diagnostics in the
background, we cannot control that.
Close #858

Fixup: Missing show_diagnostics_severity_level functionality

---

plugin/completion.py

During a resolve request it may happen that the server still returns no docs.
In that case we render "No documentation available" in the popup (in italics).
Close #1074

Print "No documentation available" when there are no docs

---

plugin/core/views.py
stubs/sublime.pyi

- Use clamp_column=True to restrict to the line from an LSP Range
to an ST Region.
- Use the correct rangeLength (in UTF-16) when sending incremental
text sync notifications.

Make use of new ST API goodies since 4075

---

plugin/completion.py

This reverts commit fe1486e95888bae811c9385e61025ac06f4d1b62.
Everyone should have 4075 or higher now.

Revert "Disable DYNAMIC_COMPLETIONS flag for builds older than 4075"

---

LSP.sublime-settings

rust-analyzer is the recommended language server these days.

Remove 'rls' from the default configs

---

plugin/core/collections.py
plugin/core/sessions.py
tests/test_collections.py

Since the purpose of the "on_workspace_configuration" is for plugins to
modify the dict, don't send original dict as plugin can't possibly keep
track of what was modified and remove modifications on next API call.

Pass copy of configuration to on_workspace_configuration

---

plugin/documents.py

The server status is removed from status bar when SessionView is
destroyed but in case server returns error from "initialize" request,
the SessionView is not created yet so teh status bar was left with
status like "LSP-typescript: initialize".
Also TextChangeListener.detach() has threw an exception since we never
called "Session.on_session_initialized_async"

Fix exception and stuck view status when server returns error from initialize

---

plugin/core/windows.py

There will already be a relevant log message earlier in the console if
_ws_server server was failed to be created so there is no need to spam
console with more logs.

Remove unnecessary log message when websocket server is not created

---

plugin/documents.py

if the cursor is moving and it stays in the already highlighted regions,
the highlight won't be cleared.
Before:
After:

[Improved Highlights] don't clear highlight on each cursor move

---

Commands/Default.sublime-commands
boot.py
plugin/core/configurations.py
plugin/core/css.py
plugin/core/windows.py
plugin/tooling.py
sheets.css
stubs/mdpopups.pyi
stubs/sublime.pyi

Opens a sheet with all information that should be necessary to diagnose
problems with a server. Important part of that is that it runs selected
server to catch and show its stderr output. Something that is a pain to
do manually.

Add LSP: Troubleshoot Server to Command Palette

---

LSP.sublime-settings

The suggested configuration with TCP port is problematic:
* It doesn't pass port number to the command and assumes it will use 7658
* It doesn't allow multiple servers running at the same time
* Solargraph is the only server in sample configuration that uses sockets

Ruby server: use stdio instead of socket

---

plugin/core/transports.py

Break out of stderr loop on empty message.
We don't want to break on server returning a newline so check the
contents before doing rstrip() on the message.
This avoids printing some spurious empty messages to the stderr callback.

Don't report empty line to stderr handler

---

tests/setup.py
tests/test_code_actions.py

* Await "textDocument/didSave" to ensure that we only test document
state after "lsp_save" command has done its job.
* Trigger "save" command instead of "lsp_save" on tearing down tests
as there is no point in triggering save actions in that case.

Improve code actions tests stability

---

plugin/core/sessions.py
plugin/core/windows.py
plugin/tooling.py
tests/test_session.py

- The "Manager.on_post_initialize" abstract method replaced with callback as Manager needs to have access to "initiating_view" to reset status also on error.
- Also, call the new callback on failure during "initialize". That was missing, causing the session to not be GC'ed due to missing clearing of self._new_session
- Remove showing of exception in the status bar as those are useless due to disappearing too quickly and having limited space.
- Include exception error in the "crash dialog", if any.
- Allow Troubleshooting disabled configs because when the server crashes it gets disabled and then it's tricky to test why it crashed. Also, print the root scope of the syntax.

Report errors returned from initialize request

---

plugin/documents.py

This makes the highlights show up a lot faster. (I haven't noticed any perf issue with this, but I like how much the highlight feels faster)

Make symbol highlight faster by reducing the debounce time

---

plugin/core/views.py
tests/test_views.py

Close #1280 
Just a heads up: when I set the front matter to
```js
frontmatter = {
"allow_code_wrap": True,
"markdown_extensions": [
{
"pymdownx.escapeall": {
"hardbreak": False,
"nbsp": False
}
},
{
"pymdownx.magiclink": {
"hide_protocol": True,
"repo_url_shortener": True,
"social_url_shortener": True
}
}
]
}
```
magiclinks don't work. Removing `hide_protocol` and `social_url_shortener` from the `pymdownx.magiclink` makes MagicLink work. I don't understand why.

Auto-create links with pymdownx magiclink

---

plugin/core/views.py
tests/test_views.py

Follow-up on #1281. It's a bit more fancy to hide the scheme in magic links.

Hide the scheme in markdown magic links

---

dependencies.json

As preparation for a follow-up PR for #1282, this adds the wcmatch library as another dependency.

Add wcmatch library (for st builds >=4070)

---

boot.py
plugin/completion.py
plugin/core/registry.py
plugin/core/views.py
plugin/documents.py
tests/test_completion.py

- format_completion has been moved to views.py
- completion handling has been moved to DocumentSyncListener
- we can now remove purge_changes_async in LSPViewEventListener
- the (most recent) completions are stored in LspResolveDocsCommand

Merge the last remaining LSPViewEventListener into DocumentSyncHandler

---

Syntaxes/ServerLog.sublime-syntax
boot.py
language-ids.sublime-settings
plugin/core/collections.py
plugin/core/sessions.py
plugin/core/types.py
plugin/core/windows.py
plugin/documents.py
plugin/session_buffer.py
plugin/session_view.py
plugin/tooling.py
sublime-package.json
tests/test_collections.py
tests/test_server_requests.py
tests/test_session.py

Each SessionBuffer has its own capabilities dictionary. This is
to account for dynamic registrations which use a DocumentSelector.
This diff makes OmniSharp somewhat work OK. It is a good example
of a server that registers *all* of its capabilities dynamically,
even textDocumentSync. Because textDocumentSync can be registered
dynamically, we need to account for the possibility of a
SessionBuffer's life starting out without document synchronization,
only to later "obtain" document sync dynamically. This is accounted
for in this diff.
A follow-up pull request will implement the `pattern` requirement
of a DocumentFilter.
This diff also implements the notion of a DocumentSelector. It is
a straightforward translation from the specification. A language server
may register a capability with a …

Capabilities per SessionBuffer

---

plugin/color.py

This allows styling of the color box phantoms from color schemes.
It also sets the default background color to the color scheme's background to prevent an ugly white 0.2em margin on top, in case the background color for `html` or `body` is not set in "phantom_css" (if used).

Add id for color box phantoms [master]

---

plugin/core/sessions.py

Diagnostics were not displays for default preferences, for example,
since those files don't physically exist on disk.
The purpose of the original is_same_file check was to match also files
that different in case of the drive letter but if they match exactly
then we don't have to call it.

Fix diagnostics not being displayed in the view for virtual files

---

plugin/completion.py

This is a follow-up for 8b5454a38435ad33c3008bc4ca96584cd5b389f0 where
the common popups style was applied to the show_popup() call but was
forgotten in update_popup().
Also replaced deprecated "allow_code_wrap" with frontmatter option.

Use common popups styling for the documentation popup

---

plugin/core/registry.py
plugin/documents.py
plugin/formatting.py

We don't need derived classes and base classes now.

Flatten LSPViewEventListener inheritance hierarchy

---

plugin/core/views.py
tests/test_views.py

A plain markdown text (MarkedString) was rendered differently from
MarkupContent for example. For MarkupContent mdpopups would add
a paragraph while for MarkedString, we've only used text2html that
didn't add paragraph.
Checked also hover popups with MarkedString and it renders the same.

Fix MarkedString display in documentation popup

---

plugin/documents.py

I think this was (partially) fixed in 4084. The file_name() is now reliable when checking for it in is_applicable of the TextChangeListener.
There is still the issue of checking whether the view is transient being unreliable.

Check that the view has a filename on-disk when starting the TextChangeListener

---

plugin/color.py

I have introduced a regression in https://github.com/sublimelsp/LSP/commit/32aaa5856e936118a9296035b18f35c2ddc63c65:
The background color from the scheme is still shown on top when the color box phantom is inside a selection.
By using a complete transparent color (alpha value 0) it should work as expected now, both in selected text and when using "phantom_css" in the color scheme.
This should also be applied to the st4000-exploration branch.

Fix color box phantoms background in selections

---

plugin/documents.py

Also, find relevant sessions via the stored session views / buffers
This is more direct than going via the manager.

Fix: manually invoking signature help should not check the triggers

---

plugin/completion.py

Always go through minihtml so that default wrapper element is added.

Fix padding for "no documentation" text in completions info

---

language-ids.sublime-settings

- html: add text.html.ngx for angular files
- shaderlab: these are supposedly Unity Shaderlab files
- r: the R language server can also handle R-flavoured markdown files
- xsl and xml: decouple them
In general, added repo links to thirdparty syntaxes

Update language ID map

---

plugin/core/settings.py

When a plugin was already registered, and then called `register_plugin`
again, we would hit an assertion error. Let's print a debug message
instead so that we can make a smooth transition to explicitly registering
plugins instead of the current way where we register them "immediately"
in _forcefully_register_plugins.

Print a debug message instead of asserting when registering a plugin

---

plugin/core/transports.py

When failing to connect to a language server that is hosting a TCP
server, and when we choose a free TCP port, the error message shows
"Failed to connect on port 0", whereas that should be
"Failed to connect on port ${port}".

Fix: TCP port number is zero in the error message

---

messages/3154-0.12.0.txt
plugin/core/collections.py
plugin/core/configurations.py
plugin/core/sessions.py
plugin/core/settings.py
plugin/core/types.py
plugin/core/windows.py
tests/setup.py
tests/test_configurations.py
tests/test_session.py

The public "read_client_config" API now takes an optional third argument
"base_settings_path" which must be passed by subclasses of LanguageHandler
to properly handle settings merging. It's an opt-in so without it
everything should work as before (no support for merging dotted settings).

Add support for DottedDict

---

plugin/core/windows.py

Try to kill a language server from your process manager app.

Fix: restart a language server after it crashed by doing the registration dance

---

messages/3154-0.12.0.txt
plugin/core/clients.py
plugin/core/configurations.py
plugin/core/handlers.py
plugin/core/registry.py
plugin/core/sessions.py
plugin/core/settings.py
plugin/core/types.py
plugin/core/views.py
plugin/core/windows.py

Adds support for LanguageHandler.additional_variables() classmethod,
to match LSP4 AbstractPlugin API.
Also backports support for expanding variables in "settings",
"initializationOptions" and "command" options. Includes support for
built-in variables "cache_path", "temp_dir" and "home".

Add support for LanguageHandler.additional_variables

---

sublime-package.json

- update LanguageConfig to match LSP3
- update log_stderr to not accept array
- update some allowed and default values
- remove:
* diagnostics_panel_include_severity_level
* lsp_code_actions_on_save
* diagnostics_delay_ms
* diagnostics_additional_delay_auto_complete_ms
* show_code_actions
* log_max_size
- add back:
* complete_all_chars
* completion_hint_type
* log_payloads
* show_code_actions_bulb

Backport sublime-package schema from LSP4

---

LSP.sublime-settings
docs/features.md
plugin/core/types.py
plugin/documents.py
sublime-package.json

Replace "only_show_lsp_completions" with:
- "inhibit_explicit_completions"
- "inhibit_word_completions"
When inhibit_word_completions is enabled, this will also cause LSP
to disable ST's completion ordering and instead use the ordering of
the relevant language server.
Resolves #1166

More granular inhibit completion options

---

Keymaps/Default (Linux).sublime-keymap
Keymaps/Default (OSX).sublime-keymap
Keymaps/Default (Windows).sublime-keymap
plugin/symbols.py

After triggering LSP's "Document Symbols", the user might start typing
the query immediately and if the server response is delayed the query
would end up changing the view. This is a stop-gap solution to avoid
such accidental input until https://github.com/sublimehq/sublime_text/issues/3338
is implemented.
Resolves #1323

Prevent accidental view input after triggering document symbols

---

plugin/core/windows.py

It's nicer to have a common prefix format for all helper plugins. This also means helper plugins don't have to bother with writing out their name for all error messages.

Better 'cannot start' message

---

plugin/completion.py
plugin/execute_command.py

This is VSCode specific behavior that unfortunately CSS language server
(and possibly other) uses.
Also fixes arguments passed to "lsp_execute" as those were not correct.
Resolves #1139

Trigger autocomplete popup on "editor.action.triggerSuggest" command

---

plugin/core/transports.py

Needed for getting SonarLint to work. This language server assumes that the editor is playing the role of a TCP server.
Dug old code up from this commit: f1a53fc45466d008392a17f1c768c26723b14b27
It's a bit simplified with respect to configuration in the following sense:
- We don't start a listener socket on every ethernet device, only localhost.
- In the config, set `tcp_port` to `-1` to start a listener socket with an arbitrary OS-chosen port, or
- set `tcp_port` to `X` where `X < -1` to start a listener socket listening on port `-X`.

Act as a TCP server for langservers that want to connect to the client

---

plugin/code_actions.py
plugin/core/sessions.py
plugin/execute_command.py
tests/test_single_document.py

It's an unfortunate reality that some language servers have elaborate client-specific code. This is a way to handle that.
An `AbstractPlugin` can now define `on_pre_server_command` and intercept a server command. It can then return a Promise to tell the `Session` that it "handled" (or will handle) the command. The `Session` will then not send the command to the server.
Example usage: https://github.com/sublimelsp/LSP-SonarLint/blob/master/src/plugin.py

Allow a plugin to intercept a server command

---

plugin/core/main.py
plugin/core/promise.py
plugin/core/windows.py

The function `open_file` in promises.py returns a Promise that shall be
resolved once the file is fully loaded. It's only safe to call `open_file`
from the main thread because the `on_load` event callback runs on the main
thread.
I want to use this for workspace edits as well as renames.

Add function to open a file asynchronously

---

plugin/code_actions.py
plugin/completion.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/views.py
plugin/documents.py
plugin/execute_command.py
plugin/goto.py
plugin/hover.py
plugin/references.py
plugin/rename.py
plugin/session_view.py
plugin/symbols.py

We can now also show the active requests in the status bar.
It looks a bit frantic without a delay so I've added a delay of 100ms.
As an added bonus the "$test" requests also show up in the tests.

Store inflight requests in SessionView

---

.github/workflows/main.yml
plugin/__init__.py
plugin/core/sessions.py
plugin/core/typing.py

To fix https://github.com/sublimelsp/LSP-eslint/issues/36 I need to have
access to the "languageId" of the file that the server is requesting
configuration for.
~~This changes the "params" object so its schema will no longer match
the LSP spec but then it was nowhere stated that the params passed to
on_workspace_configuration() were matching the spec.~~

Expose language_id on SessionBufferProtocol

---

plugin/core/main.py
plugin/core/windows.py

We don't really know if there were folders added/removed. We also
don't know what settings were changed. Better to be on the safe side and
restart everything. We can always optimize later.

Also restart all servers when the project was saved.

---

plugin/core/logging.py
plugin/core/main.py
plugin/core/types.py

The log_debug setting is now respected when you change it in
the settings. No need to restart ST.
Also removed `set_exception_logging` because it is always on and hence useless.

Improvements for debug logging

---

boot.py

Previously, we created the window managers in the on_init of the global
Listener object, but we might as well do this in the plugin_loaded.
We already remove them in plugin_unloaded.

Create managers on plugin load

---

boot.py
plugin/core/configurations.py
plugin/core/sessions.py
plugin/core/settings.py

Resolves #899 
Helper packages are encouraged to call register_plugin and unregister_plugin
in their plugin_loaded and plugin_unloaded callbacks, respectively.
There is a bug in Sublime Text's `plugin_loaded` callback. When the package is
in the list of `"ignored_packages"` in
Packages/User/Preferences.sublime-settings, and then removed from that list,
the sublime.Settings object has missing keys/values. To circumvent this, we run
the actual registration one tick later. At that point, the settings object is
fully loaded. At least, it seems that way. For more context,
see https://github.com/sublimehq/sublime_text/issues/3379
and https://github.com/sublimehq/sublime_text/issues/2099

Register and unregister plugins properly

---

plugin/session_view.py

This is a follow up PR, based on feedback:
https://github.com/sublimelsp/LSP/pull/1371#discussion_r502964924
Current behavior (that was added with #1371):
DRAW_EMPTY_AS_OVERWRITE:
DRAW_EMPTY:
---
I think the current behavior is ok, but I think that DRAW_EMPTY_AS_OVERWRITE is also ok.
I wouldn't go with DRAW_EMPTY because it is a vertical line.
The only disadvantage about the DRAW_EMPTY_AS_OVERWRITE is that the line in not squiggly, or a box, or whatever the user set in the LSP.sublime-settings file.
Someone could open an issue telling us that they set `"diagnostics_highlight_style": "box",` 
but they still see a line:
- notice the first line - **box**, 
- notice the line bellow `import Url exposing (Url`  - **line**
Feel free to close this PR if you think that the current behavior is ok, …

use DRAW_EMPTY_AS_OVERWRITE for empty regions

---

plugin/core/main.py

Latest version of Package Control is triggering update of packages
on updating to new ST version so there is no point in showing this
message now.

Replace version incompatibility dialog with a console message

---

plugin/core/sessions.py
plugin/core/views.py

* New classmethod for AbstractPlugin: `storage_path()`.
* Extra template string for expansion: `${storage_path}` for use in .sublime-settings commands.

Introduce the storage_path

---

plugin/core/collections.py
plugin/core/types.py

The tests for Config relied on a notion of equality. They implicitly relied
on equality of `id` (memory addresses). But now that we always create a new
Config in the WindowManager whether there is an override or not, this did
not work any longer. To solve this, we define what equality means.

Fix Config tests

---

plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/types.py
plugin/core/windows.py
plugin/core/workspace.py

This is a workaround for a case when user changes workspace folders
manually for which ST provides no notification. We'll just re-read set
folders every time the user starts any server.
Resolves #1374

Re-read workspace folders on starting a server

---

tests/setup.py
tests/test_code_actions.py
tests/test_completion.py
tests/test_single_document.py

The tests run in turbo mode now :) It takes about ~17 seconds to run the ~200 tests. Old time is about ~32 seconds here.
I also removed the `ensure_document_listener_created` method. I don't think this is necessary anymore.

Tests: start and stop session at the TestCase level

---

plugin/documents.py

When I worked on the `_is_in_higlighted_region`,
I assumed that it was safe to not send a document nightlight request while the cursor is in a highlighted region.
Well, my assumptions were wrong.
This PR will send a document nightlight request when the cursor stops moving, 
regardless if the cursor is in a highlighted region or not.

Fix css docment highlight of media queries

---

plugin/documents.py
plugin/goto.py
plugin/references.py
plugin/rename.py

We should rely on the language server doing the smart checks. The is_at_word
function goes against this idea. If the language server decides a request
cannot be fulfilled, we will hear that through its (error) response.

Remove is_at_word function

---

plugin/core/views.py
plugin/documents.py
plugin/session_buffer.py
tests/test_views.py

debounced call was incorrectly running on the sync thread causing potential
race issues when "pending_changes" was modified/checked from different
threads.
Also, made text document version reported in did_change notification
represents document version at the time of the change rather than at the
time of sending the notification. Without it, we sometimes have sent
consecutive notifications with different contents but the same text document
version. Which I imagine servers don't like.

Fix issues with document state getting out of sync when changing and saving

---

plugin/core/message_request_handler.py

MessageActionItem is specified as only containing the "title" property [1].
Yet, vscode-eslint sends an object with "title" and "id" properties and
expects to get that "id" back when user chooses an action.
Since it's not clear what is expected I'm for now changing behavior to
send back original object. This "spec issue" is discussed in more detail at [2].
[1] https://microsoft.github.io/language-server-protocol/specification#window_showMessageRequest
[2] https://github.com/microsoft/language-server-protocol/issues/230

Send back whole action object on choosing action in showMessageRequest

---

LSP.sublime-settings
plugin/core/sessions.py
plugin/core/types.py
plugin/documents.py
plugin/rename.py
plugin/session_buffer.py
plugin/session_view.py
sublime-package.json
tests/test_server_requests.py

The auto_complete_selector is used to fine-tune the behavior of the AC popping
up. This selector is added to an entry of the "auto_complete_triggers" of the
view, alongside the trigger characters advertised by the language server.
When both the selector and at least one trigger matches, the AC is shown.
Note that we have to notify all SessionViews of new capability registrations,
so that they can update their trigger chars.
Resolves #933

New server configuration key: auto_complete_selector

---

LSP.sublime-settings

`hie` and `ghcide` are no longer recommended for Haskell IDE users
https://neilmitchell.blogspot.com/2020/09/dont-use-ghcide-anymore-directly.html

Add deprecation note for haskell-ide-engine

---

docs/index.md

`hie` and `ghcide` are no longer recommended for Haskell IDE users
https://neilmitchell.blogspot.com/2020/09/dont-use-ghcide-anymore-directly.html

Use haskell-language-server

---

.release.json
scripts/release.py

The issue was that PC wouldn't show the release notes due to there being
a prefix. PC would report that it's not a valid SemVer version in the
console.
Fix by not using version prefix in release notes. Only use it for the
git tag and github release name.

Fix issue with release notes not being picked up by PC on update

---

plugin/session_view.py

This was from the time that we didn't use the filterText as the trigger.
I don't think it's necessary to have this anymore. We don't need to
overwrite the user's personal preferences.

Remove the "auto_complete_preserve_order" hack

---

plugin/core/rpc.py

Json loads can throw ValueError if it has trouble parsing the json.

Check for ValueError as well

---

plugin/core/registry.py
plugin/core/windows.py
plugin/hover.py

When there's no ViewListener, the view is not under control of a language
server. So we should not request any textDocument/* requests.
textDocument/hover is the only one where this can happen due to mouse
interaction and transient views during CTRL+P file browsinng.
Fixes #1303

Check for a listener for hover

---

plugin/core/views.py

Two spaces followed by a newline should result in a new paragraph.
mdpopups doesn't parse this because it assumes Daring Fireball Markdown,
but the LSP world seems to converge towards CommonMark (for one thing,
CommonMark is much better specced).
See: https://github.com/facelessuser/sublime-markdown-popups/issues/103

Workaround mdpopups CommonMark deficiency

---

README.md

As with all other languages, this one should also link to client
configuration page. That one also links to the guide.

Link to the client configuration also for C/C++

---

plugin/core/sessions.py

This is only used for completions at the moment. With respect to completions,
the regex flavor is actually Perl, but Perl is a strict *superset* of ECMAScript.
Because the spec only lists one "well-known" flavor, we restrict ourselves to
this subset to achieve maximum compatibility with language servers that may
check for this particular value.
I have intentionally left out the version because:
- I suspect language servers will not check this value rigorously, and
- I don't actually know what version of ECMAScript corresponds to ST's internal
implementation.
See: https://github.com/microsoft/language-server-protocol/commit/d1bfc1014be2b530d85223f2b090c8a0c318eaad
See: https://www.sublimetext.com/docs/completions.html#snippets
See: …

Advertise support for regular expression syntax "ECMAScript"

---

plugin/core/settings.py
plugin/core/types.py

The registration is cleared once the object dies.
I want to use this for LSP-* helper package settings registrations.

Add settings registration class that maintains a registration

---

plugin/core/windows.py

When explicitly logging it should be fine to not trim.

Don't trim messages for remote logger

---

Context.sublime-menu
Default.sublime-keymap
plugin/code_actions.py

Expose a list of source actions that are provided by the servers.
Servers announce support for those through the
"codeActionProvider.codeActionKinds" capability.

Add support for running source actions

---

plugin/core/collections.py
plugin/core/sessions.py
plugin/core/transports.py
plugin/core/types.py
plugin/core/views.py
plugin/core/windows.py
plugin/tooling.py
tests/test_views.py

- on_pre_start: do just-in-time adjustments for the startup info here
- on_post_start: extra callback just in case :)
- ~~on_pre_window_settings~~ on_pre_workspace_configuration: do just-in-time adjustments for the server settings
here
As a bonus there's much better separation between construction of the
jsonrpc transport and resolvement of settings.
Resolves #1373

Add more plugin callbacks

---

plugin/core/sessions.py
plugin/core/settings.py

Fixes #1440
But it doesn't work for example for pyright, because it changes the dev_environment setting in on_settings_read, which is only done once at plugin registration.

Recheck language servers when a settings object changes

---

plugin/execute_command.py

vscode-json-language-server likes to run this when inserting a snippet like `[$1]`, but it doesn't flow very well for ST. Every plugin should decide for themselves whether they want to handle such a command in their `on_pre_server_command` callback.

Don't handle editor.action.triggerSuggest

---

plugin/core/panels.py

I noticed at work that ST is showing its own "definition and references" popup in the find-references output panel. That is not useful.

Don't show ST's internal definitions popup in output panels

---

plugin/rename.py

Trigger the "lsp_symbol_rename" command via a keybinding with LSP-pyright. The popup input has no placeholder, which is supposed to be the original symbol name. 
This PR introduced a guessed symbol name for the placeholder which is better than nothing I think.

fix: renaming input has no placeholder if no "renameProvider.prepareProvider"

---

boot.py

LSP-elixir still depends on this for instance.

Fix: old language handler classes

---

plugin/documents.py

I have removed the following check from `_do_signature_help`:
```python
if not self.view.match_selector(pos, self.view.settings().get("auto_complete_selector") or ""):  # ???	
return
```
To me, signature help should show regardless of whether or not it is in a current `auto_complete_selector` scope. In my particular case I have auto-complete turned off, but still want signature help. I believe these features should be separate.

Allow signature help to show when auto-completion is turned off.

---

language-ids.sublime-settings

Fortran syntax has some selectors that would not convert to the right language id.
See:
https://lsp.readthedocs.io/en/latest/#fortran
This PR should fix it.

Add fortran language id

---

plugin/core/configurations.py
plugin/core/settings.py
plugin/core/types.py

An instance class called "update" should update something on the
instance, one would think, but it has instead created a new instance
of ClientConfig based on the current one.
To avoid confusion, change it to a class method that takes the source
ClientConfig instance.

Make ClientConfig.update a class method to avoid confusion

---

plugin/core/types.py
plugin/core/url.py
tests/test_url.py

This ensures backwards compatibility for the public API, because filename_to_uri
and uri_to_filename are indeed part of the API.

Add an optional ClientConfig argument to filename_to_uri and uri_to_filename

---

docs/index.md

Hello!
I hope you are doing well.
[Sourcegraph's javascript-typescript-langserver](https://github.com/sourcegraph/javascript-typescript-langserver) is unmaintained, this PR removes it from the recommended LSP servers for TypeScript. They mention [Theia's TypeScript & JavaScript Language Server](https://github.com/theia-ide/typescript-language-server) (already in the docs) as a relevant alternative.
Cheers!

Remove Sourcegraph's javascript-typescript-langserver

---

language-ids.sublime-settings

I don't think LeMmInX and vscode-json-language-server actually care about these language IDs (because they only serve one language), but it's good to have them in here anyway.

Add all base scopes from PackageDev

---

plugin/core/sessions.py

I've created this low-level API as it's difficult to otherwise create tailored and yet generic API that is not just to be used for a specific case.
LSP-json would utilize it something like this:
```py
RE_JSONC = re.compile(r'(?:\/package\.json)$')
class LspJSONPlugin(NpmClientHandler, StoreListener):
def on_pre_send_notification_async(self, notification: Notification) -> None:
if notification.method == 'textDocument/didOpen':
text_document = notification.params['textDocument']
if RE_JSONC.search(text_document['uri']):
text_document['languageId'] = 'jsonc'
```

Add Plugin API for overriding requests and notifications

---

plugin/core/sessions.py
tests/test_code_actions.py

VSCode only resolves the `edit` property and no other properties.
Servers like rust-analyzer are now depending on this behavior. For
instance it throws an error response when a client tries to resolve
a missing `command` key.

Fix: do what vscode does

---

plugin/core/types.py
plugin/documents.py
plugin/session_buffer.py

The text changes are buffered and sent after a 500ms timeout, provided that
nothing interesting happens like a trigger character.
The highlights are now sent after a 300ms timeout. This can cause the request
params to contain a document position that doesn't exist from the viewpoint of
the server, because those changes did not yet arrive (they will arrive another
200ms later).
This can be fixed by setting the timeout for highlights to 500ms.
Found in general rust-analyzer debugging.

Fix: document highlights cannot be sent earlier than didChange

---

README.md

Forgot to update the link in the main README.

fix readme docs gif link

---

plugin/core/edit.py
tests/test_edit.py

When parsing documentEdits there's no mention in the protocol that
the textDocument key is unique.

Fix: do not clobber older edits with newer edits

---

plugin/core/protocol.py
plugin/core/signature_help.py
plugin/documents.py
stubs/sublime.pyi
tests/test_signature_help.py

- Proper handling of markdown parameter docs.
- Don't assume that function signatures have an `(` and `)`.
- Put the *active parameter docs* at the top, font-size 1rem.
- Put the *signature docs* under that, font-size 0.9rem.
- Use 0.9rem font-size for the intro message.
- KISS.
close #1001

Rework textDocument/signatureHelp

---

Syntaxes/Diagnostics.sublime-syntax
plugin/core/diagnostics.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/views.py
plugin/core/windows.py
plugin/hover.py

Both in the hover popup, as well as in the diagnostic panel.
The hover popup additionally creates a clickable link if there exists a
codeDescription field with a URL.
I have also freshened up the diagnostics panel. It looks more like
SublimeLinter's panel now.
Resolves #1173
Resolves #1367
Impressions:

Display the diagnostic code

---

plugin/documents.py

Sort the diagnostics by ascending line number.
Before:
```
plugin/configuration.py:
10:32  error   Expected ":" ​Pyright
11:13  error   Expected expression ​Pyright
12:14  error   Expected expression ​Pyright
13:13  error   Unexpected indentation ​Pyright
15:5   error   Unindent not expected ​Pyright
21:1   error   Unindent not expected ​Pyright
13:13  error   "self" is not defined ​Pyright (reportUndefinedVariable)
```
After:
```
plugin/configuration.py:
10:32  error   Expected ":" ​Pyright
11:13  error   Expected expression ​Pyright
12:14  error   Expected expression ​Pyright
13:13  error   "self" is not defined ​Pyright (reportUndefinedVariable)
13:13  error   Unexpected indentation ​Pyright
15:5   error   Unindent not expected ​Pyright
21:1   error   Unindent not expected ​Pyright
```

Sort diagnostics in the diagnostics panel

---

Syntaxes/Diagnostics.sublime-syntax
plugin/core/views.py
plugin/core/windows.py
plugin/documents.py
plugin/session_buffer.py

Untested, but I'll just put it on review while I try to set up eslint :)

Clickable links in the diagnostics panel

---

Syntaxes/Diagnostics.sublime-syntax
plugin/core/diagnostics.py

This PR will make sure the last line `1018:1   error   Invalid type "sublime.TextChange.str" mypy`
is also matched with the line regex. (so the f4 and shift+f4 will work for those lines).
```
plugin/documents.py:
3:2   error   Cannot find module named '.completion' mypy
4:2   error   Cannot find module named '.core.css' mypy
...
1018:1   error   Invalid type "sublime.TextChange.str" mypy
```

fix: diagnostics line regex

---

LSP.sublime-settings
Syntaxes/Diagnostics.sublime-syntax
plugin/core/sessions.py
plugin/core/types.py
plugin/core/windows.py
plugin/session_buffer.py
sublime-package.json
tests/test_session.py

Because the diags panel is never closed automatically, it makes little sense
to have it automatically open whenever there's an error/warning. So the
setting
auto_show_diagnostics_panel
is removed. Instead
auto_show_diagnostics_panel_level
is used to determine when to automatically open the panel *on save*. Put the
value `0` here to never open the panel.
I've also added a neutral "idle" message for when there are no diagnostics.

Never close the diags panel automatically, and more

---

plugin/session_view.py

This used to work, but it was regressed again some time ago. The fix is simple.

Erase diagnostics when the SessionView dies

---

language-ids.sublime-settings

This PR adds all alias scopes of A File Icon, which point to source or text files.
Those aliases are created to attach unique icons to special named files, such as unittests or makefiles. All those alias files either use
text.plain or another scope of a syntax, shipped with Sublime Text.
As all those aliases add a sub-scope to the used base scope, they need to be added to this list here.
**Example:**
All files ending with `.test.js` are scoped `source.js.unittest`.
This commit makes sure to send the correct language id `javascript` to
language-servers.

Add A File Icon alias scopes to language-ids

---

popups.css

Before:
the hr was a solid foreground color.
After:
the hr is an slightly opaque line.

Make <hr> less noticeable in popups

---

plugin/core/open.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/symbols.py
stubs/sublime.pyi
tests/test_document_symbols.py

In this PR:
NEW:
- added deprecated tags to document symbols popup and  symbols in project popup
- symbols in project now looks consistent with the document symbol popup
- added new typed dicts
FIXES:
- This PR also fixes the invocation of the `LspWorkspaceSymbolsCommand` by removing the [fallback value](https://github.com/sublimelsp/LSP/compare/tags-support?expand=1#diff-514c816d75b08e41f44833deaf8e7281295700ce87fdfff07adbd5aabab403c3R240). - The problem is that I trigger the keybinding for `lsp_workspace_symbols` and I expect to see the popup, but no popup is shown. Some people don't experience this problem, but I do experience it on Linux and Mac. A discussion is held on Discord so I will update this PR if we conclude more about that.
Document symbol popup
Symbols in project popup - …

Symbol Tag support

---

docs/src/troubleshooting.md

Add documentation to Troubleshooting section to explain how to solve #1529 and #1530.
@moodmosaic @rwols

Documentation issue1529 issue1530

---

plugin/core/windows.py
plugin/documents.py
plugin/execute_command.py

After some discussion on Discord it seems it's safer to handle vscode-specific commands.
Most notably, now that we don't check if the server is a commandProvider due to handling client-side code lens commands, rust-analyzer will sometimes complain about not understanding workspace/executeCommand. Because it puts the command `editor.action.triggerParameterHints` in one of its completion items.
See: https://github.com/microsoft/language-server-protocol/issues/1148

Handle basic editor commands

---

plugin/code_actions.py
plugin/core/windows.py
plugin/documents.py
plugin/hover.py

Text points are the positions inbetween the characters in the buffer. A region
is a tuple of two text positions. So a region where r.a == r.b never intersects
with another region unless they are the same. Querying for touching points
behaves differently in this regard.
I also renamed `diagnostics_intersecting_point_async` to `diagnostics_touching_point_async`.

Fix #1548: when the region is empty, query touching points

---

plugin/core/registry.py
plugin/execute_command.py

The `self.capability` used to be an empty string, which meant that
the check for `capability is None` was always false when looking up
suitable sessions.
Resolves #1556

Always look up the session name for lsp_execute

---

plugin/code_actions.py

And call the callback when codeActionProvider is disabled.
This fixes more serious issues.
Whether the check for `codeActionProvider` should be implemented at a higher level is another matter.

Fix issue with code action popup re-appearing after selecting item

---

plugin/rename.py
plugin/symbols.py

I don't know if we should wait for the next ST release that will fix this, 
but here is a fix for the `'*InputHandler' object has no attribute 'want_event'` error.

Fix: '*InputHandler' object has no attribute 'want_event'

---

plugin/core/sessions.py
plugin/session_buffer.py

The problem stems from the fact that ST restores regions on Undo so in
a situation when there is a diagnostic shown:
```
let a
^ missing semicolon
```
then semicolon is added:
```
let a;
```
and immediately (before the diagnostic is removed) the document is
changed again by for example adding something before semicolon:
```
let aa;
```
then LSP will remove the diagnostic (region) but pressing undo will
add it back (after the semicolon):
```
let a;
^ missing semi
```
At this point, our logic decides that there are no diagnostics visible and
we've just received empty diagnostics message so we don't need to do
anything while in fact, we do have to remove the region.
Fixes #1218

Fix issue with diagnostics regions sometimes not being removed on undo

---

popups.css

closes #1566 
This PR makes all the font-size of header elements the same as the other text(1rem).
But header elements are bold, which makes them standout just enough from the rest of the text.
Header font size before:
Header font size after:
----
I also reduced the `hr` margin to be consistent with the popup margin spacing (0.5)
Before:
After

Change popup style

---

plugin/core/views.py
tests/test_views.py

When there's a relatedInformation in a diagnostic, we should not start
rendering related infos if the list is empty. clangd sends an empty
list instead of an omitted key.

Fix a tiny html render bug regarding diagnostic.relatedInformation

---

plugin/completion.py
plugin/core/views.py

I can't actually find in the docs what "layout space" is, but from some
experimentation it seems to be the extent of the window minus the sidebar and
minus the minimap.
Resolves #1578

Account for font size for popup width

---

LSP.sublime-settings
docs/src/features.md
plugin/core/protocol.py
plugin/core/types.py
plugin/core/views.py
plugin/documents.py
sublime-package.json

Resolves #1584
I saw that the `markup.error`/`markup.warning`/`markup.info` scopes for diagnostic regions in ST3 got "lost" in #1170 (but they are still used for the diagnostics panel). I would suggest to add them back on top of the `region.*` scopes which are currently used, because the `markup` scopes seemed like a nice semantic description and allow configuration of the styles for diagnostics colors independently of all the other places where `region.*` colors are used in ST.
I could also replace the `text` / `markup.inserted` / `markup.changed` scopes for documentHighlight that are kept for backwards compatibility by one (or separate) `region.*` scopes if desired.
Please checkout my branch and confirm that it actually works before merging this PR, because I haven't.

Replace document_highlight_scopes setting with better default scopes

---

plugin/core/views.py

Move `item.get("detail")` into st_annotation to effectively inline typehints 
Tested so far only with Golang 
References #1549

Move lsp detail into autocomplete annotation 

---

boot.py
stubs/sublime.pyi

Hopefully fix random import errors

---

plugin/hover.py

A tiny improvement. Found during debugging of #1575. Most notably, the
`provider_exists` is called for a few different providers, and each time
we do the same lookup. This is now avoided by remembering with which
listener we are dealing with.

Don't lookup the listener so many times

---

LSP.sublime-settings
plugin/code_actions.py
plugin/core/collections.py
plugin/core/sessions.py
plugin/core/types.py
plugin/documents.py
plugin/session_buffer.py
sublime-package.json
tests/test_configs.py

This adds disabled_capabilities to each client configuration. It is different
from the old disabled_capabilities in that it is now an object instead of an
array. You can disable subsets of functionality.

Add disabled capabilities per client config

---

plugin/core/views.py
tests/test_views.py

Discussion can be found here: https://github.com/facelessuser/sublime-markdown-popups/issues/119

Enable hardbreak in mdpopups to handle escaped newlines

---

plugin/core/sessions.py
plugin/core/types.py
plugin/session_view.py
sublime-package.json
tests/setup.py
tests/test_configs.py
tests/test_server_requests.py

An alternative is using disabled_capabilities.
I've also added more tests for dynamic registration for this.
Dynamic registration went through for disabled capabilities anyway.
But not anymore :)

Remove ignore_server_trigger_chars setting

---

plugin/core/configurations.py

You can now put a client configuration in your .sublime-project that
doesn't live in LSP.sublime-settings and it'll load for that window.

Enable project-only configurations

---

plugin/core/configurations.py
plugin/core/windows.py

Putting a configuration into a temporarily disabled state has the major drawback that you can't enable it anymore, unless you close the window and re-open the window.
Instead, disable a failing config via the settings machinery. This way you can enable it again by clicking on Tools > LSP > Enable Language Server In Project.

Remove temp disabled config logic

---

plugin/code_actions.py
plugin/hover.py

Display the code action in a quick panel instead of the context menu, this makes us able to use more keybindings to control which code action we want to use.
With the context menu you're only able to select an item with `up/down arrows` or the mouse, with a quick panel you can add custom keybindings and also use the search feature of the quick panel.

feat(code actions): display code actions within a quick panel 

---

Syntaxes/Diagnostics.sublime-syntax
Syntaxes/References.sublime-syntax

Some small tweaks for the scopes used in the diagnostics and references (rename) panels:
* `entity.name.filename` for the filenames (already used in Find in
Files results panel and by SublimeLinter)
* `constant.numeric.line-number` for line numbers (already used in Find
in Files results panel and by SublimeLinter)
* `constant.numeric.col-number` for column numbers (already used by
SublimeLinter and seems to be a suitable scope name)
*Note*: this will change the color in Mariana for filenames in the diagnostics panel form green (string) to orange (entity.name), which may look a little bit worse than before, but I think it's more desirable to have a consistent style over different panels and with the built-in Find Results panel. And the Monokai scheme has a rule for `entity.name.filename`, …

Make scopes in output panels consistent with Find results panel

---

LSP.sublime-settings
docs/src/features.md
docs/src/guides/client_configuration.md
docs/src/troubleshooting.md
plugin/core/types.py
plugin/core/windows.py
sublime-package.json

Remove `log_stderr` in favor of always logging errors to the log panel.

Remove "log_stderr" in favor of always logging errors to the log panel

---

plugin/session_view.py

The specific case is:
- a region for "unnecessary" code is created
- there are also other unrelated diagnostics with same severity
- the "unnecessary" code starts being used
- we enter the "elif ((severity <= userprefs().show_diagnostics_severity_level)..."
branch and we don't remove the "unnecessary" region because there
are other diagnostics with same severity
Fix by always removing tag regions at the beginning of the loop.

Fix case where tag regions would not get removed

---

plugin/core/windows.py

Otherwise the instructions might be drowned out by the error message
on macOS especially due to the small error dialogs.

Put instructions at the top when langserver gets disabled

---

plugin/documents.py

Fixes #1622
The `sessions()` method returns a generator object, which causes the query for `if not sessions` to always return false. As a result the whole promise machinery is running even if no session is available.
This commit therefore queries `completion_promises` instead, to shorten the route in case of no sessions being available.

Fix null session completions

---

docs/src/lsp_implementation_status.md

Using 4 spaces instead of 2 for each indentation level works.

Fix indentation in LSP implementation status docs

---

Default.sublime-commands

Hello, thank you for your work on LSP.
I noticed "Find references" was in the context menu but not in the commands list so I thought I would add it.
Seems to work on my Mac OS X using ST4 build 4099:

Add Find References to commands list

---

boot.py
plugin/core/panels.py
plugin/core/windows.py
tests/test_server_panel_circular.py

Avoid inserting text and parsing the syntax when the panel is closed
which can be expensive if there is a lot of output.
The debouncing logic is removed as there should be no need to delay
anything when the panel is opened.
Fixes #1626

Update server log panel only when it's opened

---

docs/src/index.md

- Remove mention of "LSP: Enable Language Server Globally" as setup
instructions enable them globally already and it doesn't apply to
LSP-* packages either.
- Don't mention the "PATH" as it doesn't apply to LSP-* packages.
Instead add a generic sentence linking to troubleshooting section.
- Remove links to LSP-* packages since it's redundant given that the
list of language servers already includes them and categorized by
programming language.

docs: improve getting-started instructions

---

plugin/core/sessions.py

Noticed that the plugin instance is not unreferenced on crash and thus is never destroyed.

Ensure that plugin instance is also destroyed on crash

---

plugin/core/sessions.py

I have a local implementation of `didChangeWatchedFiles` that I need those APIs for.
- `on_register_capability_async` to be able to handle `workspace.didChangeWatchedFiles` capability that can specify `watchers` to set up.
- `on_unregister_capability_async` to unregister them
- `on_session_end_async` to unregister watchers when session ends.
I have implemented `didChangeWatchedFiles` in `lsp_utils` but not sure if I want to upstream it. It depends on `node` and I'm not sure I have finished it (have done it some time ago and just kept using it as it works ;)). With that in mind, I'm fine with the decision not to integrate this API but if it makes sense in general and doesn't hurt then why not.

Add plugin APIs: "on_*_capability" and "on_session_end"

---

docs/src/language_servers.md

Palantir is no longer maintaining the project. It has been forked and taken up by a new group.
The final link to the complete options list will need to be updated when the new group determines their chosen documentation path. 
https://github.com/python-lsp/python-lsp-server/issues/24
The existing link should suffice for now since currently, the project is a drop-in replacement.

Change to pylsp vs pyls

---

plugin/core/transports.py

This avoids a redundant try-except.

Check if the process has already stopped

---

plugin/edit.py
tests/test_single_document.py

This fixes an issue for import edits for the FsAutoComplete server.
See: https://github.com/fsharp/FsAutoComplete/commit/48129a5ccbf1c76fe29a5ac26eeb5d1d34975a89
Co-authored-by: chendesheng

Account for out-of-bounds columnn offsets of text edits

---

docs/src/troubleshooting.md

- structure the information better
- mention where and how the logging information can be seen
- mention "troubleshooting" command

Improve self-help instructions

---

docs/src/customization.md
plugin/documents.py

This are some of the changes from the closed PR #1663 which make color scheme authors (and possibly users) happier. It affects only the colors, so there shouldn't be any unintended side affects like strange bounding box behavior on hover or so.
Short explanation regarding the scopes:
- The `markup.changed` which was previously used for the lightbulb icon is semantically incorrect and could be any color in theory. The scope `lightbulb` (can be used for potential color adjustments) on top of `region.yellowish` isn't probably used in any scheme, but that scope is comparable to the scopes `bookmarks` and `mark` which are used for the gutter icons by the internal "Goto > Bookmarks" and "Edit > Mark" features.
- If anyone used the former `markup.codelens.accent` scope for a color customization, …

Small tweaks for annotations and lightbulb colors

---

plugin/core/windows.py
plugin/documents.py

This fixes an edge case where registering the listener to the window manager could be "too late" because the window/view was already closed on the main thread.
```
File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 863, in on_load_async
run_view_callbacks('on_load_async', view_id)
File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 714, in run_view_callbacks
callback(*args)
File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 190, in exception_handler
return event_handler(*args)
File "C:\Users\mitranim\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/documents.py", line 327, in on_load_async
self._register_async()
File "C:\Users\mitranim\AppData\Roaming\Sublime …
```

Fix: do not ignore return types

---

plugin/tooling.py

The "contributes.configuration" can be a list of objects as defined in
the schema [1] and done in css language server [2].
Also increased wrap width from ~80 to ~100 as the previous value seemed
a little narrow.
[1] https://github.com/microsoft/vscode/blob/c351b396cacdfd5bcbeec6ad89a2890cbdae9263/src/vs/workbench/api/common/configurationExtensionPoint.ts#L133-L146
[2] https://raw.githubusercontent.com/microsoft/vscode/main/extensions/css-language-features/package.json

Support list type when parsing contributes.configuration

---

plugin/hover.py

VSCode assumes the fragment is a 1-based row offset so we'll assume that too.

Handle 'file:' URIs in hover content

---

plugin/code_actions.py
plugin/documents.py

If  only one option, display the `code action` method to reduce unnecessary operations

Improve `code action` op

---

plugin/code_actions.py
plugin/formatting.py
plugin/save_command.py

I'm doing a little bit of cleanup and enhancement to allow SaveTasks to call `LspTextCommand.best_session` since I want to consolidate some code later and fix #1684.
I can do further changes as separate commits or separate PR. I didn't want to just throw all together as it would be hard to review.
This change should have no functional changes.
It does switch from global `sessions_for_view` function to `LspTextCommand.best_session` but I believe this should have no behavior changes? Or if it does then only for the better? I forgot what's the difference between those exactly but I believe the latter is preferred and works correctly in more cases?

Expose access to LspTextCommand from SaveTasks

---

LSP.sublime-settings
plugin/core/types.py
plugin/core/views.py
sublime-package.json

Allow adjustable extents of the popups

---

plugin/core/types.py

The TransportConfig checks this invariant now.
In practise this means the user is presented with a clearer error.
Fixes #1564.

Raise an exception when neither "command" nor "tcp_port" is given

---

plugin/core/transports.py
tests/test_protocol.py

This makes the flow language server not crash with non-ascii characters.
However, inserting an emoji, and then removing that emoji brings flow into an
invalid state. It seems to be because when the emoji is removed, that counts
as two UTF-16 characters.

Don't ascii-escape Unicode

---

docs/src/language_servers.md

Maybe we should have a helper package for diagnostic-languageserver but
for now it's good to have this at least.

Add instructions for shellcheck

---

docs/src/language_servers.md

This avoids starting it for fish https://github.com/Phidica/sublime-fish/blob/6697fdd7becc3e5991484d4365b036b9fbb1d99d/fish.sublime-syntax#L8

shellcheck works only for bash

---

plugin/core/sessions.py
plugin/session_view.py

Apply all permanent status messages that were set via `Session.set_window_status_async` when a file is opened.
I'm not sure why, but this also fixes an issue I saw, that `set_window_status_async` has no effect when called within `AbstractPlugin.__init__`.
Note that the `set_window_status_async` method ignores the "show_view_status" setting, but it seems much more useful to me this way, because plugin authors could add their own setting for this (or query the "show_view_status" setting from the LSP preferences) and then check that before calling `set_window_status_async`.

Apply all status messages when a SessionView is opened

---

plugin/hover.py

1. If only one, If the action link is clicked, it is ran immediately, circumventing the quick panel.
2. If only diagnostics, don't show navigation
3. Improved hover phantom problem
BTW, When hovering, the `code action` does not just occur during the diagnosis

Improve hover `code actions` UX

---

LSP.sublime-settings
plugin/core/types.py
plugin/documents.py
sublime-package.json

Related: #1710
I've removed the "squiggly", "dotted" and "box" options for single-line highlights. "fill" and "underline" are possible. When set to "fill", "fill" is used for multi-line as well.

Use box-style for multiline doc highlights

---

LSP.sublime-settings
plugin/core/types.py
plugin/hover.py
sublime-package.json

if the `"show_code_actions": ""` then code action also shouldn't show in the hover

Hover code action show remains consistent

---

plugin/hover.py

... when used in Markdown link destinations in hover popups.
Resulting from the discussion in #1711.
I've only tested on Windows.

Handle percent-encoding and leading slash in file URIs

---

plugin/documents.py

This old and incorrect version of the code somehow got merged after
being reverted and re-submitted.

Fix crash on showing code actions

---

LSP.sublime-settings
docs/src/customization.md
plugin/core/sessions.py
plugin/core/types.py
plugin/core/views.py
plugin/documents.py
plugin/session_buffer.py
plugin/session_view.py
sublime-package.json
tests/test_server_notifications.py

If the diagnostic spans one line:
- Draw errors and warnings as squigglies
- Draw infos and hints as stippled
If the diagnostic spans more than one line: always draw as a box.
The diagnostics_highlight_style setting is removed, as these provide good
defaults.
Resolves #1547
Infos and hints as stippled:
Warnings and errors as squigglies:
If more than one line: always a box
cc @deathaxe, @kornelski

Refine diagnostics presentation

---

plugin/tooling.py

With this fix the tooling command for generating a schema is fixed. As discussed in the discord server!. Just adds a few is-instance checks!

Fix the `LSP Development` command

---

LSP.sublime-settings
plugin/code_actions.py
plugin/core/types.py
plugin/save_command.py
sublime-package.json

Rename the setting and make it apply to all save tasks.
Resolved #1719

Rename code_action_on_save_timeout_ms to on_save_task_timeout_ms

---

plugin/references.py

os.path.relpath may throw an exception on Windows

---

plugin/code_actions.py
plugin/core/registry.py
plugin/core/windows.py
plugin/documents.py
plugin/hover.py

Just a tiny refactor to include the _async suffix and add
a "sessions_async" API to listener for parity.

Use "_async" suffix in listener APIs

---

LSP.sublime-settings
plugin/core/types.py
sublime-package.json

Because it is requested in #1712 by multiple users and there is already the setting for it, so I think it doesn't hurt to keep this option.

Add back stippled option for document highlights

---

boot.py
plugin/code_lens.py
plugin/core/sessions.py
plugin/core/windows.py
plugin/documents.py
plugin/session_view.py

This changes the following:
* Code lens state is stored in its own class
* Code lenses are moved to SessionView instead of DocumentSyncListener
* The code lens debounce time is lowered to 300ms from 2300ms
I'm aware this is a big change. The development was discussed in the Discord server in preparation of allowing to render code lenses as phantoms. As a result the PR for that one is blocked until this one is finalised since it depends on the refactoring done here.
I tried my best to separate the code that dealt with the phantom representation but some of the data changes might still linger and seem bizarre.

Refactor code lenses

---

plugin/session_view.py

Happens with LSP-PowerShellEditorServices for instance.

Prevent infinite loop when server returns empty code lenses

---

plugin/documents.py

Useful for helper packages like LSP-rust-analyzer. Related: https://github.com/sublimelsp/LSP-rust-analyzer/pull/14

New key binding context: lsp.session_with_name

---

plugin/session_view.py

Instead of the name. The config name caused weird behavior when
using the hover functionality. The text command of hover keeps the
session buffers alive. This ensures new session buffers are created
when doing a LSP: Restart Server.

Index SessionBuffer weak value dictionary by id(session)

---

plugin/code_lens.py
plugin/session_view.py

This is an extended fix related to #1759. The original intent of the code was to allow code lenses to be filled without resorting to
reopening the file. However, the naive implementation caused an infinite loop so it requires a separate sentinel value to differentiate between an actual empty request vs an uninitialised request.

Send a code lens request if one hasn't been sent yet

---

boot.py

Otherwise LSP will attempt to register intermediary classes like
NpmClientHandler and throw an error.

Ignore plugin classes that don't return name()

---

plugin/core/url.py
tests/test_url.py

This fixes a bug with wrong labels for quick panel items after "Find References" and "Goto Definition..." if the server returns filepaths with lowercase drive letter, and also for Sublime's VCS status in the status bar when such a file link is opened.
Closes #1770.

Normalize drive letter in Windows filepaths to uppercase

---

plugin/core/sessions.py

candidate_isfile is not a bool but a str.
Also protect against bad server URIs.
For instance pyright translates
res://Packages/symbol.py
to
file:///Packages/symbol.py
Fixes #1774

Fix file comparisons

---

LSP.sublime-settings
plugin/code_lens.py
plugin/core/types.py
plugin/session_view.py
sublime-package.json

This also adds a setting to disable the rendering entirely.
In order to satisfy those who like their code lenses as an annotation I kept the setting as-is rather than replacing them. I did change the default setting to use a phantom since that representation is probably more common for those coming from VSCode.
I've tested this code and it works, but I'm unsure if there are any state related bugs. One thing I noticed is that the code lenses only show up when the file is reopened. This felt undesirable to me, however I did not know where exactly to fix it. In a normal plugin lifecycle I would hook into `on_load_async`, `on_activated_async`, and (potentially) `on_post_save_async`. There was the `_register_async` helper function which would have felt like an appropriate place to send the …

Add setting to render code lenses as a phantom

---

plugin/__init__.py
plugin/core/file_watcher.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/types.py
plugin/session_view.py
stubs/sublime.pyi
sublime-package.json
tests/setup.py
tests/test_file_watcher.py

Allows to create external package that implements the file watcher API.
See example implementation at https://github.com/sublimelsp/LSP-file-watcher-chokidar/pull/1

Add API for registering an external file watcher implementation

---

plugin/documents.py

This fixes a bug where the deno language server wouldn't attach to buffers with
a `deno` URI scheme.

Fix: should reset when uri changes via settings()

---

plugin/code_lens.py

I installed LSP-jdtls and dug out an old Java project to try out the new code lens phantoms, and saw that I could not target them specifically to adjust their style. Fixed it now.
Example with `"phantom_css": "html{background-color:transparent;color:var(--foreground)}a{color:var(--bluish)}#lsp-code-lens a{color:color(var(--foreground) alpha(0.5));text-decoration: none}",` in Mariana:
***
By the way, there is still a bug (and error in the console) with file URIs to filepaths conversion when I click on the phantom (or annotation). The normal references request e.g. via the context menu works. I will look into that later.

Allow styling of code lens phantoms

---

plugin/core/sessions.py
plugin/session_buffer.py
plugin/session_view.py
stubs/sublime.pyi
tests/test_single_document.py
unittesting.json

This doesn't actually work correctly for session buffers that get a different
session attached to them. For example, when you open a remote JSON schema with
the yaml-language-server, then the vscode-json-language-server is attached to
that virtual view. In that case this code fails.
We should instead have something like a per-window iteration over all session
buffers for all session. But this works okay for now for e.g. deno.
https://user-images.githubusercontent.com/2431823/124381676-0e817d00-dcc4-11eb-8271-1136b39835ba.mov

Open existing views with custom URIs

---

boot.py
plugin/core/windows.py

Related: https://github.com/sublimelsp/LSP-jdtls/pull/15
Related: https://github.com/daveleroy/sublime_debugger/pull/106

Allow third-party packages to open abstract URIs as well

---

plugin/core/sessions.py

If the paths compare equal as strings, then we consider this a match, *even* if
the candidate file does not actually exist on-disk. This catches a case where
you delete a file on the file system but you have a view of it open in
Sublime Text. There is no callback in the API for that. And even so,
view.file_name() will still return the (now non-existing) file name.

Even more fixes for matching up buffers with URIs

---

plugin/session_view.py

Draw the diagnostics underlines in the view regardless if we set "diagnostics_gutter_marker" is set to "".
Closes #1783

Draw diagnostic underlines when "diagnostics_gutter_marker" is set to ""

---

docs/src/language_servers.md

As stated in https://github.com/Cloudstek/LSP-serenata/issues/1#issuecomment-851055572
Until LSP-serenata supports ST4 I think the only client for PHP is LSP-intelephense

LSP-Serenata doesn't support ST4

---

plugin/core/transports.py

It complained about this:
```
plugin\core\transports.py:256: error: Incompatible types in assignment (expression has type "None", variable has type "STARTUPINFO")
```

Fix mypy type issue on windows

---

docs/src/guides/client_configuration.md

Add a note about external helper packages as otherwise users might get
confused thinking that they have to create client configurations for
those also.
Also updated a couple of places for clarity and added documentation for
"disabled_capabilities".

Update client configuration documentation

---

docs/src/customization.md
docs/src/features.md

Moved the keyboard and mouse configuration documentation to the `Customization` section and refactored.

Improve keyboard shortcuts documentation

---

plugin/core/windows.py
plugin/documents.py
plugin/hover.py

This change also affects what is shown in the status bar with "show_diagnostics_in_view_status" enabled.
I don't think it would make sense to have yet another setting specifically for the hover popup and status bar.
I've tried to make test for it but we don't have ability to override or mock the global LSP settings per-test so I couldn't find a way to test it.
Fixes #1797

Make hover popup also follow the show_diagnostics_severity_level setting

---

docs/src/troubleshooting.md

- common problems moved to the beginning
- common problems rewritten to be more concise, remove repetition
- in "Completions not shown after certain keywords" removed note about python completion inhibiting issue as that is fixed
- other small changes that are hard to summarize

Rewrite / reorganize the troubleshooting documentation

---

plugin/documents.py

This fixes a regression where previously a langserver would attach to a scratch
buffer once it was saved to disk. That functionality got lost in the URI
refactorings.

Re-evaluate what langservers to attach when the URI scheme changes

---

plugin/core/sessions.py
plugin/core/transports.py
plugin/core/windows.py

Remember the cwd for plugins

---

plugin/core/types.py
sublime-package.json
tests/test_configs.py

The lists are joined into a string with the native file system's path
separator.
Resolves #1811

Allow lists in `env` dict of client configuration

---

plugin/__init__.py
plugin/core/sessions.py
plugin/core/types.py
plugin/core/windows.py
tests/test_session.py

- When the file is outside the window folders, ignore diagnostics
- When the file matches binary_exclude_patterns, ignore it
- When the file matches file_exclude_patterns, ignore it
- When the file matches folder_exclude_patterns, ignore it
This doesn't take care of the index_exclude_patterns and
index_exclude_gitignore settings.
Resolves #1727

Discard diagnostics in a few cases

---

plugin/core/panels.py

This prevents memory growing infinitely due to Sublime Text maintaining an
infinite undo stack, even for panels.

Always clear undo stack after a mutation on any panel

---

plugin/completion.py
plugin/core/sessions.py
tests/test_completion.py

This advertises that we only support "adjust indentation"-style completions.
When a completion contains a newline, say `a\nb`, then the question becomes whether the language server should account for the current indentation the cursor is at, or whether the editor should take care of that. For this package the editor takes care of that.
While adding this property in the client capabilities I discovered that we actually had an inconsistency with this. In the case of a plaintext textEdit, we did in fact not account for indentation level. This is now fixed as well in 0b1d6d3. The two commits can be rebased as-is.

Take care of InsertTextMode for completions

---

plugin/code_lens.py
plugin/session_view.py

This makes the annotation style a bit less janky.

Make code lenses have the same behavior for both variants

---

plugin/core/protocol.py
plugin/core/views.py
plugin/hover.py

closes #https://github.com/sublimelsp/LSP-tailwindcss/issues/19
Currently LSP sends only one hover request, which doesn't work nicely when there are multiple sessions running in a file.
LSP should send hover requests to all sessions that supports the `hoverProvider`.(like we do when requesting completions)

Send hover request to all sessions that supports hoverProvider

---

plugin/core/transports.py

The logic seemed to be backwards. The poll() will return an exit code
if the process has already exited and "None" otherwise. So we want to
kill the process when the value is "None".

Ensure the process is killed if it didn't exit within 1 second

---

plugin/save_command.py

Fixes #1791.
Not sure if it is a proper fix, but the logic to determine whether the keybinding is active or not, is already present in documents.py/on_query_context(). Otherwise, the `is_enabled` evaluating to False from LspTextCommand resulted in preventing <kbd>Ctrl</kbd>+<kbd>S</kbd> from doing anything, because that binding was active, but not actually run.
I would assume that the code actions on save still won't work in the case described in #1791, but I haven't tested it.

Ensure lsp_save actually runs when context is active for keybinding

---

dependencies.json

As mdpopups vendors all required libraries as of 4.2.1 its dependencies can be removed.

Remove obsolete dependencies

---

plugin/documents.py

When triggering the documentation popup and when there are multiple sessions in the file.
Trying to resolve the completion item will fail for one session:
**Why?**
Because the resolve request is send to the wrong session.
If you put a print statement in `_on_all_settled`, 
```
for response, session_name in responses:
print('session_name', session_name)
```
I expected to see:
```
session_name LSP-tailwindcss
session_name LSP-volar
```
But currently it logs:
```
session_name LSP-tailwindcss
session_name LSP-tailwindcss
```
----
This PR will introduce the correct behavior.

use config_name, because session.config.name can change

---

plugin/core/transports.py
tests/test_protocol.py

Extracted the JSON RPC-specific handling into a separate processor
and used composition concept to pass and use it within the transport.
That should allow re-using the transport implementation in the file
watcher to implement a transport that uses plain lines of text rather
than JSON RPC.
Not using abstract classes anymore as that is not compatible with
generic types.

Generalize implementation of the transport

---

plugin/core/file_watcher.py
plugin/core/sessions.py
plugin/core/types.py
sublime-package.json
tests/test_file_watcher.py

I've realized that supporting only one pattern doesn't allow to handle the use-case of eslint which needs three patterns that are not possible to handle with a single pattern and braces:
- `**/.eslintr{c.js,c.yaml,c.yml,c,c.json}`
- `**/.eslintignore`
- `**/package.json`

Support multiple patterns in file_watcher client configuration

---

plugin/core/collections.py
tests/test_collections.py

Don't allow old nested dict style keys anymore

---

plugin/code_lens.py
plugin/session_view.py

Also show the error text when resolving code lens fails.
We could also make the code lens text red when resolving fails but not sure it's worth it for that corner case.
Fixes #1886

Don't resolve code lenses if server doesn't support resolving

---

plugin/configuration.py
plugin/core/configurations.py
plugin/core/registry.py
plugin/core/settings.py
plugin/core/windows.py

Ensure that only the server who's settings were saved is restarted.
This of course only addresses changes in LSP-* settings, not
client settings within the main LSP settings.
Also consolidated almost identical `WindowManager._end_sessions_async`
and `WindowManager.end_config_sessions_async` into one.

Don't restart all servers on changing LSP-* plugin settings

---

Default.sublime-keymap

This is a Window command so this context check does not work (always matches).

Remove unused context in "goto definition" keybindings

---

plugin/code_actions.py
plugin/documents.py
tests/test_code_actions.py

Some servers might apply different logic depending on provided
diagnostics. For example theia server might not want to apply
destructive action like removing import statements when there are
error diagnostics.
While testing this new logic, uncovered a bug where we didn't include
diagnostics "touching" the selection region which also affected the
case when getting diagnostics for the whole document range on save,
which didn't include diagnostics that were at the end of the document.

Include diagnostics when triggering codeAction request on save

---

plugin/documents.py
plugin/session_buffer.py
unittesting.json

As was noticed in https://github.com/sublimelsp/LSP/pull/1839#discussion_r750288905, it was incorrect to use `_when_selection_remains_stable_async` for the features that relied on view changes being reported first.
The `_when_selection_remains_stable_async` would cause the request to be skipped if the selection has changed since it was called. That means that changing the document and then quickly moving the cursor would result in color boxes not being requested/updated.
And on top of that, we might have also requested color boxes before the `didChange` notification has been triggered thus resulting in out of sync positioning of boxes.
Moved the logic to `SessionBuffer` where it can be called after the `didChange` notification and added checks if view is still alive and whether the …

Fix color boxes not updating in some cases

---

plugin/documents.py
plugin/session_buffer.py
plugin/session_view.py

The status fields for indicating that the server is running would sometimes not be shown. This has happened randomly when sessions were initializing.
The issue was that the [view settings listener](https://github.com/sublimelsp/LSP/blob/a8e67857126b2c9914d556850ebfc32526f650c6/plugin/documents.py#L161-L161) set up in `DocumentViewListener` would always trigger initially since we didn't initialize `self._current_syntax` from `__init__` so the [check if something has changed](https://github.com/sublimelsp/LSP/blob/a8e67857126b2c9914d556850ebfc32526f650c6/plugin/documents.py#L786-L788) would evaluate to `True` and call `self._reset()`.
At the point the `self._reset()` is called the `SessionViews` might already have been created (and in fact almost always are since the settings change is …

Fix LSP status field missing randomly

---

plugin/core/protocol.py
plugin/core/views.py
plugin/hover.py

This relies on `experimental.rangeHoverProvider` which so far only Metals implement. But this workaround would be removed once https://github.com/microsoft/language-server-protocol/issues/377 is part of the LSP specification.
Fixes https://github.com/scalameta/metals-sublime/issues/44

Send range with textDocument/hover when possible

---

plugin/core/configurations.py
plugin/core/settings.py

Don't pass the config name since that results in the listener (WindowConfigManager.update) not clearing the registered configs. On removing a config we should not pass a name.
Fixes #1905

fix crash loop on disabling helper package of a running server

---

plugin/core/registry.py
plugin/core/sessions.py
plugin/core/windows.py
plugin/documents.py
plugin/hover.py
plugin/session_buffer.py
plugin/session_view.py
plugin/tooling.py

Fixes types for pyright in cases like below where we've blatantly lied about types.
The way it was done before, apart from causing type issues with Pyright, allowed users to just access `session_view.session_buffer` from `Session`, for example, and get away with accessing anything on `SessionBuffer` because the type was `Any`.
@jwortmann sorry to cause troubles for you again. I don't mean bad. :)

fix types for protocols to add type safety

---

plugin/core/sessions.py

https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#codeLens_refresh

Handle Code Lens Refresh Request

---

plugin/semantic_highlighting.py

It is the same bug and fix as #1852.
I think the actual underlying bug is in the ST API, because https://github.com/sublimelsp/LSP/blob/f1e96dcc67b1351c409e145dcb338c458977db02/boot.py#L202 is only called when a view is dragged between two existing windows (or inside a single window), but not when it is dragged to a *new* window. I've tested and verified this with a few print statements.
With this API bug, the WindowRegistry doesn't get to know the new window ID, and therefore https://github.com/sublimelsp/LSP/blob/f1e96dcc67b1351c409e145dcb338c458977db02/plugin/core/registry.py#L76 doesn't work, which is called by `LspTextCommand.is_enabled()`, which then will return `False`.

Fix lsp_show_scope_name command not working if view was dragged to a new window

---

boot.py
plugin/save_command.py
plugin/semantic_highlighting.py

This is a workaround for the following ST bug: https://github.com/sublimehq/sublime_text/issues/4630
With this change, LspTextCommands still work after a tab is dragged out of a window to create a new window. For example lsp_hover will work again in such a case :)
The 1ms delay appears to be sufficient, so that this check still works:
https://github.com/sublimelsp/LSP/blob/19a01aa045de04bcc805e56043923656548050e0/plugin/documents.py#L205

Ensure view gets registered when tab is moved to create new window

---

plugin/documents.py
plugin/session_view.py
tests/test_code_actions.py

I must say I can't make any sense of the logic behind ST's region draw priority. For the inline decorations (underline, background), the regions which were initialized *last* end up on top, while the displayed icon is chosen from the regions, which were initialized *first*.
Whatever, this seems to work reliably for me now.

Ensure code actions lightbulb icon is on top

---

plugin/core/sessions.py

There was a new field in the client capabilities for semantic tokens added to the upcoming 3.17 version of the LSP spec:
```typescript
/**
* Whether the client uses semantic tokens to augment existing
* syntax tokens. If set to `true` client side created syntax
* tokens and semantic tokens are both used for colorization. If
* set to `false` the client only uses the returned semantic tokens
* for colorization.
*
* If the value is `undefined` then the client behavior is not
* specified.
*
* @since 3.17.0
*/
augmentsSyntaxTokens?: boolean;
```
I could imagine / hope that servers like rust-analyzer will use that field in the future, to decide whether to emit tokens to just enhance the existing syntax highlighting (with things which are not possible with a static regex-based highlighting …

Announce in initialize request that we augment syntax tokens

---

plugin/session_buffer.py

I have not observed it in practice, but there is a situation where the current logic for semantic token requests could fail in theory:
1. We have some semantic tokens data stored from a full or delta request, with a `resultId` given from the server
2. After typing in the buffer, we send a delta request (`textDocument/semanticTokens/full/delta`) for the stored data with the `resultId`
3. There are more changes in the buffer before the response arrived, so we send a cancel notification for the request, and a new delta request (still with the same `resultId`)
4. The server ignores the cancel notification for the first request (this is allowed per LSP spec) and responds with semantic tokens delta to our first request (from 2.) and a new `resultId`
5. We ignore the response to the cancelled …

Prevent semantic tokens delta request after previous error response

---

plugin/session_view.py

A small bug which prevented the region keys to match what will actually be used when drawing semantic tokens in a few cases.

Lowercase keys for initializing semantic token regions

---

docs/src/keyboard_shortcuts.md

`lsp_signature_help_show` is now a thing and docs should reflect. I figured it out by reading the source and then testing it - seems to work :)

Document the command for showing signature help

---

boot.py
plugin/core/handlers.py

I can't find any package any more that still uses this.

Remove registration of the legacy LanguageHandler class

---

docs/src/language_servers.md

The language servers for JavaScript are scattered throughout the
documentation. Most other language servers are grouped by programming
language. Reorganize the documentation for JavaScript language servers
so it's easy to see what options are available for JS developers.

Reorganize documentation for JavaScript/TypeScript

---

plugin/core/edit.py
plugin/core/protocol.py
plugin/edit.py
tests/test_single_document.py

We could also guard for overflow from the client side. This is all totally hypothetical and I haven't actually tried using LSP-Prisma yet.
Related: #1951

Guard for overflow of the column offset when applying edits

---

docs/src/language_servers.md

Update documentation to make clear that LSP-ltex-ls does provide LaTeX diagnostics and competition, but provides spell check for LaTex and Markdown.

doc: Update documentation for LSP-ltex-ls

---

docs/src/language_servers.md

According to @TheSecEng, LSP-gopls is ready. This PR updates the documentation.

doc: Update Go instructions to LSP-gopls

---

plugin/core/transports.py

Hello! I'm working on an non-proprietary implementation of [VS Code's Development Container](https://code.visualstudio.com/docs/remote/create-dev-container) protocol, [Open Devcontainer](https://gitlab.com/smoores/open-devcontainer). While testing for compatibility with Sublime Text and Sublime LSP, I found what I _think_ is an issue with the ProcessTransport implementation: Sublime LSP considers an empty message in stderr to be a justification for closing the pipe. Unfortunately, it seems that `docker exec` (which `odc` uses for running language servers in containers) emits such an empty message immediately on startup, so all processes are immediately disconnected.
This has come up before, and I'm certain I don't have the whole story, so please let me know if this won't work! It looks …

Just skip empty stderr messages, don't break on them

---

plugin/core/url.py
tests/test_url.py

```
Python 3.3>>> from LSP.plugin.core.url import filename_to_uri, parse_uri, urlparse
Python 3.3>>> filename_to_uri('\\\\wsl$\\Ubuntu-20.04\\home\\jfcherng\\Desktop\\docs\\a.py')
'file://wsl%24/Ubuntu-20.04/home/jfcherng/Desktop/docs/a.py'
Python 3.3>>> parse_uri('file://wsl%24/Ubuntu-20.04/home/jfcherng/Desktop/docs/a.py')
('file', '\\\\wsl%24\\Ubuntu-20.04\\home\\jfcherng\\Desktop\\docs\\a.py')
^^^ this is wrong. should be $
Python 3.3>>> urlparse('file://wsl%24/Ubuntu-20.04/home/jfcherng/Desktop/docs/a.py')
ParseResult(scheme='file', netloc='wsl%24', path='/Ubuntu-20.04/home/jfcherng/Desktop/docs/a.py', params='', query='', fragment='')
^^^ this is wrong. should be $
```
Notice that `netloc` is `wsl%24` after `urlparse()`. We need to decoding that before doing …

Fix WSL path URI decoding under Windows

---

plugin/session_view.py

This fixes an issue that I have, where due to me having a custom style for `unnecessary` diagnostic, those hide the normal diagnostic underlines in case the same region also has normal diagnostic region.
Initializing "normal" diagnostic regions after "tagged" ones solves this issue by assuming that "normal" diagnostics are more important to show than the "tagged" ones so should be initialized later.
So the old code initialized in the following order:
- lspLSP-typescriptdm1
- lspLSP-typescriptdm1_tags_1
- lspLSP-typescriptdm1_tags_2
- lspLSP-typescriptds1
- lspLSP-typescriptds1_tags_1
- lspLSP-typescriptds1_tags_2
- lspLSP-typescriptdm2
- lspLSP-typescriptdm2_tags_1
- lspLSP-typescriptdm2_tags_2
- lspLSP-typescriptds2
- lspLSP-typescriptds2_tags_1
- lspLSP-typescriptds2_tags_2
- …

Initialize diagnostic's tagged regions before non-tagged ones

---

plugin/core/protocol.py

`Request` or `Notification` params are not required to be of any specific type. It's up to the server.

Fix type of Request params

---

plugin/core/sessions.py
plugin/session_buffer.py
plugin/session_view.py

This attempts to fix the issue where semantic regions are being added after diagnostic regions, causing the latter to become invisible.
[As explained by @jwortmann](https://github.com/sublimelsp/LSP/issues/1934#issuecomment-1013964009) this is because we don't initialize all combinations of semantic token region keys in `SessionView._initialize_region_keys`. We could attempt to do that but I figured we could just create a pool of region keys `lsp_semantic_<number>` where the number monotonically increases each time new region is seen. This way we can just initialize regions within certain range (I've picked 0-100 in this PR) and ensure that all semantic regions are drawn in specific order relative to other types of regions. At least as long as the server doesn't use more than 100 …

Fix diagnostic regions being hidden by semantic regions

---

docs/src/guides/cplusplus.md

First of all, I'm not sure of the wording. Also, I'm not sure if this information is really needed, but I'm having trouble finding information about activation of the server. And also, maybe it's better to write about this after
> You will thus have to adjust your `"clients"` dictionary in your user preferences.
and not at the end of page.

docs: add info about enabling clangd server

---

plugin/core/collections.py
tests/test_collections.py

This is another attempt at fixing #1858. This time we keep the old behavior of
merging dicts only for the custom client dicts.
Fixes #1858

Check for `:` and `/` while updating nested dict structures in DottedDict

---

plugin/code_actions.py
plugin/core/protocol.py
plugin/core/sessions.py
tests/test_code_actions.py

Specification says this about `disabled` property:
```
Marks that the code action cannot currently be applied.
Clients should follow the following guidelines regarding disabled code
actions:
- Disabled code actions are not shown in automatic lightbulbs code
action menus.
- Disabled actions are shown as faded out in the code action menu when
the user request a more specific type of code action, such as
refactorings.
- If the user has a keybinding that auto applies a code action and only
a disabled code actions are returned, the client should show the user
an error message with `reason` in the editor.
@since 3.16.0
```
We can't quite follow the second point as we have no way of creating disabled menu items.
As for the third point, we don't provide a way to run specific code actions so that …

Don't expose disabled code actions

---

Default.sublime-keymap
LSP.sublime-settings
Main.sublime-menu
boot.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/types.py
plugin/core/views.py
plugin/document_link.py
plugin/hover.py
plugin/session_buffer.py
plugin/session_view.py
popups.css
sublime-package.json

Is this useful? Tested with LSP-TexLab:
A strange (or maybe just inaccurate) thing in the LSP specs is that a "document link"
> links to an internal or external resource, like another text document or a web site
but the type for `DocumentLink.target` is `DocumentUri`, and not the more general `URI` (they both are defined as `string` though).
---
Initially I figured it might be good to make the links available in the right click context menu, similar to what `Default/open_context_url.py` does for website links, and to run the request only on demand when you open the context menu. But then we can't show the underlines for the links, and it would probably make the context menu very slow (I don't know if it would even be possible to run the request from the …

Add support for textDocument/documentLink request

---

plugin/locationpicker.py
stubs/sublime.pyi

Resolves #1980.
Implementation is more or less copied from Default/symbol.py (where the behavior for ST's native Goto Definition / References is defined), minus the additional functionality when selecting an entry with the mouse while pressing a modifier key (but this isn't yet implemented in LSP's Goto commands anyway).

Show previews in side view for Goto commands with side_by_side

---

Default.sublime-keymap
plugin/references.py

Thanks to #1980 we can now add support for this easily.

Support side_by_side for "Go to reference"

---

plugin/core/views.py

This would be cool for language servers which use a certain convention for admonitions in the hover popups.
Before:
After:

Enable admonition extension for mdpopups

---

plugin/__init__.py
plugin/core/registry.py
plugin/core/windows.py

Add LspWindowCommand

---

Syntaxes/ServerLog.sublime-syntax
plugin/core/windows.py

Don't use actual linebreaks in log panel if payload is string literal

---

Default.sublime-keymap
docs/src/features.md
plugin/goto.py

Unfortunatelly not all LSPs have good symbol definition support. For example, `solargraph`(ruby) has limited support and quite offten returns `No results found`, so you have to keep and remember the built-in Sublime `goto_definition` key bining to be able to jump to at least something.  
It becomes especially inconvenient when you switch between different programming langages where one has a better symbol defition support than another so you always have to keep in mind what exact key to use.
This PR adds an optional `fallback` parameter to the `lsp_symbol_definition` command that allows to fallback to the built-in `goto_definition` command in case no results were found.  
```JSON
{ "keys": ["super+alt+down"], "command": "goto_definition" },
{
"keys": ["super+alt+down"],
"command": …
```

Optionally fallback to goto_definition in lsp_symbol_definition

---

Default.sublime-keymap
plugin/core/open.py
plugin/goto.py
plugin/locationpicker.py

Fixes #1990
More general, this also aligns the behavior of LSP Goto commands with the behavior of the native commands in the following, related case: if the location is in another file, which is already opened in another group, then the LSP commands would focus the already opened tab. After this PR, it will instead create a new view for the file in the active group.
There was a logic bug in the open_file function, which caused the current behavior (assuming that the `group = -1` argument should have the same meaning as in all the Sublime API functions).

Keep active group when using Goto commands

---

plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/views.py
plugin/documents.py
plugin/symbols.py

- This defines [sublime.Kind](https://www.sublimetext.com/docs/api_reference.html#sublime.Kind) tuples, so that they can be reused for LSP's `SymbolKind`s and `CompletionItemKind`s, which have a lot of overlap and even had a few inconsistencies before.
- Also they could easily be used for sublime.QuickPanelItem now.
- No more awkward indexing with `kind - 1`
- Moved the small lookup dicts for DocumentHighlightKind to core/views.py as well, because that seems to be the place where most of such things are defined.
- Fixes a bug in views.py#format_completion, which would use an `int` instead of a kind tuple for the kind in `sublime.CompletionItem.command_completion`, in case there is a kind id in the language server response, which is out of range for LSP's CompletionItemKind.
Changes:
- …

Refactor symbol and completion item kinds

---

plugin/core/configurations.py

Some users may accidentally have `"lsp_format_on_save": true` in their .sublime-project like this:
```js
{
"settings": {
"LSP": {
"lsp_format_on_save": true
}
}
}
```
Of course LSP-json flags this as invalid, but not everyone has LSP-json installed. Furthermore this would prevent loading any configuration, so LSP wouldn't run any language server.

Prevent failing to load all configs when one fails

---

docs/src/customization.md
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/signature_help.py
plugin/documents.py

- Add contextSupport (see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelpContext). For now, "triggerKind" will always be SignatureHelpTriggerKind.Invoked in case of invoking via key binding, or otherwise SignatureHelpTriggerKind.TriggerCharacter. Maybe some more logic could be added in the future, to determine if the last pressed key was e.g. <kbd>Backspace</kbd>, for the third possible option of SignatureHelpTriggerKind.
- Add support for `activeParameter` property on `SignatureInformation` (since LSP 3.16 - see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureInformation)
- Allow color schemes to adjust color of currently highlighted parameter
- Small tweaks regarding code style …

Tweaks for signature help popup

---

plugin/core/views.py
tests/test_completion.py

Alternative to and discussed in #2002.

Completions overhaul

---

docs/src/language_servers.md

The current docs install FSAC as a global tool, but invoke it as a local tool. Invoking it as a global tool means executing the globally-installed shim (which is installed to a global path by default).
These updates are based on getting @matthewcrews up and running, thanks Matthew!

Update F# guidance

---

plugin/documents.py

This is part 2 of https://github.com/sublimelsp/LSP/commit/e14bf5de0cacabea9545cf88f27cea7fa8e4e840.
Now both of the builtin ST settings are respected. For example, I personally use
```jsonc
{
"auto_complete_include_snippets": true,  // (default value)
"auto_complete_include_snippets_when_typing": false,
}
```

Follow global settings more accurately whether to show snippet completions

---

plugin/session_buffer.py

This is a small optimization for semantic highlighting:
* If a very big file was just opened, initially request tokens only for
the visible range (if the server supports it), and after the response
arrives also request tokens for the rest of the file. This way
semantic highlighting can be shown faster for the currently visible
part of the file, and for the rest of the file it will be applied a
little bit later.
* If the server supports only the semanticTokens/range request, use the
entire file range for the requested content range while typing. By
doing this, semantic highlighting is also visible after scrolling the
file and it prevents unpleasant highlighting updates when typing after
scrolling to another position.
With LSP-lua and a 165kb file:
**Before:**
<details>
<summary>Click to …

Improve strategy for semantic highlighting requests

---

boot.py
plugin/execute_command.py

A simple addition to make it so that plugins can easily use it with custom response handlers without re-implementing the `run` method.
I've changed the default success handler to not stringify the response as the response can be anything, including a complex object, so it doesn't make sense to assume that it's something that can be presented in the status bar.
Resolves #1902

Add overridable methods to LspExecuteCommand

---

plugin/core/sessions.py
plugin/documents.py
plugin/session_buffer.py
plugin/session_view.py

... after a "refresh" request from the server, which may be triggered by some servers after each document change.
I have not tested it for inlay hints because LSP-gopls doesn't seem to support inlayHint/refresh, but you can see the improvement to avoid unnecessary code lens requests for example with rust-analyzer.

Delay re-calculation of currently not visible code lenses and inlay hints

---

ColorSchemes/Breakers.sublime-color-scheme
ColorSchemes/Celeste.sublime-color-scheme
ColorSchemes/Mariana.sublime-color-scheme
ColorSchemes/Monokai.sublime-color-scheme
ColorSchemes/Sixteen.sublime-color-scheme
LSP.sublime-settings
docs/src/customization.md
plugin/core/types.py
plugin/core/views.py
plugin/documents.py
plugin/hover.py
plugin/session_view.py
sublime-package.json

Inspired by VSCode. Not sure if it's needed, and there seems to be a slight aversion to introduce new settings. But I kind of like it (and it's disabled by default).
For the "document_highlight_style" setting I have also renamed the "fill" option to "background" (which I now think is a better name), but kept it fully backwards compatible with "fill".
Feel free to merge or close.

Add option to highlight hover range

---

plugin/hover.py
plugin/inlay_hint.py

Make sure special characters like `&` are properly escaped in minihtml content.
For example with LSP-html and hover over the link in the following file:
```html
<!DOCTYPE html>
<html>
<body>
</body>
</html>
```
I assume that this might fix #2034, but due to lack of motivation to install Rust + rust-analyzer manually, I have not tested it.
@minerscale If you want, you could give it a try and see if it fixes your issue :)

Fix unescaped special characters in minihtml

---

Default.sublime-keymap
docs/src/features.md
plugin/references.py

It is a follow-up PR for https://github.com/sublimelsp/LSP/pull/1986
This PR adds an optional `fallback` parameter to the `lsp_symbol_references ` command that allows fallback to the built-in `goto_reference` command in case no results were found.

Optionally fallback to goto_reference in lsp_symbol_references

---

plugin/code_actions.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/views.py
plugin/documents.py
plugin/hover.py

- if there are multiple code actions and one of them uses `"isPreferred": true`, then preselect it in the quick panel
- add icons for the quick panel entries if CodeActionKind is provided :)
I'm not sure whether multiple code actions can be "preferred" for a given range at the same time, but I would interpret the description at https://code.visualstudio.com/updates/v1_32#_auto-fix-and-preferred-code-actions in such a way that it should not happen.
Other possible enhancements for a future PR:
- add a `only_preferred` argument for the `lsp_code_actions` command, which will then only consider code actions with `"isPreferred": true`
- sort code actions by CodeActionKind for the quick panel

Add icons and isPreferred support for code actions

---

plugin/code_actions.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/views.py
plugin/documents.py
plugin/hover.py

Set triggerKind for code action requests to indicate whether action was automatic or manual. Typescript server returns different refactorings depending on how the request is made.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionContext
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionTriggerKind
Adding support for triggerKind in typescript in https://github.com/typescript-language-server/typescript-language-server/pull/579 in case someone wants to test.
Resolves #2041
Resolves #1890

Add support for triggerKind in code action requests

---

Context LSP Log Panel.sublime-menu
boot.py
plugin/core/panels.py
tests/test_server_panel_circular.py

Toggles the limit per window rather than globally. I've assumed it's better that way as it will "limit the damage" if someone leaves it disabled for a long period of time.
Resolves #1810

Add context menu entry in log panel for toggling lines limit

---

Default.sublime-keymap
docs/src/features.md
plugin/core/open.py
plugin/core/sessions.py
plugin/goto.py
plugin/locationpicker.py

This PR will allow the user to pass a group for `Goto` commands.
When the group is specified:  
- The result will always open in the group.
- If there's more than one result, it will focus to the group and open the `LocationPicker`.
Relates to: #2022

Add group argument for LspGotoCommand

---

plugin/core/open.py
plugin/core/url.py
plugin/document_link.py
plugin/hover.py

Should handle the following formats which are supported by VSCode:
https://github.com/microsoft/vscode/blob/835ace5796cec0ed19a7eec119b26b57220b0f1a/src/vs/platform/opener/common/opener.ts#L153-L160
It applies to Markdown links in the hover content and also to `DocumentLink.target` from the "Document Link" response.
Can be tested for example with LSP-html and the following file:
```html
<!DOCTYPE html>
<html>
<body>
<h1 id="anchor">Heading</h1>
<a href="#anchor">link</a>
</body>
</html>
```
Closes #2009.

Parse position or selection from link fragment

---

LSP.sublime-settings
docs/src/troubleshooting.md
sublime-package.json

Currently if the user want to enable logging, 
the following settings have to be set:
```
"log_debug": true,
"log_server": ["panel"],
```
----
With this PR the user just have to enable:
```
"log_debug": true,
```
So we skip one additional thing that needs to be enabled.
----
EDIT:
closes https://github.com/sublimelsp/LSP/issues/1508

Change log_server default value to  ["panel"]

---

plugin/code_lens.py
plugin/completion.py
plugin/core/open.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/views.py
plugin/documents.py
plugin/execute_command.py
plugin/hover.py
plugin/rename.py
plugin/selection_range.py
plugin/session_buffer.py
plugin/symbols.py
tests/test_code_actions.py
tests/test_protocol.py
tests/test_views.py

As suggested by @jwortmann in https://github.com/sublimelsp/LSP/pull/2049#discussion_r967910560 and also to make migration to new types much easier, renamed `RangeLsp` to `Range` and removed our custom `Range` class. It was an unnecessary intermediate class that wasn't really used for much (its `contains`, `intersects`, `extend` methods weren't even used outside of tests).

Remove Range class and rename RangeLsp to Range

---

Default.sublime-keymap
boot.py
docs/src/keyboard_shortcuts.md
plugin/core/registry.py
plugin/core/sessions.py
plugin/core/views.py
plugin/goto_diagnostic.py
plugin/panels.py
plugin/session_buffer.py
plugin/symbols.py
tests/test_server_notifications.py

This makes the console command `sublime.log_commands(True)` usable again if you type in a view which has diagnostics.

Only update content of diagnostics panel when visible

---

plugin/code_actions.py
plugin/core/protocol.py
plugin/core/views.py
tests/test_views.py

Makes sure that the code action request that we make when triggering the "Source actions..." command explicitly includes `"only": ["source"]` kind.
Related to https://github.com/sublimelsp/LSP/issues/1846#issuecomment-1255150008
(More readable diff with `Hide whitespace changes` enabled)
@jwortmann

Ensure "Source Actions..." request includes the "source" kind

---

plugin/core/typing.py
pyrightconfig.json

Fixes compatibility with 3.8 host. We'll use real imports for type checking and dummy ones for the plugin host, like we do now for 3.3.

Import new imports like NotRequired from "typing"

---

boot.py
plugin/color.py
plugin/core/protocol.py
plugin/core/views.py
plugin/session_buffer.py
tests/test_views.py

This runs the `textDocument/colorPresentation` request when clicking on a color box, and shows the results in a quick panel. I think it is better to apply the change into the file only after selecting one of the quick panel entries, rather than immediately like it's implemented in the VSCode color picker when cycling through the different color formats. Because the conversion from RGB to HSL/HWB and back again might alter the original color (e.g. `#dddddd` -> `hsl(0, 0%, 87%)` -> `hwb(0 87% 13%)` -> `rgb(222, 222, 222)` -> `#dedede`).
There is no special server capability for this request by the way, so we can't decide beforehand whether or not it is supported by the server and is useful to make the color box clickable. (But maybe it's expected that servers that have the colorProvider …

Request color presentations when clicking on a color box

---

plugin/documents.py

The issue was that files in the background have received new diagnostics and since the "last save change count" has still matched, that has triggered the panel to hide or open.
To fix, reset the "last save change count" after showing or hiding the panel so that it's only relevant again after next save.
It was reproducible by:
1. having an error in one file and saving it
2. hiding the panel
3. switching to another file with no errors and saving it
The file saved in 1 would receive updated diagnostics and the logic would pop the panel open again.
(Of course those steps depend on what servers are used and whether saves in certain files trigger diagnostics in other files)

ignore background files for toggling diagnostics panel on save

---

Main.sublime-menu
plugin/core/protocol.py
plugin/symbols.py

```
/**
* The parameters of a Workspace Symbol Request.
*/
interface WorkspaceSymbolParams extends WorkDoneProgressParams,
PartialResultParams {
/**
* A query string to filter symbols by. Clients may send an empty
* string here to request all symbols.
*/
query: string;
}
```
closes #1008

Allow empty string for workspace symbol request

---

plugin/core/signature_help.py
tests/test_signature_help.py

fixes https://github.com/sublimelsp/LSP/issues/1694

Improve highlighting of signature parameters when labels are of type string

---

plugin/tooling.py

An enum like the one below would crash the code as `.join` expects strings.
```js
"volar.takeOverMode.enabled": {
"type": [
"boolean",
"string"
],
"enum": [
"auto",
false
],
},
```

Fix crash on generating schema with mixed-type enum

---

plugin/core/views.py
plugin/session_buffer.py
tests/test_views.py

Doing the phantoms update on the main thread (like it's already done with the inlay hints phantoms) fixes the double color box flash after selecting another color format from the quick panel.

Fix short color box rendering bug after color presentation change

---

plugin/goto_diagnostic.py

Only enable Goto Diagnostic commands if diagnostic with configured severity exists

---

docs/src/commands.md
plugin/execute_command.py

Some language server commands can only take the `line` and/or `character` integers individually instead of the entire `position` object. Allowing those variables to also be expanded adds to the flexibility of individual LSP plugins.
This was tested locally using https://github.com/sublimelsp/LSP-elixir and https://github.com/elixir-lsp/elixir-ls (specifically the `manipulatePipes` command: https://github.com/elixir-lsp/elixir-ls/blob/a4bd85e/apps/language_server/lib/language_server/providers/execute_command/manipulate_pipes.ex#L21)

Add `$line` and `$character` expansion variables

---

plugin/configuration.py
plugin/core/registry.py

There were issues with restarting servers when there were more than one views using the same session and the corresponding server was restarted. Only the active view would start the session again and on other views the session would not start.
Fixed by using `WindowManager.restart_sessions_async` which re-registers all view listeners rather than the (internal) `WindowManager._end_sessions_async` and manually registering just the active view listener.
Also removed unnecessary `WindowManager._end_sessions_async` call after disabling server globally as ending the sessions is already handled on disabling the config (saving settings).

fix issues with restarting servers

---

plugin/symbols.py

Match ST behavior and focus symbol closest to selection on triggering Go to Symbol command.
Taking end point of first selection and finding symbol that intersects it or is just before it.
I think ST might have slightly different behavior with multiple selections (takes into account last while we take first) but otherwise it should match ST behavior.
Fixes #2093

Focus symbol closest to selection on showing document symbols

---

plugin/hover.py

I think it would be better for the popup on hover over a DocumentLink, to already indicate that it will be opened in a browser if that is the case. Otherwise it could be a bit surprising for users, because most of the time these are links to a location in another file.
-> Adjust label to "Open in Browser" if the target is not a file uri.
And in case there are multiple sessions at the same time, which all provide DocumentLinks, then combine them into a single link and open a quick panel with the target URIs to choose from when clicked, instead of just putting multiple links into the hover popup.

Improvements for DocumentLink in hover popup

---

language-ids.sublime-settings

relates to https://github.com/sublimelsp/LSP-tailwindcss/issues/42

Add elixir to language ids

---

plugin/session_buffer.py

Fix diagnostics_additional_delay_auto_complete_ms not working after split view

---

plugin/core/views.py
plugin/session_buffer.py

Python has this actually built-in for dict/TypedDict.

Remove unnecessary is_range_equal function

---

plugin/core/windows.py

Files within folders excluded by `"folder_exclude_patterns"` are not shown in the sidebar and can't be opened via "Goto Anything...", so it's probably better to ignore diagnostics for those files.
The line which was removed in the diff did basically nothing, because fnmatch would never match just a folder name or path segment from the "folder_exclude_patterns" if not adapted to glob pattern conventions.

Ignore diagnostics for files in folder_exclude_patterns

---

plugin/core/sessions.py
plugin/documents.py
plugin/session_buffer.py
plugin/session_view.py

Servers like typescript trigger `textDocument/publishDiagnostics` for all open files on making any changes. Our `DocumentSyncListener` triggered [code action request](https://github.com/sublimelsp/LSP/blob/439b01efe862497ee67dedb7d7d9662521c12537/plugin/documents.py#L285-L286) in that case.
Changed so that code action request is only made if the view is visible.
Since the code action response can be affected by changed diagnostics, make sure that the code action request is then also made when view is activated later.
We should have been triggering code action request on view activation anyway as otherwise we have relied on `textDocument/publishDiagnostics` triggering it which is not guaranteed.
Also made sure that `on_load_async` triggers `on_activated_async` which triggers code …

Don't trigger code action requests for background views

---

plugin/goto_diagnostic.py

At the moment, "Goto Diagnostic..." opens a slightly different overlay compared to invoking "Goto Diagnostic in Project..." and selecting a file. Doing the latter will show the filename in the command palette input and when pressing <kbd>Backspace</kbd> it will go back to the list of files, which is not the case for "Goto Diagnostic...".
This PR would make both of the commands to show a consistent overlay by adding the file preselected to the input field for "Goto Diagnostic...".
Feel free to discuss or reject if this implementation feels too dubious/hackish...

Make Goto Diagnostic overlays consistent

---

language-ids.sublime-settings

I wondered why LSP wasn't working for my [Django](https://djangoproject.com) HTML templates. After I followed the steps outlined in https://github.com/sublimelsp/LSP-tailwindcss/issues/47 it worked. So here's a pull request so other people don't have to customize their configs to make it work.

Add language id for Django templates

---

Default.sublime-keymap

The keybindings file looks like it was created by a JSON formatter with all those unnecessary linebreaks like in
```jsonc
"keys": [
"f12"
],
```
This PR makes it more readable (in my opinion), removes a few unnecessary things like `"operator": "equal", "operand": true` and adds two examples (which are commented out) for Goto Definition/References in side-by-side mode, with Sublime's default keys.

Format keybindings file

---

Context.sublime-menu
boot.py
plugin/core/views.py
plugin/formatting.py

This is a first step towards cleaning up the context menu (#1983) by combining "Format File" and "Format Selection" into a single item with dynamic label. It also makes the question obsolete whether "Format File" should be included in the context menu or if the main menu entry is enough (https://github.com/sublimelsp/LSP/issues/2066#issuecomment-1256614309).

Combine file and range formatting entries in context menu

---

plugin/core/views.py
plugin/core/windows.py

Looks better & it's the same as what VS Code does.

Don't show a source if diagnostic doesn't have a source

---

plugin/code_actions.py
plugin/core/registry.py
plugin/goto.py
plugin/references.py
plugin/rename.py
plugin/selection_range.py

This is another step towards cleaning up the context menu, by hiding unavailable items there (but not in the main menu).
For the "Expand Selection" command I added a `fallback` argument (default to `True` to preserve current behavior) similar to the "Goto" commands.
I'd personally prefer to eventually remove the submenu and put the items at the top level, maybe with an "LSP:" prefix, so that they can be accessed more quickly. In that case it would probably be better to change the "Expand Selection" `fallback` default to `False`.

Hide inactive items in context menu

---

plugin/core/sessions.py

Currently, plugins can not set the configuration object in `on_workspace_configuration` if it is `None` or it has to be replaced completely.
This did only work in those cases where `configuration` was a reference to an object that could be altered.
See 
https://github.com/sublimelsp/LSP-jdtls/commit/85f2392c9af3cdbf5048bdac8fad81cb29a1c95a
for an example where the current implementation does not work.
This PR changes `on_workspace_configuration` so that it must return the new configuration item. The default implementation now forwards the "pre-resolved" configuration.

Fix plugin overwrite `on_workspace_configuration`

---

plugin/core/sessions.py
plugin/documents.py
plugin/rename.py

The issue with the old code was that it has shown the input overlay asking for new name before sending the `prepareRename` request and didn't use the range (or placeholder) from the response.
Added big comment about how `lsp_symbol_rename` works since it behaves very differently depending on if server supports prepareRename request.
Related to https://github.com/sublimelsp/LSP-typescript/issues/178

Fix prepareRename support

---

Default.sublime-keymap
plugin/documents.py

https://github.com/sublimelsp/LSP/issues/2128#issuecomment-1349141253
This adds a new context to check for a DocumentLink at the current cursor position, which can be used for the `lsp_open_link` key binding. This way users can configure to use the same key as for "Goto Definion...", if they place the `lsp_open_link` key binding after (below) the other one (see https://docs.sublimetext.io/reference/key_bindings.html#order-of-preference-for-key-bindings).

Add context for lsp_open_link key binding

---

plugin/core/sessions.py

Since we don't have any special handling for disabled code actions and instead just filter them away, as long as server is compliant, it should be better to just not advertise support for it as then we should not receive those in the first place.
There is still code in place to filter out "disabled: true" code actions but it can be left as a safety net for non-compliant servers (not aware of any).

don't advertise support for disabled code actions

---

plugin/goto.py
plugin/locationpicker.py

Addressing issue mentioned in https://github.com/sublimelsp/LSP/pull/1994#issuecomment-1270279134

Pass force_group to LocationPicker

---

Default.sublime-commands

Added those to Command Palette to match menus:
- `LSP: Goto Definition…`
- `LSP: Goto Type Definition…`
- `LSP: Follow Link`
Fixes #2130

add missing Goto commands to Command Palette

---

plugin/core/types.py
plugin/documents.py
plugin/session_buffer.py

Updating of code lenses should IMO not be tied to selection update as document can get modified programmatically in which case selection might not change.
There is also another weird case where I've noticed this issue during "Undo" and that one has deeper roots... When undoing removal of a line, `on_text_changed_async` is quickly called twice and on the first call selection is `different` from the stored one but on the second call, it's not. That results in `_when_selection_remains_stable_async` not being triggered (first time because region no longer matches in `debounced` and second time because `different` is `False` so we return early from `on_text_changed_async`). This is an issue that should still be fixed but it's fairly minor and probably doesn't even effect `_do_highlights_async` …

fix code lenses not updating after Undo

---

plugin/session_buffer.py

Before triggering completion or signature request, we are forcing a [`purge_changes_async()`](https://github.com/sublimelsp/LSP/blob/0ee0a7f6658805f61187a8a591b4980e99a0e5d5/plugin/session_buffer.py#L281-L281) because we have to. This immediately triggered various non-essential requests like semantic highlighting, inline hints, document link, color boxes which can dramatically reduce responsiveness due to those requests jumping in front of the queue. Instead trigger those in the next "tick" so that the completion/signature requests are triggered first.
Before those changes (with semantic highlighting enabled and being the main reason for worse responsiveness):
https://user-images.githubusercontent.com/153197/208928929-d35cef67-4223-4947-b00b-92e7f7fb2eda.mov
With those changes: …

improve performance of completion & signature request on typing

---

plugin/core/configurations.py
plugin/core/sessions.py
plugin/core/windows.py

This PR aims to do two things:
Open questions:
- Where should the state about crashed servers be stored? (WindowManager, ClientConfig, ...)
- How often do we attempt to restart the server? When is the counter reset?
(e.g. Increase the counter if the last crash was <30s apart, else reset the counter. If the counter reaches 5, ask the user and reset the counter?)

Auto-restart on server crashing, up to 5 times

---

plugin/core/open.py

Noticed that on "Goto definition", when the region of the definition spans many lines, ST scrolls to the end of the region rather than the start.
Imagine triggering "Goto definition" on a symbol that jumps to the constructor of that symbol and that constructor spans many lines. Focusing on the end of the constructor implementation is rather confusing and also it's not where the selection/cursor is in this case.

when going to definition scroll to start of the region, not end

---

plugin/completion.py
plugin/core/sessions.py

Based on investigation in https://github.com/sublimelsp/LSP-pyright/pull/207.
I believe this is correct since `minihtml_content` is built from parts that should have already gone through mdpopups markdown parsing but I might have missed something.

fix completion documentation being parsed as markdown twice

---

Main.sublime-menu
boot.py
plugin/code_actions.py
plugin/core/sessions.py

Here's another experiment of mine. It can dynamically show up to 5 "Refactor" code actions in the "Edit" main menu, without the need to open the quick panel overlay.
I haven't tested with actions from multiple sessions at the same time, but I think it should work™.
Closes #1846 (?)

Add "Refactor" entry to the "Edit" main menu

---

Main.sublime-menu
boot.py
plugin/code_actions.py

Same as #2141, but for "Source Action".
I also moved "Format File" and "Format Selection" into a submenu.
Note that no diagnostics are sent when requesting the "source" and "refactor" actions, but I would expect those actions to not depend on diagnostics, so I think this should be okay.
It would be good if someone could test it with a server that also provides "source" actions.
---
And I've experimented a little bit with the context menu, but I'm not happy with how it turns out if the same submenus for "Refactor" and "Source Action" are applied to the context menu. Because those menu items for the submenus cannot be hidden if they contain no items. That means that they will always be present in the context menu, even if no LSP is running (for example for basic `.txt` files).
The following …

Add "Source Action" entry to the "Edit" main menu

---

plugin/inlay_hint.py

Use inline element instead of block so that inlay hint parts are shown on the same line.
I've also checked what happens when two inline hints with multiple parts are added in the same place and that looked OK (there was space between them).
Fixes #2152

Fix inlay hint parts wrapping into multiple lines

---

plugin/core/views.py
tests/test_views.py

The motivation is provided in #2158 but basically [both](https://github.com/sublimelsp/LSP-css/pull/16) [issues](https://github.com/sublimelsp/LSP/pull/1591) that we had that needed this extension don't seem to manifest itself anymore and there is a new #2151 issue that it causes.
Fixes #2151

Don't use "escapeall" extension when formatting with mdpopups

---

plugin/code_actions.py
plugin/code_lens.py
plugin/color.py
plugin/core/edit.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/views.py
plugin/core/workspace.py
plugin/document_link.py
plugin/documents.py
plugin/edit.py
plugin/formatting.py
plugin/goto_diagnostic.py
plugin/inlay_hint.py
plugin/locationpicker.py
plugin/rename.py
plugin/selection_range.py
plugin/session_buffer.py

This PR should improve some type annotations, mostly by replacing `Dict[str, Any]` or similar with the actual LSP types for request or response parameters. (Plus a little bit of cleanup for imports in a few files, to use one line per import.)
No claim for completeness.

Improve type annotations

---

language-ids.sublime-settings
tests/test_server_requests.py
tests/test_types.py

This change is required for LSP-cspell to work in plaintext files.
ref to spec https://github.com/microsoft/language-server-protocol/pull/1577

Use "plaintext" language ID for plain text files

---

plugin/active_request.py
plugin/core/active_request.py
plugin/core/sessions.py
plugin/session_view.py

This commit adds a workaround for servers that report server-initiated progress but don't request window/workDoneProgress/create before reporting progress.
I haven't actually tested whether this works with jdlts regarding its progress reporting behavior in https://github.com/sublimelsp/LSP-jdtls/issues/37, could you check @LDAP ?

Allow missing window/workDoneProgress/create request from the server

---

docs/src/language_servers.md

this is default now
The argument is not available anymore.

docs: fsautocomplete config - remove redundant argument

---

plugin/core/views.py
plugin/symbols.py

Some suggestions for the "LSP: Goto Symbol..." feature to follow ST's "Goto Symbol..." more closely (the current implementation is closer to what VSCode does, though, but I don't think that matters much).
* If the server response is of type SymbolInformation (deprecated), then adjust the outline color for highlighted items to use the color from the symbol item kind (which is defined by the theme, but there is a strong recommendation in the [theme docs](https://www.sublimetext.com/docs/themes.html#quick-panel) under `kind_container`, and the built-in themes follow those recommendation), rather than the scope color from the color scheme for the symbol. By using the theme's kind color the outline matches the icon color in the quick panel.
* If the server response is of type DocumentSymbol, …

Make Document Symbols behavior more consistent with built-in Goto Symbol

---

plugin/core/sessions.py
plugin/core/types.py
plugin/core/windows.py
plugin/session_view.py

This allows a plugin to call `Session.set_config_status_async` which would add extra text in parenthesis in the server's permanent status. For example can add server version info like:
It could also be used to show whether workspace-local or global server is used or anything else.

feat(API): allow setting additional text in permanent server status

---

.github/workflows/main.yml
plugin/core/protocol.py
plugin/core/sessions.py
plugin/documents.py
tox.ini

We didn't trigger `AbstractPlugin.on_server_response_async` for the `initialize` response because plugin instance is created a bit later, from the initialize handler. Have exception for that case and trigger it manually from the handler.
I'm contemplating using it in LSP-rome to show server version that is provided in initialize response.
Also making `Repsonse` type Generic and more accurate. Not really doing much to improve anything. Just makes it easier to annotate in `on_server_response_async`.

trigger "on_server_response_async" also for "initialize" response

---

LSP.sublime-settings
plugin/core/types.py
sublime-package.json

https://discord.com/channels/280102180189634562/645268178397560865/1068560891806752798

disable diagnostics panel

---

Syntaxes/ServerLog.sublime-syntax
plugin/core/windows.py

Borrowed a bit from https://github.com/sublimelsp/LSP/issues/272#issuecomment-1262201348. Currently looks like this.
Scopes and formatting up for discussion.
Resolves #272

add timestamp and request duration in LSP log

---

plugin/documents.py
plugin/session_buffer.py

When file has been "reloaded" by ST due to branch change or just modified externally then the requests that normally happen on file changes didn't run. That includes code lenses, symbol highlights, color boxes, semantic tokens, document link and inlay hints. That result in lack of those features until file was modified or stale state like with those code lenses for example:

fix stale state or lack of updates on changing branches

---

Context.sublime-menu
Default.sublime-commands
Default.sublime-keymap
boot.py
docs/src/keyboard_shortcuts.md
plugin/core/paths.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/goto_diagnostic.py
plugin/type_hierarchy.py

The type hierarchy specs/interface is very similar to call hierarchy, so `type_hierarchy.py` is basically a copy/paste of `call_hierarchy.py`. I'm unsure whether there should be added another abstraction layer, with `LspHierarchyDataProvider(TreeDataProvider)`, `LspHierarchyCommand`, and `LspHierarchyToggleCommand`, from which call hierarchy & type hierarchy can derive, but then you need to pass a lot of strings and the protocol types in `__init__`. And there is a bit of difference between the call and type hierarchy responses, in that type hierarchy always returns `TypeHierarchyItem[]` directly, but call hierarchy uses wrapper classes `CallHierarchyOutgoingCall[]` / `CallHierarchyIncomingCall[]` with `from`/`to` fields. That could make a generic implementation a bit awkward.
(I assume …

Implement type hierarchy request

---

Default.sublime-keymap
plugin/references.py

support "force_group" and "group" arguments in "lsp_symbol_references"

---

boot.py
plugin/completion.py
plugin/core/views.py
stubs/sublime.pyi

A low-hanging fruit optimization that allows us to create `CompletionList` with drastically smaller payload.
Instead of serializing complete completion items and attaching those to `CompletionItem.args`, only attach an index of the item and lookup the item within the global completions list attached to the `LspSelectCompletionCommand` class (previously it was attached to the `LspResolveDocsCommand` class but moved to match the current use).
We did that already for the purpose of of accessing them for the `completionItem/resolve` request but there is no reason not to do that for the completion insertion also.
I've created a separate package at https://github.com/sublimelsp/LSP-performance-test which currently includes one performance test for testing the `format_completion` function. …

Optimize performance of handling huge completion payloads

---

plugin/completion.py
plugin/core/views.py
tests/test_completion.py

I didn't want to muddle previous PR with the move so doing it separately. I think there is too much stuff in `views.py` and this code really belongs in `completion.py` anyway.
There are no changes besides the move.

refactor: move format_completion into completion.py

---

boot.py
plugin/core/panels.py
stubs/sublime.pyi

There was annoying issue with LSP Log Panel that meant that the content didn't scroll when opened initially.
I've experimented a bit with a simple plugin and noticed this this seems like a bug that triggers when:
- panel view's `scroll_past_end` setting is set to `False`
- and panel is shown with more than a screenfull of content inserted at the same time
The work around is to just trigger `view.show(view.sel(), animate=False)` after inserting text to scroll the view to the end (or wherever selection was set too if it's not the initial opening).

fix log panel not scrolling on initial open

---

plugin/code_actions.py
plugin/core/sessions.py
plugin/documents.py
plugin/session_buffer.py

On getting code actions, instead of checking `Session` capabilities, check against `SessionBuffer` so that we take into account dynamic capabilities that might have been registered (for specific document selector rather than globally).
Fixes #2201

check capabilities against buffer when requesting code actions

---

plugin/session_view.py

could crash with invalid user values: https://github.com/TerminalFi/LSP-copilot/issues/90

protect again invalid `auto_complete_triggers` values

---

plugin/completion.py
tests/test_completion.py

Workaround for and closes #2169.
I've put the `labelDetails.detail` into the ST "detail" field, if it starts with a letter (or number), which likely indicates that it is a type annotation. Because I think for example `NaiveDateTime struct` doesn't look very good in the "trigger". But, if the language server intentionally prepends a space, then keep it in the "trigger".
Open for discussion @princemaple

Tweak completion formatting with labelDetails

---

plugin/core/sessions.py
plugin/session_buffer.py
plugin/session_view.py
tests/test_session.py

Diagnostics are stored in `Session` and there might exist diagnostics for not-yet-opened files so notify Session Buffers immediately about those when creating new buffers.
This fixes somewhat obscure bug for servers that don't implement `didOpen` but also makes diagnostics show more quickly after opening files for other servers (in case diagnostics were already reported for those files).
Fixes #2200

notify opened files immediately if there are pending diagnostics

---

LSP.sublime-settings
messages/1.23.0.txt

Did a bit of grouping of options to make default settings a bit more organized.
Also removed default configs for rust-analyzer, clangd and gopls since we have dedicated packages for those.
Improvement suggestions welcome.

better grouping of default settings

---

plugin/documents.py

while debugging something I've realized that the `TextChangeListener` would be initialized when triggering Command Palette because `is_applicable` returned True.

don't initialize TextChange listeners for widgets

---

plugin/session_buffer.py
plugin/session_view.py

While working on another PR #2221, I noticed that some features in the SessionBuffer class only check for the server capabilities which are stored in the Session, but not specific to the SessionBuffer. This means that it could miss a server capability, if it was dynamically registered with a `documentSelector` (see [TextDocumentRegistrationOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentRegistrationOptions)).
The relevant code for that is at https://github.com/sublimelsp/LSP/blob/4ed8b7a75b091311bff041eb63aea2744c35b23e/plugin/core/sessions.py#L1779-L1785
I have no example of this where it happens in practice (I don't know any server which uses dynamic registration with documentSelector). But it should be relevant for pull …

Fix some features might not work with dynamical registration

---

docs/src/language_servers.md

- The newer clojure-lsp builds are done with GraalVM and must not be called with 'java -jar' anymore.
- The clojure-lsp.io website serves the up-to-date installation instructions and settings.

Update clojure-lsp docs

---

plugin/core/sessions.py
plugin/core/windows.py
tests/test_session.py

This should fix an uncatched exception in case of server response with id `null`, which apparently is valid per LSP & JSON-RPC specs and is or was used by at least one server (https://github.com/JohnnyMorganz/luau-lsp/issues/161 - maybe in a bit inappropriate way, though).

Fix exception for null response id

---

docs/src/customization.md
inlay_hints.css
plugin/core/css.py
plugin/inlay_hint.py

Closes #2229.
This allows user modifications of the inlay hint styles more easily, by overriding only the `inlay_hints.css` file.
When you create an override for the file, ST must be restarted, because the CSS is loaded only when the LSP package is loaded (on ST start).
I hope ST devs one day will fix the color scheme bug that I mentioned in the linked issue, but I think for now this is a feasible workaround.

Allow style overrides for inlay_hints.css

---

plugin/completion.py
plugin/core/views.py
plugin/goto_diagnostic.py
plugin/hover.py
tests/test_views.py

- Removed unused `view` argument from `format_diagnostic_for_html`
- Escape diagnostic properties when including them in HTML
Fixes #2223

html-escape diagnostic-related strings

---

plugin/session_buffer.py

With push diagnostics, some (most?) servers clear diagnostics for a file on `didClose`. At least this should be the case for servers which (are configured to) send diagnostics only for files that are opened in the editor, e.g. Pyright with default setting `"python.analysis.diagnosticMode": "openFilesOnly"`.
With pull diagnostics, at the moment we are always only in this diagnostics-for-open-files-only mode[^1], so I think it makes sense to clear diagnostics for a file when the last view of that file closes. Otherwise, they would still be shown in the diagnostics panel and Goto diagnostics quick panel. See also https://github.com/microsoft/language-server-protocol/issues/1542#issuecomment-1237778484, where it is mentioned that it might make sense to keep the diagnostics e.g. for the …

Clear pull diagnostics on file closed

---

plugin/core/windows.py
plugin/core/workspace.py
plugin/session_view.py

ProjectFolders now holds a mapping of `folder_exclude_patterns` matching each of the workspace `folders`. This way we can do more targeted check to know whether path is not ignored in at least one of the folders.
I think this logic might be a bit hard to wrap the head around and not sure if the design of that fix is good.
Fixes #2171

Fix handling of folder_exclude_patterns in projects

---

plugin/documents.py

Workaround a pathological case where server returns hundreds of code actions for the selection and causes [ST's memory usage to explode](https://github.com/sublimehq/sublime_text/issues/5950) when creating code actions annotation region.
Instead of creating a huge link that includes whole code action response, use response stored in the local `self._actions_by_config`. This was already the case when using "bulb" for code actions so apart from fixing the memory issue, it makes code more consistent.
Also small optimization to remove local `action_lists` and `all_actions` variables that weren't really used for anything and just increased heap memory usage.

optimize creation of code actions annotation region

---

plugin/core/protocol.py
tests/test_protocol.py

Rome returns an error response if we include `params: null` in the `shutdown` request:
```
:: [21:44:43.399] --> LSP-rome shutdown (6): None
:: [21:44:50.131] <~~ LSP-rome (6) (duration: 6732ms): {'message': 'Unexpected params: null', 'code': -32602}
```
Spec says that the `shutdown` request and the `exit` notification have `params: void` which I guess means that the property should not be set. `params` is an optional property in the spec so this is valid per spec:
```ts
interface RequestMessage extends Message {
/**
* The request id.
*/
id: integer | string;
/**
* The method to be invoked.
*/
method: string;
/**
* The method's params.
*/
params?: array | object;
}
```
In the spec there are some server-initiated requests like `workspace/codeLens/refresh` that have `params: none` …

don't send params for requests/notifications that don't expect them

---

plugin/documents.py

Regression caused by #2239 where I've switched from `make_command_link` to `make_link` where the latter does html escaping but former doesn't.
I've also removed text wrapping. It was rather aggressive at 30 characters. Since ST elides the text length itself to not overlap the code, I'm not sure we should be doing it. If for ascetic reasons we do want it then we should probably at least increase the number of characters.
Fixes #2245

fix regression causing `<br>` to show in code action annotation

---

plugin/core/views.py

The `%AppData%/Sublime Text/Roaming` path from the docstring of the `get_storage_path` function doesn't exist.
Could someone confirm whether the paths on macOS and Linux are correct?

Fix package storage path in a docstring description

---

plugin/core/views.py
plugin/goto_diagnostic.py
popups.css

Use `.color-muted` class instead of hardcoding color when showing diagnostic info.
Changed opacity of `.color-muted` from `0.5` to `0.6`. Should still be fine and is more consistent with other places.
Fixes #2255

use class for diagnostic info instead of hardcoding color

---

plugin/session_view.py

Avoids erasing regions if we're gonna re-add regions with same key right away.
Fixes #2272

Fix tagged diagnostics flickering on document changes

---

plugin/core/workspace.py

Ensure that the `_folders_exclude_patterns` list has same number of elements as `folders` so that accessing by index doesn't throw when `window.project_data()` is missing.
Fixes https://github.com/TerminalFi/LSP-copilot/issues/109

fix crash on checking excluded folders with missing project data

---

docs/src/customization.md
plugin/core/signature_help.py
stubs/sublime.pyi

Implements https://github.com/sublimelsp/LSP/pull/2259#issuecomment-1554831618.
It turned out we don't need the bugged "source_line" to decide whether there is a special color scheme rule for the active parameter. Instead, we can just compare the foreground colors.

Take font style of sighelp active parameter from color scheme

---

boot.py
plugin/core/configurations.py
plugin/core/registry.py
plugin/core/windows.py

Fixes `Error rewriting command lsp_recheck_sessions. Encountered infinite loop` warning on startup.
The warning is a bit misleading. It triggers not due to an infinite loop but due to triggering a window command directly from `plugin_loaded`. Basically means that triggering this command on startup had no effect but that's fine because at that point there is no sessions yet so it wouldn't really do anything anyway.
This PR removes the `LspRecheckSessionsCommand` command in favor of a more explicit notification triggered from the `WindowConfigManager` to the `WindowManager` to let it know that sessions should be restarted (the approach with using `LspRecheckSessionsCommand` was just a hack around the fact that `WindowConfigManager` did not have access to `WindowManager`).
Also note that …

fix "Error rewriting command" warning triggered on startup

---

plugin/code_actions.py
tests/test_code_actions.py

Previously we have been re-running Code Actions on Save if the document got modified by code action. This have in some cases resulted in a loop that would only terminate on timeout. Changed so that each server only has one chance to run code actions on save.
Fixes #2231
Fixes https://github.com/sublimelsp/LSP-typescript/issues/202

Only do a single pass on running code actions on save

---

plugin/core/protocol.py
plugin/core/views.py
plugin/hover.py

~~The implementation on the rust-analyzer side has changed so updating our code to follow.~~
~~ref: https://github.com/rust-lang/rust-analyzer/blob/7e19d99d4f0631b141d4d49a49cd5c504726cf9c/docs/dev/lsp-extensions.md#hover-range~~
Moving experimental functionality from here to respective packages:
- https://github.com/sublimelsp/LSP-rust-analyzer/pull/98
- https://github.com/scalameta/metals-sublime/pull/108

Remove experimental hover range support from core

---

plugin/core/sessions.py
plugin/core/views.py
plugin/session_buffer.py
plugin/session_view.py

Just a small refactor to get rid of publicly exposed `SessionBuffer.data_per_severity` and pass that data to `SessionView` instead.
Also add `_` prefix to private properties of `SessionBuffer` to make it clear that those are private.

refactor: get rid of `SessionBuffer.data_per_severity`

---

plugin/core/transports.py

On `int(headers.get("Content-Length"))` crashing in `JsonRpcProcessor.read_data`, we've assumed that it's an expected case happening on server exit. As far as I've observed, the typical data we get on process exit is a newline, but it can also be any other random output that doesn't conform to the HTTP header format.
In either of those cases we were just silently closing the transport, treating it as expected session shutdown.
Changed so that we only silently exit transport if the stdout was a single newline. In other cases propagate the output to the UI so that a crash dialog is shown.
I've also changed the `JSON decode error` case to also propagate the error to the UI instead of silently ignoring payload. I think this makes more sense but we'd have to see how it works out in practice. …

Show server crashed dialog on unexpected output in server's stdout

---

plugin/documents.py

I can reproduce this error in the console
```
File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 944, in on_activated_async
run_view_callbacks('on_activated_async', view_id)
File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 714, in run_view_callbacks
callback(*args)
File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 190, in exception_handler
return event_handler(*args)
File "C:\Users\jwortmann\AppData\Roaming\Sublime Text\Packages\LSP\plugin\documents.py", line 338, in on_activated_async
self._register_async()
File "C:\Users\jwortmann\AppData\Roaming\Sublime Text\Packages\LSP\plugin\documents.py", line 856, in _register_async
listeners = …
```

Fix a rare KeyError

---

docs/src/client_configuration.md
docs/src/language_servers.md
plugin/core/transports.py

https://github.com/sublimelsp/LSP/issues/2214
I have no idea if this is too hacky to be pulled, or what it breaks. It does work for my usecase tho. Would be cool if it doesn't find a server, it would just wait until one shows up instead of disabling the lsp until manually enabled again. Maybe i'll do it if I find it annoying enough.
If there would be small edits needed to be pulled I can totally do them, if there are fundamental issues I probably wont bother.

support client config with `tcp_port` but without `command`

---

plugin/documents.py

Just a tiny optimization to save one API call if there is nothing to do.

Small optimization for folding on load

---

plugin/core/protocol.py

In file: protocol.py, class: `Point`, there is a special method `__eq__` that raises a [`NotImplementedError`](https://docs.python.org/3/library/exceptions.html#NotImplementedError). If a special method supporting a binary operation is not implemented it should return [`NotImplemented`](https://docs.python.org/3/library/constants.html#NotImplemented). On the other hand, `NotImplementedError` should be raised from abstract methods inside user defined base classes to indicate that derived classes should override those methods. I suggested that the special method `__eq__` should return `NotImplemented` instead of raising an exception. An example of how `NotImplemented` helps the interpreter support a binary operation is [here](https://docs.python.org/3/library/numbers.html#implementing-the-ar …

Fix the implementation of a special method

---

third_party/websocket_server/__init__.py

In file: `__init__.py`, the list named `__all__` contains undefined names which can result in errors  when this module is imported. The module name should be of string type. I created a string for the module name. For more information regarding `__all__`, please read about importing fields from a package.  
Here is a [video](https://drive.google.com/file/d/1nOyQuHKcrDVAkIitdZS4O3g5hZLw6jV7/view?usp=drive_link) that demonstrates the type error that happens during import when the module name is not represented as a string. Here when `foo` is exported, it is not done as a string. So, when this is imported and used, we get an error.
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation …

Update a module name to allow import without type errors

---

docs/src/troubleshooting.md

Users just have to run the `LSP: Toggle log panel` from the command palette.
It is no longer required to manually enable `log_debug` command in the settings.

Update troubleshooting docs

---

plugin/core/sessions.py

This should fix #2326 and some other type issues for progress reporting, which can use an integer value for the progress token.

Fix type issues for progress notification

---

Default.sublime-keymap
plugin/selection_range.py

The "Expand Selection" command has a `fallback` argument, similar to "Goto Definition" and "Find References", which allows to invoke Sublime's built-in "Expand Selection" if there is no LSP result for the caret position or if the server doesn't have this capability. But for LSP's "Expand Selection" this fallback is enabled by default, while it is turned off for "Goto Definition" and "Find References". I did set the `fallback` to be enabled in #2124 to preserve former behavior of that functionality. But now I see no good reason why its fallback behavior should be different from the other commands, and I think it is confusing to see the context menu item for "Expand Selection" under the LSP submenu, even when there is no language server running at all (or if it doesn't have this …

Align "Expand Selection" fallback behavior with "Goto Definition" and "Find References"

---

plugin/documents.py

... by reducing the amount of API calls after every buffer change.
I think this should also fix #1958, but I haven't directly tested.

Improve signature help performance

---

Default.sublime-commands
plugin/core/windows.py
plugin/formatting.py
sublime-package.json

Handle multiple formatters

---

Main.sublime-menu
plugin/core/views.py
plugin/goto_diagnostic.py
plugin/symbols.py
stubs/sublime.pyi
stubs/sublime_plugin.pyi

Closes #2055.
I removed the colored region box highlighting for now, because I don't really like it personally and ST's built-in Goto Symbol doesn't have something like that. But it could be added back easily.
The implementation is a bit hacky, and there is one significant drawback: a user key binding for this command would need to be adjusted in the following way:
```jsonc
[
// Document Symbols (a replacement for ST's "Goto Symbol")
{
"keys": ["primary+r"],
"command": "show_overlay",
"args": {"overlay": "command_palette", "command": "lsp_document_symbols"},
"context": [{"key": "lsp.session_with_capability", "operand": "documentSymbolProvider"}]
},
]
```
Otherwise it won't work due to the input handlers in the command palette. I'm unsure if this breaking change would be acceptable. Maybe …

Add kind filter for Goto Symbol command

---

Default.sublime-commands

The shipped *Default/Default.sublime-commands* file per convention uses no ellipses (`...`) for the labels in the command palette. Ellipses seem to only be used for the menu items, for example compare `Preferences > Browse Packages...` from the main menu vs. `Preferences: Browse Packages` in the command palette. And you wouldn't filter for `...` in the command palette anyway.
Also lowercased `in`.

Remove ellipses in command palette labels

---

notification.css
plugin/core/message_request_handler.py
plugin/core/views.py

The popup shown on server triggering `window/showMessageRequest` was a bit out of date.
- Run the message through `text2html` so that newlines are respected.
- Tweak margins so that there is no big gap at the bottom of the content when actions are not specified.
Would be good to test this with some other servers to ensure that preserving newlines actually doesn't make it worse. I remember eslint used it but not sure what else.

minor visual tweaks to ShowMessageRequest popup

---

plugin/core/protocol.py
plugin/locationpicker.py
plugin/references.py

This is a part of the suggested enhancements from https://github.com/sublimelsp/LSP/issues/2084#issuecomment-1297691586.
With the setting `"show_references_in_quick_panel": true` enabled it will sort the results by URI and location and select the closest one if there is a result in the current file.
Note that the sort order can be OS dependent; for example Pyright uses `file:///C:/` format for Windows drive letters for files which are currently open, and `file:///c%3A/` format for unopened files. We could add another step to convert from URI to filename and sort those instead, but actually I found it quite useful that currently opened files are shown at the top of the list, when sorting by URI.

Sort and select closest result for Find References in quick panel

---

plugin/core/open.py
plugin/core/sessions.py
plugin/core/views.py
plugin/hover.py

Before this change, custom URI schemes would be delegated to the browser.
With this change, an attempt is made to look for a session that can handle the URI.
Moreover, if there is a fragment present in the URI, then it's assumed that that fragment encodes the (row, col) to jump to. This logic is somewhat dubious, but it's the only reasonable way (as far as I can see) to handle this.
Anoher approach could be to introduce a new on_open_uri2_async callback for plugins where they can also provide a (row, col) to jump to. But, then we would also require an opt-in switch for plugins where they would advertise that they can handle the "version 2" of on_open_uri.
(I've attached a GIF of goto-definition now working even for hover text links with Java, but I don't think the mouse cursor is visible)

Handle custom URI schemes in hover text links

---

plugin/symbols.py

Make input suppression for document symbols more reliable

---

plugin/symbols.py

... which was described in #2346.
This should make the LSP Goto Symbol overlay appear (almost) immediately again, even for very large files, by lazily calculating the character offsets from LSP row/col position (for highlighting and scrolling).
I tested with a file with 5000 symbols in it, where this saves 10k API calls.
---
By the way, it doesn't really make any sense that this could have been a cause for worse performance, because before the commit https://github.com/sublimelsp/LSP/commit/2e06833ca86cb88b4ae3acf663541551de675458 the same amount of API calls (for `SymbolInformation[]` response) were done as well (`range_to_region` function), or even twice the amount (for `DocumentSymbol[]` response). Perhaps the ListInputHandler is just slower than `window.show_quick_panel`, in …

Fix performance regression in Goto Symbol overlay

---

LSP.sublime-settings
messages/1.27.0.txt
messages/1.30.0.txt
plugin/core/types.py
sublime-package.json

The panel feels archaic and less user-friendly due to issue with navigating results.
The default should IMO be as close to what ST offers as possible.

change default value of show_references_in_quick_panel to true

---

docs/src/language_servers.md

Hi there,
there is another notable LSP implementation for Ruby, called `ruby-lsp`. I added it to the docs.
Config inspired by their docs: https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md#sublime-text-lsp
Please feel free to request changes or do them on your own if I missed something. Thanks!
Cheers!

Add "ruby-lsp" section to documentation

---

plugin/core/open.py
stubs/sublime.pyi

Closes #718
---
*Edit:* Oh, the behavior of the `group` argument doesn't match builtin `window.find_open_file` at the moment. I will fix it.

Prefer active view instead of leftmost one for Goto commands with split views

---

plugin/core/open.py
stubs/sublime.pyi

A small fix for the last PR, which was merged hastily :-)
`Window.active_view_in_group` could return `None` if a nonexistent group is passed. This shouldn't happen and could be considered the user's fault, but better safe than sorry.

Small fix to guard against None

---

Default.sublime-commands
Main.sublime-menu
boot.py
plugin/code_lens.py
plugin/core/constants.py
plugin/core/sessions.py
plugin/session_view.py

Code Lens is one of those features that is IMO too annoying to have always enabled but can be useful to use once in a while to catch un-referenced symbols and such so I think it deserves its own toggle like that.
Threw it in very quickly based on Inlay Hints and Hover Popups toggles. Might have missed something.

Add menu item to toggle code lenses

---

plugin/core/signature_help.py
plugin/core/views.py
plugin/documents.py
popups.css
tests/test_signature_help.py

A little tweak which adds a `<kbd>` tag for the keyboard keys and also a `<body>` tag[^1] with [unique id](https://www.sublimetext.com/docs/minihtml.html#best-practices) for the signature help popup.
[^1]: The `<body>` tag will not be the outermost tag in the minihtml, because mdpopups still adds its own `<div>` wrapper tag around it, but there is nothing we can do about that and it won't affect the functionality.
I have adjusted the CSS style for the `<kbd>` tag a bit, beacause the default style from mdpopups uses a too high contrast against the background color in my opinion. The style will also apply to regular hover popups if they contain literal `<kbd>` HTML tags.
|     | Mariana | Breakers |
| --- | ------- | -------- |
| Before | …

Small visual tweak for signature help popup

---

plugin/documents.py

This will show a popup with all diagnostics from the line (except hint severity), sorted by severity, when you hover over a gutter icon. It is compatible with the code actions popup if applicable for the current caret position and using the "bulb" setting.

Show diagnostics popup when hovering over gutter icons

---

plugin/core/url.py
tests/test_url.py

The `sublime` part in `buffer://sublime/[view_id]` URIs that we were using for unsaved buffers triggered an infinite loop in pyrights file traversing code. While I don't pretend to understand its code fully, the `sublime` in our made-up URIs is not really necessary or makes a lot of sense even.
Fixes https://github.com/sublimelsp/LSP-pyright/issues/281

fix unsaved buffers pyright incompatibility

---

plugin/core/configurations.py
plugin/core/types.py
plugin/core/url.py
plugin/core/windows.py
plugin/hover.py
tests/test_url.py

Improve buffer URI format alternative

---

docs/src/language_servers.md

Hi there,
as a follow up to https://github.com/sublimelsp/LSP/pull/2352 I tested enabled diagnostics for the solargraph server. It works fine so far so I do not see any reason not to "enable" it per default in the docs.
As always, please feel free to request changes or do them on your own if I missed something. Thanks!
Cheers!

docs: Enable "diagnostics" in solargraph example

---

plugin/code_lens.py

Don't use the response error as the text for the code lens that failed resolving. That can resolve in stuff like this:
The protocol errors are not really meant to be surfaced in an UI like that.
This is how it looks after:
Not married to the styling or the text itself...

use simple error for code lenses that failed resolve

---

README.md

1. When you hover over the badges in the current Readme, the spaces between the buttons are underlined, which looks weird. The cause seems to be that the closing `</a>` tag is on a new line with indentation, and this indentation will become part of the link.
[readme.webm](https://github.com/sublimelsp/LSP/assets/6579999/0214efa3-6375-4801-b0fd-5cac964f13ef)
2. Updated the label of the "docs" badge with the link target location.
3. I would expect that when I click on the Discord badge, that it will redirect me to the discord page, and not just scroll the page down a little bit (where it is even unclear where the link points to, because corresponding Discord link is at the bottom of the Readme page, so the anchor will not end up at the top of the browser's viewport). Especially because the …

Small tweaks for Readme page

---

Main.sublime-menu
boot.py
plugin/code_actions.py
plugin/completion.py
plugin/core/constants.py
plugin/core/registry.py
plugin/core/sessions.py
plugin/core/tree_view.py
plugin/core/typing.py
plugin/core/views.py
plugin/core/windows.py
plugin/diagnostics.py
plugin/documents.py
plugin/goto_diagnostic.py
plugin/hierarchy.py
plugin/hover.py
plugin/locationpicker.py
plugin/session_view.py
plugin/symbols.py

These are a bunch of minor refactorings that I wanted to do. Most of it just moves some code to other places where it makes more sense, but there are no functional changes. See the individual commits for details.
Everything touched by this PR should just be internal functions and constants, so I believe it should be safe to do. At some time the public API for LSP-* packages in `LSP/plugin/__init__.py` should probably be revised and extended, because various packages already import utility functions directly from `LSP/plugin/core/views.py`.
To be released together with:

Various refactorings

---

.github/workflows/main.yml
pyrightconfig.json
stubs/sublime.pyi
stubs/sublime_plugin.pyi
tox.ini

- Check stubs using mypy. Noticed some type issues when checking `lsp_utils`.
- Ignore `reportIncompatibleMethodOverride` pyright warning which is reported in the new pyright version because it has introduced a new, stricter `typeCheckingMode` "standard" that is enabled by default.

Fix some mypy type issues in stubs

---

plugin/session_buffer.py

I've reproduced a case where document state gets desynchronized on the LSP side. The issue seems to be only reproducible when there are at least two servers starting on a file (or maybe it just makes it more likely to happen). The easiest way to reproduce is to start ST, (re)open a file on which at least two servers will get started and start typing immediately. After undoing the changes LSP will show some stale errors.
https://github.com/sublimelsp/LSP/assets/153197/8af0eba7-9626-4496-9cb4-31f6971b3070
This happened on opening the file. We have applied all latest changes through `didOpen` when the change count was, let's say, 1, but there was also already pending text change notification with a change count of 1 which we have applied again a little later.
To fix, ignore text change …

fix document state getting out of sync in rare cases

---

docs/src/language_servers.md

As always, please feel free to request changes or do them on your own if I missed something.
Thanks & cheers!

docs: Move Steep in Ruby Section & minor cleanups

---

Default.sublime-keymap
docs/src/keyboard_shortcuts.md
plugin/save_command.py

Closes #2371 (?)
Using this argument, you can add a key binding (or menu entry or command palette entry) to save all files, without being bothered by save dialogs for new buffers.
Also did a small adjustment to the caption of the example key binding, to make it clear that `lsp_save_all` only saves views for which a language server is running.

Add only_files argument for lsp_save_all command

---

Default.sublime-keymap
plugin/save_command.py
tests/test_code_actions.py
tests/test_single_document.py

This might be not very relevant in practice, because `lsp_save` is just an internal command.
But I think this implementation to just pass through the arguments is cleaner and more flexible than hardcoding a single argument, especially since `lsp_save` is meant to be a replacement for `save`.

Support all arguments of native save in lsp_save command

---

plugin/core/transports.py

Plugin fails with "list index out of range" error when running on windows and a server is configured with empy `command` and non-empty `tcp_port`.
Looks like regression of #2118, but it also doesn't look like it was really fixed.

fix empty command behavior on windows

---

docs/src/language_servers.md

Add [Stimulus LSP](https://github.com/marcoroth/stimulus-lsp) to Language Servers docs section.
Config inspired by the [Neovim install instructions](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#stimulus_ls).

docs: Add `stimulus-lsp` to language_servers.md

---

plugin/edit.py
plugin/formatting.py
stubs/sublime.pyi
tests/test_edit.py

Add opt-in handling for placeholders in text edits which define the position of the cursor after text edits are applied. This is required (well, not required but it improves experience) for custom rust-analyzer `moveItem` command that I'm adding support for in https://github.com/sublimelsp/LSP-rust-analyzer/pull/111#pullrequestreview-1805125212
Based on rust-analyzer extension code: https://github.com/rust-lang/rust-analyzer/blob/f7823f31069c6ec5be24d0497847bf1bb8a4c683/editors/code/src/snippets.ts#L41-L87
Also check rust-analyzer description of their custom snippet text edit: https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#snippet-textedit

feat: support setting cursor position in text edits

---

Default.sublime-commands
lsp_utils.sublime-settings
sublime-package.json

Doing as suggested in https://github.com/sublimelsp/LSP/pull/2388 and moving `lsp_utils` settings into `LSP`. A temporary step until we migrate to a new plugin API that I've started looking into.

include lsp_utils settings in LSP

---

plugin/__init__.py
plugin/color.py
plugin/completion.py
plugin/core/edit.py
plugin/core/sessions.py
plugin/edit.py
plugin/formatting.py
plugin/inlay_hint.py
plugin/rename.py
tests/test_edit.py
tests/test_single_document.py

Refactor per discussion in https://github.com/sublimelsp/LSP/pull/2389#discussion_r1447905532
- Make `lsp_apply_document_edit` take `[TextEdit]` rather than parsed custom structure.
- Remove private and deprecated `LSP.plugin.core.edit.apply_workspace_edit` function (use `session.apply_workspace_edit_async` instead)
- Remove private `LSP.plugin.formatting.apply_text_edits_to_view` function (use `LSP.plugin.apply_text_edits` instead)
- Move `LSP.plugin.core.edit.parse_text_edit` to `LSP.plugin.edit._parse_text_edit` (and make "private")
- Change return value of private `LSP.plugin.core.edit.parse_workspace_edit` function (returns unparsed edits)
- Expose `apply_text_edits` as a public API
In one test I had to change the test for overflow handling from passing `sys.maxsize + 1` offset to …

refactor: make LspApplyDocumentEditCommand take plain TextEdits

---

docs/src/language_servers.md

Hi! Would it be possible to add [asm-lsp](https://github.com/bergercookie/asm-lsp) to the docs?
I wasn't super sure what to list for the selectors in the configuration. Checking the selector on my test files (see `samples/` in the project's repo) yielded `text.plain`. I tried finding a more comprehensive lists of scopes to use a more assembly-specific scope, but the best I could find was [this](https://stackoverflow.com/questions/30153110/get-all-scope-names-on-sublime-text-3) stack overflow post. The post listed `source.disasm`, but I struggled to find a file that used that. I tested the configuration as-is and it works, but I'm happy to change anything if I've made a mistake :)

docs: add asm-lsp

---

plugin/core/windows.py

`wm.destroy` is called in two cases:
- from `EventListener.on_pre_close_window`, before the window is closed
- from `plugin_unloaded` hook when LSP package is unloaded
The changed line is triggered in the former case.
As the [comment in `WindowManager.destroy()` says](https://github.com/sublimelsp/LSP/blob/f10f45e4323fbe39e2f138dd9f7ce47544c110d6/plugin/core/windows.py#L402-L406), we should (have to!) call it from the main thread when the plugin is unloaded. But afaics, we don't need to call it from the main thread when closing a window so change the code to not do that.
Calling it from the main thread on window closing triggers a `KeyError` exception due to `DocumentListener.on_close` being triggered first and `DocumentListener.on_session_shutdown_async` later. The latter removes session …

fix KeyError exception triggered on closing a window

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/src/troubleshooting.md

Refactored "Common problems" section:
- Combined `Popup error Language server <your_server_language_name> has crashed` and `LSP cannot find my language server` into a single `Error dialog saying Failed to start...` section. That's because both of those issues trigger the same error dialog, only with some potentially different errors at the bottom of the dialog.
- Removed some very obscure `the language servers may have dependencies that should also be in your PATH` suggestion specific to haskell server and instead linking to "Self help" section that should provide more generic understanding of whatever the issue might be.
- Removed "Known issues" header since the `Completions not shown after certain keywords` section can easily be considered "Common problems" instead. Note that this is …

docs: rewritten "common problems" section

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/src/troubleshooting.md

Rewritten self-help instructions.
I wanted it to be something that we can link people to when asking for additional information without having to repeat ourselves all the time. The old text was a bit all over the place. Now it's hopefully more precise and concise and will get us the stuff we need.
Feel free to suggest improvements as english is not my forte and I'm not particularly good at writing docs. :)
(we can potentially even link to it in an issue template)

docs: rewrite self-help instructions

---

plugin/rename.py

I saw that this command has two arguments `position` and `point`, with one of them being unnecessary. Currently `position` is just an internal argument used to pass it to itself when the command is re-triggered after prepareRename response. It seems that `position` existed before `point` was added (to LspTextCommand), but now we can use `point` for that instead. The logic should be completely unaffected by this change, and the line with `location = ...` (105) can be simplified because `get_position` also prefers `point` if given.

Remove unnecessary argument from lsp_symbol_rename command

---

plugin/core/constants.py
plugin/core/sessions.py
plugin/documents.py
plugin/hover.py
plugin/session_view.py

Instead it can be stored on the DocumentSyncListener instance, which is created once per view (by ST).
I think view settings should only be used to create context keys (`setting.lsp_active`) or to potentially interact with other packages (`lsp_uri` - not sure if that was the intention, but I think this setting is okay). The hover provider count is only an internal variable of the LSP package, so it doesn't really belong into the settings.

Remove hover provider count view setting

---

docs/src/language_servers.md

I added instructions to the `language_servers.md` file on how to configure the Verible LS (probably the most mature, open source LS for SystemVerilog) in conjunction with the Sublime SystemVerilog syntax package.
I can also confirm formatting with `LSP: Format File` is working as expected.
Thanks for your feedback.

Add SystemVerilog language server setup guide

---

plugin/core/types.py

ST 4173 tweaks how selector scoring works resulting in LSP no longer functioning.
As per the comment there seems to be a misunderstanding of how `sublime.score_selector` works. The entire selector must always match for a non-zero score, so if the goal is to check if it's not empty and matches then checking for `>= 8` is simply wrong.

Fix usage of sublime.score_selector

---

plugin/core/sessions.py
plugin/hover.py
tests/setup.py

Prevent that the tab selection changes if a WorkspaceEdit affects files that are not currently open in the window (because `window.open_file()` focuses the new tab).

Keep tab selection and focus when applying WorkspaceEdit

---

boot.py
plugin/core/panels.py
plugin/core/views.py
plugin/edit.py
plugin/rename.py
tests/test_rename_panel.py

1. Currently the "Dry Run" functionality for a multi-file rename operation is a bit awkward to use, because after you have looked at the rename locations which are shown in the panel, you need to run the rename command again, including typing of the new name, to actually do the rename. This PR adds "Apply" and "Discard" buttons into the panel to save a bit of time. In theory there could be wrong changes applied if you edit the view(s) first, before clicking the "Apply" button (because the document version is not mandatory in the LSP edits), but in that case I'd consider it to be the user's fault (or does anyone have an idea how to prevent it?). The buttons will automatically hide after they are clicked.
2. Changes are now displayed in the panel using Sublime's inline diff feature. Perhaps …

Enhancements for the rename panel

---

plugin/core/types.py
plugin/core/url.py
plugin/locationpicker.py
tests/test_url.py

With a recent Pyright version, some features don't work (i.e. error in console or error dialog) for package ressource files (View Package File from the command palette).
This is because we use `Packages` as the authority name in `res:` URIs, and the authority is converted to lowercase by vscode-uri library in the server responses. Instead, we should move `Packages` to be part of the `path` component of the URI and leave `authority` empty.
See: https://github.com/microsoft/pyright/issues/7495
---
The only case where I can find `res://` being used in the Sublime Text API is in minihtml for the `<img>` element, see https://www.sublimetext.com/docs/minihtml.html#tags:
> `<img>` — supports PNG, JPG and GIF images from `file://`, `res://` and `data:` URLs.
For example with Terminus installed …

Fix URI format for res scheme

---

.github/workflows/main.yml
tests/test_configurations.py

This commit adopts `unittesting.ViewTestCase` to run view related test cases.
ViewTestCase ...
1. provides `view` and `window` members pointing to a dedicated view, being created for testing.
2. ensures not to close empty windows, which was probably the most likely reason for unittests failing before on MacOS.

Fix failing python 3.8 unittests on MacOS

---

plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/windows.py

I think it's not very useful to print those messages into the LSP log panel, in addition to the payload log. Those lines are just redundant there, for example
```
LSP-pyright: Received change text document command for closed file file:///d%3A/code/Python/LspTest/main.py
:: [22:05:28.199] <-  LSP-pyright window/logMessage: {'message': 'Received change text document command for closed file file:///d%3A/code/Python/LspTest/main.py', 'type': 1}
```
Instead, if `"log_debug"` is enabled, I suggest to log them into the console, similar to the other log/debug messages like
```
LSP: enabled configs: [...]
LSP: starting [...]
LSP: LSP-pyright: supported code action kinds: [...]
```
Error messages are additionally printed to the status bar (only if `"log_debug"` setting is enabled).

Print messages from window/logMessage into console instead of LSP log panel

---

docs/src/language_servers.md

closes #2445
Use default port for LSP suggested by godot-editor ->
https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html#lsp-dap-support

[Docs] Change default godot-editor port 

---

docs/src/language_servers.md

Just added a quick guide how to make LSP package to work with solidity, I've also tried to make [solc](https://docs.soliditylang.org/en/v0.8.23/installing-solidity.html#macos-packages) lsp to work, but [hardhat-vscode](https://github.com/NomicFoundation/hardhat-vscode/tree/development/server) feels much more suitable and easier to set up.

Added solidity language server setup guide

---

docs/mkdocs.yml

Reported on Discord.
> FichteFoll — Yesterday at 11:31 AM
FYI, I just noticed that you have a discord link to a channel in the footer of the docs (i.e. https://lsp.sublimetext.io/). This does not work for people not already part of the server. Please use the invite link in the channel topic instead (also mentioned in

Fix Discord link

---

plugin/core/sessions.py
plugin/session_buffer.py

It's always more correct to first check capability through session buffer in case server registers capability dynamically with a selector.
Resolves #2452

fix: check semantic capability through session buffer

---

plugin/core/typing.py

Since we are now in py38, we don't need most of type polyfills.
`# noqa: F401` is to suppress `import but no used` linter warnings.

Fix LSP.plugin.core.typing with py38

---

plugin/core/typing.py

This commit replaces various homegrown type definitions by imports from typing_extensions module.

Make more use of typing_extensions module

---

.github/workflows/main.yml

It seems like the UnitTesting action is currently broken on Mac in some way.
> Package Control: The library "coverage" is not available for Python 3.3
Let's try if this fixes it, and I don't think we need or have used the coverage report anyway.
```
Terminated Sublime Text
Package Control: Installing 6 libraries...
Package Control: The library "coverage" is not available for Python 3.3
Package Control: Installed library "wcmatch" 1.2.1 for Python 3.8
Package Control: Installed library "coverage" 7.5.0 for Python 3.8
Package Control: Installed library "bracex" 2.1.1 for Python 3.8
Package Control: Installed library "mdpopups" 4.2.2 for Python 3.8
Package Control: Installed library "typing_extensions" 4.11.0 for Python 3.8
Package Control
Sublime Text needs to be restarted for installed or …
```

Disable CI on Mac

---

.github/workflows/main.yml

UnitTesting 1.8.1 excludes coverage dependency from python 3.3 on arm platform.
GH Actions seem to have switched MacOS to ARM platform recently.

Re-enable CI on Mac

---

plugin/core/views.py

A bug that was missed, resulting from importing the `enum` stdlib on Python 3.8 (compare https://github.com/sublimelsp/LSP/pull/2446#issuecomment-2059553794).

Fix CodeActionTriggerKind enum access

---

third_party/websocket_server/websocket_server.py

Avoid polluting other packages.
closes #2477

Remove logging.basicConfig()

---

plugin/code_lens.py
plugin/completion.py
plugin/core/registry.py
plugin/semantic_highlighting.py

LspTextCommands opt-in to mouse events, but not all are designed to handle required events. Therefore they fail, when being bound to mouse keys.
see https://forum.sublimetext.com/t/mouse-map-always-attach-current-event-in-its-args/72502/4
This commit opts-out those commands.

Fix arguments error if commands are bound to mouse keys

---

plugin/core/sessions.py

closes https://github.com/sublimelsp/LSP/issues/2494
This API allows LSP-* to hook into when a notification is received form the language server.

Add on_server_notification_async API

---

docs/src/commands.md
plugin/execute_command.py

Should close #2515
(And a small change in the docs to use proper double quotes `"` instead of `'` for the JSON objects.)

Add variable for VersionedTextDocumentIdentifier to use with lsp_execute

---

plugin/session_buffer.py
plugin/session_view.py

I've noticed an issue with semantic tokens being removed when restarting a session that doesn't provide semantic tokens, when there is also another session active that provides semantic tokens.
In this case there are both LSP-typescript and LSP-volar sessions active in the view and LSP-typescript is the one that provides semantic tokens. On restarting LSP-volar, semantic tokens disappear and don't show up until changing the document or restarting LSP-typescript:
https://github.com/user-attachments/assets/c6021c53-a86c-4ed2-ab5d-31adf7fc894f
I've made semantic token regions session-specific so that initializing a session doesn't overwrite existing semantic token regions.

use session-unique region keys for semantic tokens

---

plugin/core/registry.py
plugin/core/sessions.py
plugin/documents.py

Use of generators for retrieving the session is IMO completely unnecessary (correct me if I'm missing something).
1. This is not an expensive operation that would benefit from being interrupted early. Getting all sessions and returning a list is not gonna be slower. It will potentially even be faster as I imagine that generators have some overhead.
2. Passing generators around can lead to errors or at least confusion since the values can only be retrieved once from it. In cases like https://github.com/sublimelsp/LSP/blob/603632ea703d6296348680890859c148ac85229a/plugin/core/registry.py#L24-L33 where we pass generators and disguise it as `Iterable[Session]`, there is no way of knowing that the code will fail if trying to iterate sessions twice.

remove unnecessary use of generators for session retrieval

---

plugin/documents.py
tests/test_code_actions.py

Code actions and document highlights use the same debounce time (FEATURES_TIMEOUT), so their debouncing can be combined into a single function to save some (many) unnecessary `sublime.set_timeout_async` calls.

Remove unnecessary parallel debouncing on selection change

---

plugin/goto.py

If `point` is explicitly given as a command argument, currently the best session is still selected based on the cursor position.

Fix not considering given point when choosing best session in Goto commands

---

plugin/documents.py

Currently if LSP (this package) is installed, it runs quite some code in the background whenever the callbacks from [`DocumentSyncListener`](https://github.com/sublimelsp/LSP/blob/a6b17a4aa4d10d8ddc225413d221c4241b877f8b/plugin/documents.py#L139), which is a subclass of `sublime.ViewEventListener`, are triggered. This happens for *all* views, not only when a server is active. For example it creates an empty (if no server is running) `sublime.CompletionList` and schedules to run more code on the async thread in https://github.com/sublimelsp/LSP/blob/a6b17a4aa4d10d8ddc225413d221c4241b877f8b/plugin/documents.py#L555-L560
or it runs the debouncing in https://github.com/sublimelsp/LSP/blob/a6b17a4aa4d10d8ddc225413d221c4241b877f8b/plugin/documents.py#L384 via `sublime.set_timeout_async` each …

Make DocumentSyncListener more efficient if no server is running

---

plugin/completion.py

I haven't noticed this issue in practice (or if I did then it's subtle enough to not raise suspicion) but when looking at this code I've realized that the case when completions are canceled is not quite right since in that case we'd tell ST that we got empty completions and we'd pass the `sublime.AutoCompleteFlags.NONE` flag. The flag is the issue since we don't consider user's settings like `inhibit_snippet_completions` and `inhibit_word_completions` so in the case when completions would get canceled, we'd let ST show buffer and snippet completions which is not what the user expects.
It's kinda hard to test. I think this is only a potential issue for servers that return dynamic completions (like pyright) since then it's more likely that the completion request will get canceled on typing. …

fix: respect user-preferred flags when canceling completions

---

plugin/code_actions.py
plugin/session_buffer.py

Fix issue with code actions on save not fixing diagnostic errors that were just introduced, when saving immediately after changing the document.
For servers that support the pull diagnostics model we have to assume that the server doesn't re-compute diagnostics until client asks for them. Thus we have to ask just before sending code actions request or otherwise it might not provide fixes for issues that were just introduced.
To test, with a LSP-eslint running on a file, create an issue (like a trailing space) and save the file immediately. The issue is often not fixed on the first try.
Fixes #2511

fix: code actions on save not fixing issues if saving quickly

---

plugin/core/sessions.py
plugin/session_buffer.py

On document change, it makes sense to cancel pending semantic tokens/pull diagnostics requests as early as possible rather than waiting for the debounce timeout and potentially failing to cancel request on time and wasting resources on handling those.

fix: cancel pending requests as early as possible

---

LSP.sublime-settings
plugin/core/constants.py
plugin/documents.py
plugin/hover.py
plugin/references.py
plugin/session_buffer.py
plugin/session_view.py
tests/test_code_actions.py

... continuing from #2537.
There should be no functional change.

More small code style improvements

---

.github/workflows/main.yml
plugin/references.py
tox.ini

For me running `tox` locally was broken for quite some time because the outdated flake8 version reported many dubious errors (not sure why it didn't in the GitHub Actions CI). This should make it possible to run `tox` again without errors.
---
Also I wonder why the unit tests on Mac are randomly broken sometimes. It always seems to be caused by a timeout in a file watcher test. Maybe it would help to increase the timeout value, or could there be a different underlying issue?
https://github.com/sublimelsp/LSP/blob/55e2068eff99dc5e43019f9357137f8ac604c9d1/tests/setup.py#L20

Bump flake8 to latest version

---

plugin/documents.py

According to https://github.com/sublimehq/sublime_text/issues/6249#issuecomment-2502804237 this should prevent lag/freezing if there is an excessive amount of completion items.

Set completions from the async thread

---

plugin/core/sessions.py

There is also the newer `Session.set_config_status_async` which does basically the same thing, and there is no point in having two methods doing the same.
`set_config_status_async` is nicer because it prints the status message directly after the config name in brackets, so it's clearer that this message belongs to the LSP server.
At a later time we could remove the method bodies of the two deprecated methods (replace with `pass`).

Deprecate Session.set_window_status_async

---

plugin/inlay_hint.py

Fix LspToggleInlayHintsCommand not initializing

---

boot.py
plugin/documents.py

It was fixed upstream, so we can get rid of accessing the undocumented (private) `sublime_plugin.view_event_listeners` dict on current builds.

Disable workaround for on_post_move_async listener not triggering

---

docs/src/language_servers.md

Without passing the current directory, `srb` fails to start, with this error: 
```
Sorbet's language server requires a single input directory. However, 0 are configured: []
```
In Sublime, the LSP fails to start 5 times then quits.

Sorbet requires a directory be passed to the typecheck command

---

docs/src/language_servers.md

This adds Marksman (via [LSP-marksman](https://github.com/sublimelsp/LSP-marksman)) to the Markdown section in the documentation.

Add docs for Marksman

---

docs/src/language_servers.md

A [MediaWiki Wikitext](https://www.mediawiki.org/wiki/Wikitext) language server is available from [wikitext-lsp](https://npmjs.com/package/wikitext-lsp), which is also used in a [VSCode MediaWiki extension](https://marketplace.visualstudio.com/items?itemName=Bhsd.vscode-extension-wikiparser).

Add docs for MediaWiki language server

---

docs/src/language_servers.md

Since Herb Language Server already has official installation instructions for Sublime Text, this commit refers to them.

Update Herb installation instructions

---

plugin/documents.py
plugin/session_buffer.py

Skip `textDocument/diagnostic` request if we have already received diagnostics for the current view version.
For servers that support pull diagnostics, we would re-ask for diagnostics on each selection change (through the code that requests code actions), even if the view hasn't changed.
In the case of the bug linked below, this would even trigger an infinite loop as the cache in the `CodeActionsManager` that caches the response would not cut the loop short if two views into the same file are opened and selection range is different in each.
Fixes #2609

fix: skip diagnostics pull if diagnostics already received

---

plugin/execute_command.py

The error dialog that occurs when trying to run `workspace/executeCommand` (for example from a code lens) with a command that is not implemented on the server side is pretty annoying, so let's print to the status bar instead.
I wonder if we should maybe even prevent the request for commands that are not listed in the server capabilities (from initialize response or dynamic registration), and directly print a "command not implemented" message instead. Or are there any servers which handle commands that are not advertised its capabilities?

Don't show error dialog for failed workspace command

---

plugin/code_actions.py
plugin/core/protocol.py
plugin/core/sessions.py
plugin/core/views.py
tests/test_code_actions.py

- the logic should be unchanged here. I just had to extract the "kind includes other kind" logic out of this code and place it somewhere where `Session` could access it.
- added `kind_includes_other_kind` function
- Fixed a bug where a refactoring code action would not always trigger save with `refactoring_auto_save` enabled. It only worked if the code action had `refactoring` kind exactly and not if it had more specific one like `refactoring.move`. This is fixed by the new `kind_includes_other_kind` function.
- Allow passing `is_refactoring` to `Session.execute_command` to allow for all edits triggered within this request to be treated as refactoring and trigger the `refactoring_auto_save` logic.  (see https://github.com/sublimelsp/LSP-typescript/pull/278 to see the code that uses that)

fix: respect `refactoring_auto_save` in more cases

---

plugin/core/sessions.py
plugin/session_buffer.py
tests/test_server_notifications.py
tests/test_session.py

Somehow I still keep running into outdated diagnostics ;) I've identified one more problem.
When the response for pull diagnostic comes back, in `SessionBuffer._on_document_diagnostic_async` the `version` can be 5 (for example) but by the time the code gets to `SessionBuffer.on_diagnostics_async` the `view.change_count()` can increase. Since we didn't pass the actual diagnostics `version` to `SessionBuffer.on_diagnostics_async`, we assumed that those diagnostics are for the latest version of the view (6 in this example) and then never requested the more recent diagnostics (actual version 6 diagnostics) later. Fix by passing the actual version of the diagnostics around so that we never show outdated diagnostics due to not getting latest diagnostics.
Also reset `_diagnostics_version` on …

Fix another case of outdated diagnostics
